### ISSUE TITLE
Species retrieving limitation using API

### ISSUE THREAD

**Issue by javierseixas** [gbif/registry#102]
I want  to get all species recorded in GBIF Backbone Taxonomy Dataset. The problem happens when I specify an offset value greater than 100000 in the request query. I get the following error:

```
{
    "body": "Offset is limited for this operation to 100000"
}
```

So, apparently I would only obtain the first 100000 records. According to the dataset metrics, it has more than 5.800.000 records. How I can get all them?

Thanks for your help.

**Comment by MattBlissett** [comment]
Hopefully your question was answered elsewhere (apologies if not), but for anyone else finding this the full GBIF taxonomic backbone can be downloaded from https://hosted-datasets.gbif.org/datasets/backbone/README.html, via the links on https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
