### ISSUE TITLE
Provide an Ansible script 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#105]
As ALA evaluate replacing the Collectory, they have asked for a simple Ansible script to deploy an empty registry for exploration. This is 1) to help gain comfort that if for any reason ALA need to deploy the registry in their own stack it is tested and 2) to allow ALA devs to explore necessary schema and WS changes easily using familiar tools. 

Ideally this would come with a vagrant (or similar) script to start with an empty Ubuntu16 installation.

The stack should deploy (initially for development purpose):
- PostgreSQL (relatively empty other than admin account or with a redacted export of GBIF.org)
- Java WS stack running in Jetty / Tomcat
- Apache or similar running the Admin console
- RabbitMQ with the registry-change and doi-updater queues in place

**Comment by timrobertson100** [comment]
@djtfmartin - do you have preferences in tomcat/jetty or Apache / NGinx etc and please can you confirm Ubuntu16 is the preference?

**Comment by MattBlissett** [comment]
Work is in this repository: https://github.com/MattBlissett/gbif-registry-ansible

So far, there is Postgres, Rabbit (untested) and the Registry webservice (only slightly tested, no admin user yet).

The webservice is run with the embedded Jetty: 

```
/usr/bin/java -jar registry-ws.jar -conf application.properties …
```

**Comment by timrobertson100** [comment]
Tested - thanks @MattBlissett
