### ISSUE TITLE
Limit on specimen count for institutions

### ISSUE THREAD

**Issue by kcopas** [gbif/registry#109]
Besides not being able to save changes to the ZMUC record under institutions, I note that there appears to be a hard limit of 9,999 for the "number specimens" field. I'd assumed this was meant to reflect the 'number of specimens', in which case this seems absurdly low.

**Comment by MortenHofft** [comment]
indeed. closed by https://github.com/gbif/registry-console/commit/3a3bd870fab801a44c2b23e01007e64faf0e5d66

**Comment by MattBlissett** [comment]
A more reasonable limit is 100M. (NHM london has >30M)
