### ISSUE TITLE
publisher search free text search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#11]
Publisher search is behaving differently than other endpoints. Filters seem to be OR instead of AND

example:
http://api.gbif.org/v1/organization?q=montreal   2 results
vs
http://api.gbif.org/v1/organization?q=montreal&country=CA  31 results

also 
results seems to be missing:
a search for the exact title: [Université de Montréal Biodiversity Centre](https://demo.gbif.org/publisher/search?q=Universit%C3%A9%20de%20Montr%C3%A9al%20Biodiversity%20Centre) isn't returning [The publisher](https://demo.gbif.org/publisher/ff7bd5db-b724-4932-b496-10ea298851f9)

**Comment by fmendezh** [comment]
The organization/publisher search is now using and AND for all the filters and the API seems to return the right results for exact matches see [Université de Montréal Biodiversity Centre ](http://api.gbif.org/v1/organization?q=Universit%C3%A9%20de%20Montr%C3%A9al%20Biodiversity%20Centre)
However, the portal search doesn't return any result

**Comment by MortenHofft** [comment]
Wonderful, 

> However, the portal search doesn't return any result

that is just because the link redirect scrambles the url it seems. 
The [search works](https://www.gbif.org/publisher/search?q=Universit%C3%A9%20de%20Montr%C3%A9al%20Biodiversity%20Centre) as I would expect.
