### ISSUE TITLE
Resolve GRBIO cool URIs and other identifiers

### ISSUE THREAD

**Issue by asturcon** [gbif/registry#112]
The DB tables collection_identifier and institution_identifier contain all the identifiers migrated from GRBIO. We need to create a new method in the API that resolves these identifiers to the corresponding entity (collection or institution). 

After that, we have to setup a redirect in Varnish for these URLs. For instance, a request to http://grbio.org/cool/v7ji-e2y0 should be redirected to http://gbif.org/grscicoll/{{collection OR institution}}/{{UUID}}

**Comment by MattBlissett** [comment]
> After that, we have to setup a redirect in Varnish for these URLs. For instance, a request to http://grbio.org/cool/v7ji-e2y0 should be redirected to http://gbif.org/grscicoll/{{collection OR institution}}/{{UUID}}

I envisage a webservice endpoint in the registry that receives these requests, and deals with them (302, maybe content negotiation to decide between the JSON and HTML if that's a requirement). Varnish should only send the request to the registry-ws backend.

**Comment by MattBlissett** [comment]
I've made up an endpoint, `/grscicoll/resolve` (do change this if it doesn't fit).

It should accept requests like these:

* `/grscicoll/resolve/dev.grbio.org/cool/035p-ba0x` 
  which is from `http://dev.grbio.org/cool/035p-ba0x`
* `/grscicoll/resolve/dev.biocol.org/urn:lsid:biocol.org:col:35158`
  which is from `http://dev.biocol.org/urn:lsid:biocol.org:col:35158`
* `/grscicoll/resolve/urn:lsid:biocol.org:col:34994
  which is from an LSID resolution of `urn:lsid:biocol.org:col:34994` (yes, we can actually support this).

The `dev.` prefix is to fit in with our usual dev-uat-prod setup; so the endpoint needs to cope with `dev.`, `uat.` or no prefix.  If you prefer (and if it's acceptable), the hostname doesn't need to be part of the URL.

Note that Roger has changed the biocol.org DNS to point to api.gbif.org, so for testing in Dev you'll need edit your hosts file or do something like:

```
curl -i -H 'Host: dev.grbio.org' http://api.gbif-dev.org/cool/035p-ba0x
```

The registry endpoint should respond with a 303 redirect to http://www.gbif{…}.org/…

**Comment by MattBlissett** [comment]
There are also URLs like

* `http://biocol.org/node/14838`
* `http://biocol.org/institution/swansea-museum`
* `http://biocol.org/institutional-collection/bryozoa`
* `http://biocol.org/collection/view/id/17107`

Which we may want to pick up.

**Comment by MattBlissett** [comment]
This simulates the final step in LSID resolution in dev:

```
curl -I -H 'Host: dev.biocol.org' 'http://api.gbif-dev.org/authority/metadata?lsid=urn:lsid:biocol.org:col:35158'
```

There's no way to test the whole process using e.g. http://lsid.info/urn:lsid:biocol.org:col:35158 — changing it to `dev.biocol.org` changes the identifier.

**Comment by asturcon** [comment]
> There are also URLs like
> 
> * `http://biocol.org/node/14838`
> * `http://biocol.org/institution/swansea-museum`
> * `http://biocol.org/institutional-collection/bryozoa`
> * `http://biocol.org/collection/view/id/17107`
> 
> Which we may want to pick up.

Should we also tackle this now?

For some of them there could be more than one entity. For example, there are 2 collections with name Bryozoa. We could just take the first one.

For the ones that use ids I'm not 100% sure that those ids in our DB refer to the same entity that they were referring in biocol. For those 2 examples I found the following:
- `http://biocol.org/node/14838`: there is this institution with 14838 as identifier https://registry.gbif.org/institution/845ef8e6-27bc-4313-bd74-029edf08ad19/identifier
- `http://biocol.org/collection/view/id/17107`: there is no collection with that id, but an institution https://registry.gbif.org/institution/7ecfa22e-e80d-4e2e-9b6a-c44d2cf75a4c/identifier

Is there a way to know where those URLs were pointing till now?

**Comment by asturcon** [comment]
Also, we have in the DB some UUIDs that were as LSID in GRBIO. The grscicoll/resolve method resolves them too in case we want to support that. For example: https://registry.gbif-dev.org/collection/8d0f46f7-9df8-495f-b53b-9b5bf767004a/identifier  that can be resolved with http://api.gbif-dev.org/v1/grscicoll/resolve/98d9b8ed-08d6-47fc-b324-2853e44d75d1

**Comment by MattBlissett** [comment]
> Should we also tackle this now?

I think we should ask @rogerhyam what he thinks about these URLs:

>   http://biocol.org/node/14838
>   http://biocol.org/institution/swansea-museum
>   http://biocol.org/institutional-collection/bryozoa
>   http://biocol.org/collection/view/id/17107

Were they promoted as persistent identifiers, or something else? I can't remember if the biocol.org website did anything else.

If it's not straightforward to resolve them, then it could wait until later.

**Comment by rogerhyam** [comment]
The only URIs that were intended to be persistent back when this was my baby looked like this

http://biocol.org/urn:lsid:biocol.org:col:15670

And I see that these are working in the registry! Well done. Thanks.

(Me: Quietly chuckling about how 10 years ago we couldn't use PURLs because they were unstable and we must use purpose designed identifiers like LSIDs - not that we'd have that conversation today!).

It would be even cooler if the URI were semantic web friendly and returned an RDF representation of the data if requested. That would be easy to render in other ways. e.g. If

curl -L -H "Accept: application/rdf+xml" http://biocol.org/urn:lsid:biocol.org:col:15670

gave and RDF XML document rather the redirecting to the web version. Or JSON-LD for that matter.

As for the ones you can probably just redirect them to the registry. The /node/14838 looks like a Drupal path to me.

**Comment by MattBlissett** [comment]
A note in passing: records like https://www.gbif.org/occurrence/1697652967 are using "identifiers" like http://grbio.org/institution/moscow-state-university

**Comment by asturcon** [comment]
Since I have to migrate the data that is missing from grscicoll I can also migrate all those URLs as identifiers so we can resolve them. 

This also makes me think that those URLs would be the most appropiate ids for the GBIF URLs as discussed in https://github.com/gbif/registry/issues/116

**Comment by asturcon** [comment]
Old identifiers for institutions and collections are now migrated and resolve to the corresponding entity in the GBIF portal.

I'm closing this issue since it looks to me that we've done everything. If not please reopen.
