### ISSUE TITLE
Replace GrSciColl UUID with INT

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#116]
Introducing UUID primary keys for the entities in the GrSciColl database has caused some concern that a new identifier is being created unnecessarily.

We should remove the UUID PKs for Institution, Collection and Staff Member (if possible) and replace with the original integer ID from GrSciColl which maps directly to the IDs, such as http://biocol.org/urn:lsid:biocol:org:34946 without the need for further redirecting logic.

**Comment by asturcon** [comment]
The ids in the cool URIs or LSIDs don't match with the original integer IDs from GrSciColl. E.g.:
![Screen Shot 2019-06-28 at 11 45 16](https://user-images.githubusercontent.com/25691745/60333843-5ca76b80-999a-11e9-8ffb-6ea07d5931cb.png)

Also, the cool URIS don't usually use integers, they are strings (http://grbio.org/cool/6j3y-rabv)

The original integers IDs from GrSciColl look like like the DB Drupal IDs and I think they were never used as public identifiers.

On the other hand, taking a look at the original data migrated from GrSciColl, they used to store a `URL` field that seems to be like a public identifer:
![Screen Shot 2019-06-28 at 11 49 09](https://user-images.githubusercontent.com/25691745/60334053-e3f4df00-999a-11e9-94a7-8e65b2e0670c.png)

Notice that for the collections that have the same name they append a dash and a number to differentiate them (see http://grbio.org/institutional-collection/aves).

Also, I can see in our logs in PROD that there are still requests to that URLs. 

Could we believe that these were the public identifiers used in the past and maybe we can use the same not to create a new UUID identifier?

**Comment by timrobertson100** [comment]
Thank you for exploring this. I suggest we ask the Smithsonian folk involved, but it sounds reasonable.

**Comment by MikeTrizna** [comment]
I'm not great with Drupal, but I believe that these URLs were assigned to each "entity" (institution, staff member, etc.), and would redirect from the Drupal Node ID URL (e.g. grbio.org/node/7361). I think there was some sort of SEO advantage to this?

**Comment by timrobertson100** [comment]
I'm going to close this, as it is not for certain using an integer identifier is better. As things progress, I anticipate a more appropriate identifier will be promoted prominently - e.g. a DOI so citations can be properly tracked. While that decision is pending it seems wrong to make changes.
