### ISSUE TITLE
feedback on GrBio editing

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#125]
Based on the feedback that we have received from one of our GRBio editor:
- Could we have a way to link duplicate entries together?
The idea would be then to link outdated entries to the most recent ones - the issue is that there can be many entries with the same name (for example `Chicago Academy of Sciences`) which may be confusing so it would be a good idea for the outdated ones to at least point to the right one.
- Could there be any way to link datasets (from GBIF) to collections in GRBio?

**Comment by asturcon** [comment]
@MortenHofft for the first point, would it be enough for you to show it in the UI if I change the API to allow filtering by name and code (or even more fields if we need) in the list method?

**Comment by marcos-lg** [comment]
Closing since this is outdated.
