### ISSUE TITLE
dataset search limit disregarded without warning

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#13]
http://api.gbif.org/v1/dataset/search/?offset=0&limit=10000 returns 1000 results. 
it would be nice with an error instead.
Not critical of course, but it would be useful.

**Comment by MattBlissett** [comment]
It's documented and it would be inappropriate to change this behaviour https://www.gbif.org/developer/summary

> limit | Controls the number of results in the page. Using too high a value will be overwritten                                 with the default                                 maximum threshold, depending on the service. Sensible defaults are used so this may be                                 omitted
