### ISSUE TITLE
Add country to search on GrSciColl collections

### ISSUE THREAD

**Issue by rukayaj** [gbif/registry#131]
On https://registry.gbif.org/collection/search it would be really nice if the search worked on the country field in the mailing addresses and physical addresses, at the moment it just seems to work on the address string. 

So for example if I search for Norway (trying to see all the collections in Norway), I don't get https://registry.gbif.org/collection/5f096916-26ab-4927-ae0b-b6f0f6db55ed even though it is based in Oslo, because Norway is not mentioned in the address string or in the description.

**Comment by asturcon** [comment]
It is related to this other issue: https://github.com/gbif/registry/issues/95 

In this particular case, I've also noticed that the country `NO` is not present in the full text column in the DB, perhaps Postgres filters it as a stop word

**Comment by marcos-lg** [comment]
This has been done some time ago.
