### ISSUE TITLE
modifying collections also sets creation date.

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#133]
@asturcon 
I just modified an entry, which changed both the modification and creation date

http://api.gbif-dev.org/v1/grscicoll/collection/9afa5f2c-1a86-4f40-b8de-029227d51a63
```
"createdBy": "mlopezg",
"modifiedBy": "mhoefft",
"created": "2019-07-08T14:11:02.431+0000",
"modified": "2019-07-08T14:11:02.431+0000",
```

**Comment by asturcon** [comment]
fixed in PROD. I restored the creation date of the entities that were modified before this fix
