### ISSUE TITLE
Add new installation type of EarthCape

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#138]
Just as the title says.

Please let @ManonGros know when it is live so installations can be updated.

**Comment by asturcon** [comment]
Deployed in Production

**Comment by emeyke** [comment]
Great!
Still needs enum label update.
Currently appears as Installation type installationType.EARTHCAPE_INSTALLATION

Cheers,
Ev

**Comment by asturcon** [comment]
We've actually deployed the new label too. I can see it in the registry-console. Maybe some content is cached. If after some time you are unable to see the right label please let us know.

**Comment by emeyke** [comment]
ok! was looking at uat actually...
