### ISSUE TITLE
User with Node permission gets error when setting endorsement=True

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#140]
The organisation was this one: https://registry.gbif.org/organization/84f05dcd-9971-41db-be8a-c18d3b2883f8
It works with the API but not with the console (see screenshot).
![image_2019_08_21T07_34_24_562Z](https://user-images.githubusercontent.com/7677271/63412680-827c4a00-c3f8-11e9-8419-467f10a1cc9d.png)

**Comment by ManonGros** [comment]
That's really odd, EC was able to add contact to an organisation via the API. Is it because it is a POST statement?
![Screenshot 2019-08-21 at 10 48 00](https://user-images.githubusercontent.com/7677271/63417306-4994a300-c401-11e9-800e-b6c42d708580.png)

**Comment by MortenHofft** [comment]
My user with node permissions can change text, but not set endorsement to true
