### ISSUE TITLE
Edit installation for Node editors

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#141]
Would it be possible to allow editors with Node permissions to edit installation information?

**Comment by MortenHofft** [comment]
I just tested if it was a UI oversight. The API does not allow for it (returns 401 Unauthorized)

**Comment by MattBlissett** [comment]
As far as I see, this already works.

**Comment by MortenHofft** [comment]
I just retested on dev. Still fails for user `mortenh` for me. I also tested outside the UI by PUT on the API with the users credentials

**Comment by MattBlissett** [comment]
Mistake was mortenh not having REGISTRY_EDITOR role.
