### ISSUE TITLE
Users with organisation scope cannot edit their installations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#142]
When a user has editing right for an organisation it would make sense they could also edit that organisations installations.

Similar to https://github.com/gbif/registry/issues/141

**Comment by MattBlissett** [comment]
Are you sure this doesn't work?

I have granted REGISTRY_EDITOR to the user `matt_blissett` (my test user), on the organization `Test Organization #1`, and then edited `Test installation2`.

https://registry.gbif-uat.org/installation/1c930e21-72ce-4d71-a384-87a3fcd507da

**Comment by MortenHofft** [comment]
I've just tested with user [mortenh on dev](https://registry.gbif-dev.org/user/mortenh)
changing this installation description
https://registry.gbif-dev.org/installation/faeb021c-ab9f-4c80-9587-3749a8f6fb23
it failed.
the user has organisation and node rights

**Comment by MattBlissett** [comment]
Mistake was mortenh not having REGISTRY_EDITOR role.

**Comment by ManonGros** [comment]
I don't know if it is just in the console but I cannot edit the installation if my user has node permissions but no organisation permission. Can anyone confirm?
