### ISSUE TITLE
Add type to installation list API

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#143]
Please add `type` as a parameter in [this api](https://github.com/gbif/registry/blob/master/registry-ws/src/main/java/org/gbif/registry/ws/resources/InstallationResource.java#L134) so the following will work:

http://api.gbif.org/v1/installation?type=EARTHCAPE_INSTALLATION

**Comment by MattBlissett** [comment]
Done in 02173bf68e97a94eea93aeb21bc8daf07362ccdd.

**Comment by ManonGros** [comment]
I am not sure if I am doing something wrong but it doesn't seem to work on UAT:
http://api.gbif-uat.org/v1/installation?type=EARTHCAPE_INSTALLATION
Does it mean it hasn't been deployed yet?

**Comment by emeyke** [comment]
This works now.
