### ISSUE TITLE
avoid ambiguous characters in DOIs

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry#145]
We've seen several cases of incorrect DOIs being cited because of people getting letters and numbers mixed up, e.g. 0 vs O, 1 vs l, etc.

If we decide to expand/change the recipe for DOIs, perhaps we could avoid some of these characters altogether? E.g 0, O, o, i, I, l, and 1.

(there may be more than I haven't considered)

**Comment by MattBlissett** [comment]
I've removed `0o 1il` from the set of possible characters.  I could exclude `2z 4a 5s 7 8b 9g` etc but that seems like going a bit far, especially as we use lower case.

**Comment by dnoesgaard** [comment]
I think this is sufficient. Thanks.
