### ISSUE TITLE
Publish all datasets as CSV/TSV file

### ISSUE THREAD

**Issue by mdoering** [gbif/registry#147]
To support the common use case of retrieving all registered datasets in GBIF it would be useful to publish a simple TSV or CSV file with the most common, flat properties. It could be updated daily. BHL is doing this

See https://github.com/gbif/gbif-api/pull/45#issuecomment-533510404

**Comment by jhpoelen** [comment]
+1 also see https://github.com/bio-guoda/preston/issues/21 for context.

**Comment by MattBlissett** [comment]
This was implemented as `https://api.gbif.org/v1/dataset/search/export`, it accepts the usual search parameters.

**Comment by jhpoelen** [comment]
Very cool! Thanks for implementing this method to get a full list of all GBIF indexed datasets and associated info.

```
$ curl "https://api.gbif.org/v1/dataset/search/export" > datasets.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.3M    0 30.3M    0     0   751k      0 --:--:--  0:00:41 --:--:--  646k
$ wc -l datasets.tsv
81316 datasets.tsv
```

with first 10 rows being:

| dataset_key | title | doi | license | type | sub_type | hosting_organization_key | hosting_organization_title | hosting_country | publishing_organization_key | publishing_organization_title | publishing_country | endorsing_node_key | network_keys | project_identifier | occurrence_records_count | name_usages_count |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 4fa7b334-ce0d-4e88-aaae-2e0c138d049e | EOD – eBird Observation Dataset | 10.15468/aomfnb | CC_BY_4_0 | OCCURRENCE |  | e2e717bf-551a-4917-bdc9-4fa0f342c530 | Cornell Lab of Ornithology | US | e2e717bf-551a-4917-bdc9-4fa0f342c530 | Cornell Lab of Ornithology | US | 8618c64a-93e0-4300-b546-7249e5148ed2 |  |  | 1060970490 | 0 |
| d7dddbf4-2cf0-4f39-9b2a-bb099caae36c | GBIF Backbone Taxonomy | 10.15468/39omei | CC_BY_4_0 | CHECKLIST |  | fbca90e3-8aed-48b1-84e3-369afbd000ce | GBIF Secretariat |  | fbca90e3-8aed-48b1-84e3-369afbd000ce | GBIF Secretariat |  | 02c40d2a-1cba-4633-90b7-e36e5e97aba8 |  |  | 0 | 7651850 |
| 7ddf754f-d193-4cc9-b351-99906754a03b | Catalogue of Life Checklist | 10.15468/rffz4x | UNSPECIFIED | CHECKLIST | TAXONOMIC_AUTHORITY | f4ce3c03-7b38-445e-86e6-5f6b04b649d4 | The Catalogue of Life Partnership |  | f4ce3c03-7b38-445e-86e6-5f6b04b649d4 | The Catalogue of Life Partnership |  | 03e816b3-8f58-49ae-bc12-4e18b358d6d9 |  |  | 0 | 4850622 |
| fab88965-e69d-4491-a04d-e3198b626e52 | NCBI Taxonomy | 10.15468/rhydar | UNSPECIFIED | CHECKLIST |  | fbca90e3-8aed-48b1-84e3-369afbd000ce | GBIF Secretariat |  | 2f2e4f28-d929-4609-937b-9a8ebd265159 | National Center for Biotechnology Information (NCBI) | US | 8618c64a-93e0-4300-b546-7249e5148ed2 |  |  | 0 | 3136018 |
| 6b6b2923-0a10-4708-b170-5b7c611aceef | The European Nucleotide Archive (ENA) taxonomy | 10.15468/avkgwm | CC_BY_4_0 | CHECKLIST | TAXONOMIC_AUTHORITY | ada9d123-ddb4-467d-8891-806ea8d94230 | European Nucleotide Archive (EMBL-EBI) | GB | ada9d123-ddb4-467d-8891-806ea8d94230 | European Nucleotide Archive (EMBL-EBI) | GB | d897a5b9-35ee-4232-94bd-b0bcaac003c2 |  |  | 0 | 2329239 |
| 38b4c89f-584c-41bb-bd8f-cd1def33e92f | Artportalen (Swedish Species Observation System) | 10.15468/kllkyl | CC0_1_0 | OCCURRENCE |  | 4c415e40-1e21-11de-9e40-a0d6ecebb8bf | GBIF-Sweden | SE | b8323864-602a-4a7d-9127-bb903054e97d | SLU Artdatabanken | SE | a0b3be64-6525-4387-ac67-a499950f92e1 |  |  | 95866665 | 0 |
| 046bbc50-cae2-47ff-aa43-729fbf53f7c5 | International Plant Names Index | 10.15468/uhllmw | UNSPECIFIED | CHECKLIST | NOMENCLATOR_AUTHORITY | 72da316f-62b4-451e-9238-cf72289e6372 | The International Plant Names Index Collaborators |  | 72da316f-62b4-451e-9238-cf72289e6372 | The International Plant Names Index Collaborators |  | 02c40d2a-1cba-4633-90b7-e36e5e97aba8 |  |  | 0 | 1352714 |
| d9a4eedb-e985-4456-ad46-3df8472e00e8 | The Plant List with literature | 10.15468/btkum2 | UNSPECIFIED | CHECKLIST |  | 92f51af1-e917-49bc-a8ed-014ed3a77bec | Institute of Biodiversity, Animal Health and Comparative Medicine, College of Medical, Veterinary and Life Sciences, University of Glasgow | GB | 92f51af1-e917-49bc-a8ed-014ed3a77bec | Institute of Biodiversity, Animal Health and Comparative Medicine, College of Medical, Veterinary and Life Sciences, University of Glasgow | GB | d897a5b9-35ee-4232-94bd-b0bcaac003c2 |  |  | 0 | 1322960 |
| bae5856f-da10-4333-90a0-5a2135361b30 | The Leipzig catalogue of vascular plants | 10.15468/9qxmn3 | CC_BY_4_0 | CHECKLIST | TAXONOMIC_AUTHORITY | f4ce3c03-7b38-445e-86e6-5f6b04b649d4 | The Catalogue of Life Partnership |  | b48dbd22-0452-4c31-a6b5-28f04e99d8cf | German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig | DE | 4f6826f2-4ff6-443d-b966-e6913bd24013 |  |  | 0 | 1311409 |
