### ISSUE TITLE
pipeline history shows oldest first?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#149]
pipeline history shows oldest first. Is there a way to sort them?
are they searchable? I see that there are pagination.

https://api.gbif-dev.org/v1/pipelines/history

```
{
"offset": 0,
"limit": 20,
"endOfRecords": false,
"count": 2301,
"results": [
{
"key": 243,
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"attempt": 170,
"created": "2019-09-12T13:41:01.275006",
"createdBy": "crawler.gbif.org",
...
},
{
"key": 244,
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"attempt": 171,
"created": "2019-09-12T14:04:48.454759",
"createdBy": "crawler.gbif.org",
...
},
...
}
```

**Comment by MortenHofft** [comment]
same goes for the dataset history
https://api.gbif-dev.org/v1/pipelines/history/b89a7f02-021d-4e7a-b19f-575d10578a6d

it is ordered latest first

**Comment by asturcon** [comment]
I'm gonna sort them by created date in descending order.

They're searchable by datasetKey and attempt

**Comment by asturcon** [comment]
fixed and deployed in all envs
