### ISSUE TITLE
pipeline run step x doesn't work

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#151]
POST https://registry-api.gbif-dev.org/pipelines/history/run/0ac84fc0-ee6a-46f2-936f-e17e59aec29c?steps=VERBATIM_TO_INTERPRETED&reason=sdf

I get error 400 message `{"responseStatus":"PIPELINE_IN_SUBMITTED","steps":["VERBATIM_TO_INTERPRETED"]}` Doesn't matter which dataset.

**Comment by asturcon** [comment]
I just tried and worked. When the error says `PIPELINE_IN_SUBMITTED` it means that there is a step running for that process and we don't allow reruns in those cases.
