### ISSUE TITLE
pipeline errors is sometimes json other times text

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#152]
would be nice if it was consistent.

https://registry-api.gbif-dev.org/pipelines/history/run/0ac84fc0-ee6a-46f2-936f-e17e59aec29c?steps= is text for example see https://github.com/gbif/registry/issues/151 for json example

**Comment by asturcon** [comment]
I changed it to return a JSON response when the steps are not present but this is the way the registry handles certain kinds of exceptions. So this will happen in other cases.

We should change this in the new registry @mike-podolskiy90 . Now this provider returns plain text as media type when there is an `IllegalArgumentException` https://github.com/gbif/gbif-common-ws/blob/master/src/main/java/org/gbif/ws/server/provider/IllegalArgumentExceptionMapper.java
