### ISSUE TITLE
Not all the preservation types appear in the drop down menu

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#162]
I am making an update for a user and he would like me to set the preservation type to be `STORAGE_FROZEN_MINUS_80` based on the list I sent him: http://api.gbif.org/v1/enumeration/basic/PreservationType

However, I can't find this type in the drop down menu of the edit page.

**Comment by MortenHofft** [comment]
@ManonGros said
> I am making an update for a user and he would like me to set the preservation type to be STORAGE_FROZEN_MINUS_80 based on the list I sent him: http://api.gbif.org/v1/enumeration/basic/PreservationType
However, I can't find this type in the drop down menu of the edit page.

the website is using http://api.gbif.org/v1/enumeration/basic/PreservationMethodType for that dropdown.

@asturcon if the API expects something else let me know and I will update the UI

**Comment by asturcon** [comment]
That enum the dropdown is using is wrong. It should use http://api.gbif.org/v1/enumeration/basic/PreservationType

**Comment by ManonGros** [comment]
@asturcon in that case, do you know why I couldn't update the record with the API?
Any help would be appreciated, thanks!

**Comment by MortenHofft** [comment]
@ManonGros the registry-console now use the other endpoint for dropdowns. I'll leave the issue open for the other issue

**Comment by asturcon** [comment]
> @asturcon in that case, do you know why I couldn't update the record with the API?
> Any help would be appreciated, thanks!

Looks like you are sending a list of preservation types? a collection can only have one.

**Comment by ManonGros** [comment]
Yes I was, but I thought I could because in the API it looks like that: `"preservationTypes":[]`
Are the brackets just for empty values?

**Comment by asturcon** [comment]
Yeah, I deleted the comment because I realised it's a list. Let me check more carefully

**Comment by asturcon** [comment]
what response do you get? or what status code at least

**Comment by ManonGros** [comment]
I get `Response [204]`

**Comment by ManonGros** [comment]
Ok so great news! The API actually works, I was just using UAT but checking prod. So the preservation types were updated: http://api.gbif-uat.org/v1/grscicoll/collection/2a95140b-f5d7-440c-862b-092958e7d1b2

The problem is that I can't see them in the UI: https://registry.gbif-uat.org/collection/2a95140b-f5d7-440c-862b-092958e7d1b2

**Comment by MortenHofft** [comment]
So it is a list? Not as far as the interface is concerned. I'll look at that

**Comment by ManonGros** [comment]
> So it is a list?

Yes it is

**Comment by MortenHofft** [comment]
Changed in https://github.com/gbif/registry-console/commit/4466ad46ae3f8c56a4ca0e594fbc56cc51532c5e

**Comment by MortenHofft** [comment]
closing as the frontend is now using the correct enumeration and is showing a list. And the backend issue was a misunderstanding
