### ISSUE TITLE
GrSciColl - add identifier field to staff

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#175]
Currently there is no option to add person identifiers to staff. We have that option for contacts (in datasets, publishers etc). We should introduce an equivalent in GrSciColl. Perhaps we should restrict types unlike in the EML? Say ORCiD and Wikidata only to begin with?

There is also the option to use the already existing `identifiers` instead of adding a new field? And then simply add a person or ORCiD type? I like that version, but might make editing more challenging for externals as it would require multiple forms.

**Comment by rukayaj** [comment]
I've actually added some orcids for staff members using the existing `identifiers` already. But is it possible to get them to show up on the front end? E.g. currently this guy https://www.gbif.org/grscicoll/person/43c83325-5b9b-43bb-9025-59bfb11e21cb has an ORCID that I added through the registry, but it's not showing on that page.

**Comment by marcos-lg** [comment]
This has been already fixed when we migrated the staff to the contacts entities: https://github.com/gbif/registry/issues/379
