### ISSUE TITLE
Files missing after the spring-boot merge

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#178]
e.g. `registry-examples/src/test/resources/registry-inserts.sql` and the rest of registry-examples.

(I have not checked for others.)

**Comment by mike-podolskiy90** [comment]
Do we need registry-example's RegistryWsJerseyIT?

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/registry/commit/afa98652b10c0426e82f9bea39b6de7edf31538e
https://github.com/gbif/registry/commit/268f3cde17983da17594bfe523f5d6c0dbefecd2
