### ISSUE TITLE
Add scopes for GrSciColl users

### ISSUE THREAD

**Issue by asturcon** [gbif/registry#179]

**Comment by ManonGros** [comment]
We would have the two following roles:

GRSCICOLL_ADMIN:

- Can edit everything
- Get a warning when editing IH entry in the UI

GRSCICOLL_EDITOR:

- Cannot edit IH_IRN identifier
- Get a warning when editing IH entry in the UI
- Cannot edit machineTag
- Can create and edit all staff
- For everything else, editor's right will depend on a scope:
    * If given institution permission:
        * can edit existing institution
        * can create and edit related collections
        * can add staff to institution and related collections
    * If given collection permission:
        * can edit existing collection
        * can add staff to collection

**Comment by asturcon** [comment]
When implementing this I assumed:
- Editing also includes deleting
- Editors are not allowed to create institutions
- Editors can only create collections if they are linked to an institution where they have rights and they still have rights in the current collection or institution. If the institution key is null they can't create it.
- Editors can change the institution key of a collection if they have rights in the institution set.

**Comment by asturcon** [comment]
Deployed in PROD

**Comment by MortenHofft** [comment]
@marcos-lg Would it make sense to say that registry admins can edit anything? I mean, a registry admin can just edit their own roles anyway.

**Comment by marcos-lg** [comment]
@MortenHofft no, registry admins can't edit anything in GRSciColl - GRSciColl uses only GRSciColl roles. I separated the roles some time ago to make GRSciColl more independent and have more control over permissions.

**Comment by MortenHofft** [comment]
To avoid issues like this there is now this issue https://github.com/gbif/registry/issues/293
