### ISSUE TITLE
SpringBoot Registry Ws Clients

### ISSUE THREAD

**Issue by fmendezh** [gbif/registry#184]
The [registry-ws-client](https://github.com/gbif/registry/tree/oldMaster/registry-ws-client) has not been migrated yet to use more up-to-date libraries that play nicely with the latest versions of Spring. 
Initially, this task aims to provide functional compatibility with the existing module, but it should take into consideration future extensions to provide mechanisms such as resilience (i.e. circuit breaker), caching and asynchronous processing.

The implementation of this client library must take into consideration the implementation of reliable integration tests that can possibly be used in the current [registry-integration-tests](https://github.com/gbif/registry/tree/master/registry-integration-tests) module
 
At least two libraries and frameworks have been evaluated to be used as a replacement to Jersey, being [Spring Feing](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html) the preferable option so far. In other GBIF projects, Retrofit and OKHttp have been used extensively, however, it lacks support to reuse service definition through composition or inheritance (see this [issue](https://github.com/square/retrofit/issues/504)), additionally, the use of Generics is also cumbersome.

**Comment by mike-podolskiy90** [comment]
Branch ws-client merged
