### ISSUE TITLE
Create endpoints to show duplicated entities in GrSciColl

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry#191]
The goal is to create something like https://registry.gbif-dev.org/dataset/search?type=duplicate but for collections. This will show collections and institutions that have the same code. We could even show fuzzy matches of the names. For persons we can check name + email duplicates.

**Comment by marcos-lg** [comment]
This will be implemented as `/grscicoll/institution/{key}/duplicates` (the same for collections)

**Comment by marcos-lg** [comment]
Deployed in UAT:

http://api.gbif-uat.org/v1/grscicoll/institution/4ba42ccd-e6ac-4ea3-9b54-1eaf4755eb2e/possibleDuplicates

http://api.gbif-uat.org/v1/grscicoll/collection/34175252-43cd-45ce-9a4d-384496b7a14f/possibleDuplicates

**Comment by marcos-lg** [comment]
After some discussions, the folowing changes were made:
- Removed the /possibleDuplicates endpoint
- Improved the search endpoint to match the names fuzzily and added a limit param (it's internally limited to a max of 50. The offset is not allowed, this endpoint was intended to use in things like the autocomplete, for paging we have the list endpoints): http://api.gbif-uat.org/v1/grscicoll/search?q=Jiiin%20agriculture%20university&highlight=true&limit=10
- Added a city and fuzzyName to the list endpoints (both institution and collections): 
http://api.gbif-uat.org/v1/grscicoll/institution?fuzzyName=Jiiin%20agriculture%20university
http://api.gbif-uat.org/v1/grscicoll/institution?city=copenhagen

**Comment by ManonGros** [comment]
Just an idea - low priority:
it would be nice to be able to filter for duplicates where one of the entries is iDigBio

**Comment by marcos-lg** [comment]
The endpoint is deployed in PROD.

Examples:
http://api.gbif.org/v1/grscicoll/institution/possibleDuplicates?sameCity=true&sameFuzzyName=true&inCountries=FI,DE

http://api.gbif.org/v1/grscicoll/collection/possibleDuplicates?sameCity=true&sameName=true&inCountries=FI

The parameters are:

- sameName: boolean
- sameFuzzyName: boolean
- sameCode: boolean
- sameCountry: boolean
- sameCity: boolean
- inCountries: in every group of duplicates there will be at least one entity of one of these countries
- notInCountries: all the groups of duplicates that contain an entity from any of these countries will be discarded
- excludeKeys: discards these entities from the results

Only for the collections endpoint:
- sameInstitution: boolean
- inInstitutions: in every group of duplicates there will be at least one entity of one of these institutions 
- notInInstitutions: all the groups of duplicates that contain an entity from any of these institutions will be discarded

Note that for the boolean parameters is not the same to send it as false and not to send it. If you don't send it that condition is not checked, if you send it as false we check that the condition is false. For example:
- sameName=true&sameCity=false -> results must have the same name and the city has to be different
- sameName=true -> results must have the same name and the city can be the same or it can be different

For the list parameters, you have to separate the values with commas.

We'd also create a process to check these results and create github issues. The process can be run in Jenkins via the run-collections-duplicates job and the issues are created in https://github.com/gbif/collections-duplicates/issues.
