### ISSUE TITLE
Add work_mem to DB connection initialisation

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#192]
In the migration onto spring we dropped this setting from DB config, which existed as a configurable parameter. I expect it was added for good reason:

```
registry.db.connectionInitSql=SET work_mem='64MB'
```

To save searching, here is the definition (note that all our paging use ordering extensively):

> work_mem (integer)
> Specifies the amount of memory to be used by internal sort operations and hash tables before writing to temporary disk files. 
> The value defaults to four megabytes (4MB). Note that for a complex query, several sort or hash operations might be running in parallel; each operation will be allowed to use as much memory as this value specifies before it starts to write data into temporary files. 
> Also, several running sessions could be doing such operations concurrently. Therefore, the total memory used could be many times the value of work_mem; it is necessary to keep this fact in mind when choosing the value. Sort operations are used for ORDER BY, DISTINCT, and merge joins. Hash tables are used in hash joins, hash-based aggregation, and hash-based processing of IN subqueries.

**Comment by MattBlissett** [comment]
We have `work_mem = 128MB` in postgresql.conf, so it's not necessary to configure it in the webservice.
