### ISSUE TITLE
Registry emails coming from root@prodws-vh.gbif.org

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#193]
Registry emails to the helpdesk (endorsement and so on) are being sent from root@prodws-vh.gbif.org, which is probably the default From address for messages sent by that server.

It's no problem to use localhost to send mail, but the From address should be set as in the configuration, i.e. helpdesk@gbif.org.

This may well affect other email sources in the registry.

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/registry/commit/7deb5f5942209f636c6f697bb7955549e039ff9a

**Comment by mike-podolskiy90** [comment]
Updated configuration on dev https://github.com/gbif/gbif-configuration/commit/c1329ae1d8856e4a63cf0cc48202c7c593ba9e20
Property mail.from has to be added to uat & prod

**Comment by mike-podolskiy90** [comment]
deployed on prod, v. 3.16
