### ISSUE TITLE
Errors in the logs for dataset searches

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#194]
There are thousands of errors in the registry logs, possibly many of them are for this query: http://api.gbif.org/v1/dataset/search?q=Catalogue+of+Texas+spiders&hl=False&limit=9200&offset=9100

1) Investigate why that causes an error
2) Why are there >40,000 results for "Catalogue of Texas spiders"?

**Comment by muttcg** [comment]
1. It is cause of some aggregations, I extended max_result_window to 20_000

**Comment by fmendezh** [comment]
A default of `index.max_result_window: 100000` is used when creating the index
https://github.com/gbif/gbif-configuration/blob/master/cli/prod/config/registry-batch-indexer.yaml#L38
