### ISSUE TITLE
Registry search limited to 50,000 results

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#195]
http://api.gbif.org/v1/dataset/search?limit=1000&offset=50000

I don't know if this matters, since it's the free text search and there's always the plain search: http://api.gbif.org/v1/dataset?limit=1000&offset=50000 but if the limitation remains, it should be documented in the public API documentation, and a reasonable error returned.

**Comment by fmendezh** [comment]
https://github.com/gbif/registry/commit/345480bff26d0f93d23a6210291dd3999b6427ca
