### ISSUE TITLE
Allow a user to delete their own account, or an administrator to delete a user account

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#196]
At the moment, requests to delete a user account are handled manually (I have a script).  They are usually sent to helpdesk, comms or admin, and this causes confusion on who (me) handles them.

We have had 12 such requests since March 2018.

This functionality will need to:
- Generate a new, placeholder/invalid username and email. I've been using `deleted by user request 2020-06-09` (which is invalid due to the spaces) and `deleted_2020-06-09@deleted.invalid` (which is guaranteed by the DNS system to be an invalid email address).  Although, maybe we should use a random string instead of the date.
- Search through occurrence downloads for downloads created by the user
  - Remove any notification addresses
  - Update `created_by` with the new username
- Update the `username` and `email` of the `user` table, set the password to something invalid (I use `DELETED_DELETED_DELETED_DELETED_`), blank out the `first_name`, `last_name`, `roles`, `settings`, `system_settings` and set `deleted = NOW()`.
- Maybe send a final email to the user, saying their account is deleted etc, and listing the downloads whose DOIs will continue to resolve.

Supersedes #92, if we have a way to recover a deleted user it's not really deleted, is it? :-)

Also supersedes #41.

**Comment by mike-podolskiy90** [comment]
Should we remove all notification addresses from occurrences created by the user? Or just this user's email?

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/registry/commit/2b8277833df3c596882a6ee3a0c56f7781ae5b09
https://github.com/gbif/registry/commit/938c497d1bb621c4c20b2a6b7073762f905fd1d3

**Comment by mike-podolskiy90** [comment]
Is email fine? I've been thinking that we also have to send a new username to the user in order to be able to recover the account

**Comment by MortenHofft** [comment]
> Supersedes #92, if we have a way to recover a deleted user it's not really deleted, is it? :-)

Indeed not. Reading that again it seems like an odd suggestion.

**Comment by mike-podolskiy90** [comment]
tested on dev & uat

**Comment by mike-podolskiy90** [comment]
release v. 3.19
