### ISSUE TITLE
Publisher search (portal and registry UI) showing inconsistent behavior

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry#198]
Observation:
A search for institution: "Instituto de Investigação Científica Tropical"
failed both at https://registry.gbif.org/organization/search and at https://www.gbif.org/publisher/search (on Google Chrome / MAC) - no hits could be found.

This could be reproduced on my own browser/machine (Firefox 77.0.1 / Microsoft Windows 10). Substring search (working around the accented characters) likewise failed. However, attempting the same search a short while later now did give results (both setups), including the Portuguese characters and substring searches. On Firefox, reopening the browser (deleting history and cookies) did not change this. 

This behavior, too, was the same both for the registry console and for the UI at gbif.org.

A few days earlier (June 5), we had received a possibly related issue report from a data publisher via email, saying (original in German) that "Also, since a few days ago, the search for datasets or collections by substrings, top left, no longer works; I had quite liked that. Now it has to be spelled exactly as shown in the list, right from the start of the field."

**Comment by fmendezh** [comment]
This has been fixed in referenced commits
