### ISSUE TITLE
dataset/suggest queries no longer work as expected

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#200]
Reported on https://discourse.gbif.org/t/api-dataset-suggest-elasticsearch-errors/2206

**Comment by fmendezh** [comment]
Multiple commits fixed this issue:

https://github.com/gbif/registry/commit/960c8e36c1bb8ce7f0dd2e9ff7cd4e4fee0780a7
https://github.com/gbif/registry/commit/912b9326ff135842c3a8b5fa5dfd51c2aaa094ac
