### ISSUE TITLE
any 1 letter dataset suggests fail

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#206]
e.g. https://api.gbif.org/v1/dataset/suggest?limit=8&q=k

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 18 19:47:27 UTC 2020
There was an unexpected error (type=Internal Server Error, status=500).
Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
```

**Comment by fmendezh** [comment]
The span first query threw exceptions for some query terms, by now a minimum of 3 characters will be used for that type of query.
Later when we migrate to ES 7 we can improve this by indexing prefixes: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-prefixes.html

https://github.com/gbif/registry/commit/960c8e36c1bb8ce7f0dd2e9ff7cd4e4fee0780a7
