### ISSUE TITLE
"endorsed" status for organizations: allow 3 states

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry#209]
Endorsement of a newly registered publisher is granted (or refused) by the responsible GBIF participant node manager. On approval, the endorsement flag is set to Yes; by default, it is starting off as No. Having just two states available, however, does not allow to document cases where endorsement is explicitly refused/withheld/on hold. 

Proposed change: 

make the flag non-mandatory
store the NULL value in the database
start a new record with endorsed = NULL
explicitly set the other states for
true: accepted
false: refused (or on temporary hold)

loosely relates to: #60

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif is there a way to distinguish 'on hold' organization from 'withheld' one ? 
I also wouldn't recommend use boolean value (endorsement_approved flag) to store more than two states. I'd prefer to create endorsement_status field and store there an explicit status of the endorsement.

**Comment by ahahn-gbif** [comment]
@mike-podolskiy90, you are probably right about avoiding 3-state boolean - I am fine with other solutions as well, possibly a second field alongside the flag to qualify the endorsement_status? 

The main concern is that we currently cannot document a state of "still pending node manager response", "denied", and "on hold" (explicitly, e.g. when the node manager is still in communication with the prospective publisher before making a decision, and informed us of the procedure). The present "withheld" text in titles is a poor workaround that we would really like to get rid of again.

The endorsement flag is presently used to decide visibility / hiding of the publisher entry from search results, overview pages and links, and we probably should not touch that. The endorsement_status is largely an internal management tool supporting communications - are reminders required, or is the case settled, at least for the time being. Comments can help to a degree to understand an individual case, but checking up on required actions for unendorsed publishers is tedious that way.

If this is turning out to be a new field, I would strongly wish for adding the endorsement date (data stamp for when the flag was set from No to Yes: https://github.com/gbif/registry/issues/60) at the same time. Presently we have to run yearly updates for the Nodes Steering Group on endorsement metric / lag times by piling through a year's endorsement email traffic, since we know from the registry when a publisher was registered, but not when they did get endorsed.

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif I'm not going to remove or change the 'endorsement_approved' flag. 
I'm also already testing #60 on dev (it may requires some UI changes).

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif I think we can distinguish 'denied' ones from the others, they don't have the 'challenge_code_key' field which is set to null when someone denies or approves the organization

**Comment by mike-podolskiy90** [comment]
So I propose the following states: 'ENDORSED', 'REJECTED' and 'WAITING_FOR_ENDORSEMENT'

**Comment by ahahn-gbif** [comment]
> distinguish 'denied' ones from the others, they don't have the 'challenge_code_key' field
I don't think that is true. I would prefer not having to evaluate cryptic internal fields. But also, I am not sure whether this one will also be flipped when one of us manually sets the endorsed flag in the registry rather than by email confirmation (which can happen). Denying endorsement is not an actively registry-connected action, nothing gets set on that decision (no "deny" button to click), it is exclusively documented in emails.

In that sense, I am fine with ENDORSED (with boolean true), REJECTED (and boolean false), WAITING_FOR_ENDORSEMENT (and boolean false), but would still like a 4th state for 'ON_HOLD' (with boolean false): there is a difference between follow-up actions needed on a newly registered publisher where we are waiting for the node's first reaction (i.e. the node does not react), having to follow up and escalate if nothing arrives in reasonable time, and a situation where the node told us that they are exploring and we should wait some more time (i.e., we got a response from the node). Any concerns with having four states instead of three?

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif 4 states is of course better than three.
 The 'challenge_code_key' is not actually cryptic. It's always erased when someone endorses the organization (by link or through the form in the registry).

**Comment by ahahn-gbif** [comment]
Great, thanks!
challenge_code_key: same information as the flag itself set to 'true' then, right?

**Comment by mike-podolskiy90** [comment]
The only concern with 4 states is that we can't set that validly for all the current organisations.

**Comment by ahahn-gbif** [comment]
for a start:
- anything endorsed = true is clear
- anything else could start with WAITING(...) (endorsed = false), as long as we can manually update that afterwards. We have relatively few cases of true rejection, and can sort through "on hold" ones manually

**Comment by mike-podolskiy90** [comment]
Added in v3.23
