### ISSUE TITLE
New service: DOI for a secondary filtering of a download

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#212]
When a user of a monthly snapshot applies significant filtering of the downloaded data the current citation practice is poor. A simple example being someone filtering for plants-only which currently gives credit to all zoological and fungal datasets even though their records were discarded. As GBIF moves forward with [public datasets on the cloud](https://discourse.gbif.org/t/gbif-exports-as-public-datasets-in-cloud-environments/1835) this will become more common.

We need a service to help provide more meaningful citations and clear guidelines for people to follow.

As an initial design for consideration:
- A service accepting a list of dataset keys (optionally with counts), the original DOI and the necessary metadata (e.g. a download URL if applicable) that returns a new DOI and citation string. 
- The service can ensure the necessary links are captured to attribute the original datasets (similar to current download DOIs) - The service adds a reference to the original snapshot DOI declaring this is a derivation.

This will allow us to give clear recommendations for researchers, and enable tools and scripts (e.g. rGBIF) to be developed to help people follow the guidelines.

**Comment by dnoesgaard** [comment]
To make this service really useful—even for smaller scale studies, I would love to see the ability to accept occurrence keys as well. If not to fully recreate a download—but—to allow users to skip the step of looking up datasetKeys and counting unique records.

**Comment by timrobertson100** [comment]
> To make this service really useful—even for smaller scale studies, I would love to see the ability to accept occurrence keys as well. If not to fully recreate a download—but—to allow users to skip the step of looking up datasetKeys and counting unique records.

We can explore this, but need to be aware that the occurrences may have been removed so (currently) may miss some links. 

My hope was people could design their workflows such that they could do the likes of (shown here in SQL syntax) `SELECT datasetkey, count(*) FROM cleaned_data GROUP BY datasetKey` which I think would be reasonable to ask wherever possible, and robust

**Comment by jhnwllr** [comment]
I think this could also be useful for custom downloads.  Currently, the guidelines are only for authors upload to Zenodo with datasetkeys as meta-data (something to that effect). I think a service would be much more straightforward for users to use and for us to track. I could imagine always packaging custom downloads with a unique datasetkey file that they could plug into this service.

**Comment by mike-podolskiy90** [comment]
Document https://gbifs.sharepoint.com/:w:/g/Development/EaZGBunw3slIjNduAt1kS-gBieNmEM2lgbE7ny9LQcu4jg?rtime=9uk8GqVJ2Eg

**Comment by timrobertson100** [comment]
This will be refined (by @dnoesgaard) during testing but initially please start with a citation string along the lines of:

**Citation** GBIF.org (2 Sept 2020) Filtered export of GBIF occurrence data https://doi.org/10.15468/dd.12345

When we get to the webpage for what this resolves to, we will have additional text along the lines of:

> This dataset was derived by filtering content from an export of GBIF-mediated occurrence data. The original export is available on https://doi.org/10.15468/d1.abcdef.
>
> After filtering, the result includes records from N datasets
> ... similar to any download page

**Comment by dnoesgaard** [comment]
(just a note to remember that the Mendeley crawler needs to be able to unpack these new dd DOIs)

**Comment by dnoesgaard** [comment]
I know that this might not be completely on-topic, but since we're already working with downloads and creating new DOIs, would it be possible to consider this functionality: https://github.com/gbif/gbif-doi/issues/6
