### ISSUE TITLE
Add user language

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/registry#213]
Allow users to choose a language in the profile and store it in the DB. UI and email notification should use this language. Default language is English.

**Comment by kcopas** [comment]
Email notification *where available*—or we need to (select and) add some translations. 

Is this a single choice, or can users store >1 with preference indicated? Thinking of non-UN language users who might want to indicate their interest in their mother tongue, e.g. Pole who would prefer Russian over English where available?

Be useful if we can use this information (in anonymized form) to inform future language additions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mike-podolskiy90** [comment]
@kcopas for all user notifications (so called 'identity' emails: welcome, reset password, password changed, delete account, new user). For organization emails (confirm organization, organization confirmed, organization password reminder) I have some concerns because we send emails not only to the organization, but also to helpdesk as CC.
I'd recommend by now use only one language. It can be any (not only UN ones) in the format BCP-47.

**Comment by kcopas** [comment]
Thanks, @mike-podolskiy90 !

May I ask: how will we manage the translated versions of these messages, then?

**Comment by mike-podolskiy90** [comment]
@kcopas emails will have a separated template on each supported language. Templates are part of the registry source code, we change them very rarely.

**Comment by kcopas** [comment]
Understood—it seemed to me that CrowdIn would be overdetermined for this task and registry or some such was more likely. 

But part of why I ask is to say: do you want us to coordinate those translations with our volunteers? I know the 2nd floor would probably have RU and ES under control (even if I'm less confident in EN 😉), but it seems we'd ideally want translations into the languages the site currently supports.

**Comment by fmendezh** [comment]
@kcopas maybe one way to handle these translations is by having in them in Crowdin only to coordinate the work with volunteers and we simply copy the translation provide into files we use in the Java backends.
I don't anticipate this would be something that will change too often

**Comment by kcopas** [comment]
Thanks, Fede! Yes, thought about that as a possibility, too. Let me know if you'd like to pursue it, whenever you're ready, and we can get a CrowdIn project set up.

**Comment by ahahn-gbif** [comment]
Concerning organization emails: I would like to second Mikhail on keeping those in English. (a) new publishers are encouraged to register in English anyway, (b) helpdesk gets copied and sometimes needs to respond (most often reverting to English), (c) for endorsement confirmations, helpdesk is the _only_ recipient, then informing the new publisher by manual mail (in English), and (d) endorsement mails sometimes have to be rewired/-sent to a different node, or forwarded to the committee for community endorsement. Agree to keep organization / endorsement emails in English.

**Comment by mike-podolskiy90** [comment]
tested on dev, will be added in the registry v3.24

**Comment by MattBlissett** [comment]
For the very small number of emails, I think it's best that we either
# copy the emails into the portal project, so the existing Crowdin project translates them. This is easier than inviting translators to another project, or
# just ask for them to be translated by email. They're emails with a few ${name} fields, nothing too scary.

My preference is for the first option..
