### ISSUE TITLE
Custom citation exception code has not been migrated to the new registry

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#218]
These commits: 

57d93ca61be571f064eaf95fd7808439b5fba2f7
5d905c69db31ffc2ad51ce811c4be6a4ca39028b (just the test)
1975ee1b58d4d67a59afca8b80e92ba5ab02cdd7 (just the test)
c7dfea61580191158c3ac46a66954c81b2b24f77

In addition to the OBIS network, the IUCN dataset with key 19491596-35ae-4a91-9a98-85cf505f1bd3 should also use the publisher's citation.

**Comment by mike-podolskiy90** [comment]
@MattBlissett should we add this UUID to the gbif-api's Constants?

**Comment by mike-podolskiy90** [comment]
Seems everything is there now, please let me know if something wrong or missing
