### ISSUE TITLE
add a doi search param to dataset/search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#219]
See also https://github.com/gbif/portal-feedback/issues/2849

**Comment by fmendezh** [comment]
Closing this issue, search by DOI was implemented several months ago
see: 
[http://api.gbif.org/v1/dataset/search?doi=10.3897/zookeys.730.21846](http://api.gbif.org/v1/dataset/search?doi=10.3897/zookeys.730.21846) --> returns 2 datasets
[http://api.gbif.org/v1/dataset/search?doi=10.11646/zootaxa.4846.1.1](http://api.gbif.org/v1/dataset/search?doi=10.11646/zootaxa.4846.1.1) --> returns 1 datase3t
