### ISSUE TITLE
testDismaxSearch fails sometimes

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#22]
From time to time this test fails:

```[INFO] Running org.gbif.registry.DatasetIT
[INFO] Tests run: 98, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 74.181 sec <<< FAILURE! - in org.gbif.registry.DatasetIT
[INFO] testDismaxSearch[0](org.gbif.registry.DatasetIT)  Time elapsed: 0.34 sec  <<< FAILURE!
[INFO] java.lang.AssertionError: SOLR docs not as expected expected:<6> but was:<4>```
```

I presume it is due to this, which should be fixed correctly and not hacked:
```
    //Give some time to Solr to update
    Thread.sleep(100);
```

I am disabling tests that use this approach and will reference to this issue.  Once fixed the test can be reenabled.  This should be fixed with mock implementations or similar.

**Comment by fmendezh** [comment]
it seems this issue has been fixed while porting dataset search to Elasticserch
