### ISSUE TITLE
relatedDatasets counts

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry#225]
Re. https://github.com/gbif/registry/issues/212

When adding a new derivedDataset, I think would it make sense to allow blank/null values for relatedDatasets record counts, if possible, e.g

  "relatedDatasets": {
    "10.21373/1llmgl",
    "9579eaa0-f762-11e1-a439-00145eb45e9a",
    "10.21373/abcdef": 200
}

This would be a common use case. Otherwise, I see this being populated with 1s in these cases, which would be inaccurate. If would be better to allow null and interpret it as "unknown" in the UI...

**Comment by mike-podolskiy90** [comment]
@dnoesgaard I'm afraid an example above is not a valid json.
We can do that like:
`
{
	"relatedDatasets": {
		"10.21373/1llmgl": null,
		"9579eaa0-f762-11e1-a439-00145eb45e9a": null,
		"10.21373/abcdef": 200
	}
}
`
Is it suitable?

**Comment by mike-podolskiy90** [comment]
If we attach a file we can do the following:
```
10.21373/1llmgl
9579eaa0-f762-11e1-a439-00145eb45e9a
10.21373/abcdef,200
```

**Comment by dnoesgaard** [comment]
That's fine. Null is better than having to use a fake value. Thanks!
