### ISSUE TITLE
idigbio friendly format

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#229]
As far as I can see, it wouldn't require much work for iDigBio to start using the GBIF registry to display collections.

It looks to be as simple as changing the URLs at
https://github.com/iDigBio/idb-portal/blame/master/app/controllers/publishers.js#L17
and
https://github.com/iDigBio/idb-portal/blame/master/app/controllers/publishers.js#L30

to point to a gbif endpoint and then do a small transform to each entry. The iDigBio developers could easily do this, but it requires many API calls at the moment as we split institutions and collections.
As a friendly gesture we could create a custom endpoint for them that summarised all the data they need (it should also support GET by key). Then it really look to be as simple as changing those URLs.

Here is an example of the iDigBio collection format:
```
{
  "institution": "University of South Carolina Upstate",
  "collection": "Herbarium",
  "recordsets": "aac5fd7f-8043-4aa8-811f-e50de70d96f3",
  "recordsetQuery": "{\"recordset\":\"aac5fd7f-8043-4aa8-811f-e50de70d96f3\"}",
  "institution_code": "USCS<IH>",
  "collection_code": "",
  "collection_uuid": "urn:uuid:ffe8b443-6ff9-4540-a296-52d5b514b489",
  "collection_lsid": "urn:lsid:biocol.org:col:14610",
  "collection_url": "https://www.uscupstate.edu/academics/arts_sciences/natural_science/Herbarium/Default.aspx?id=2192",
  "collection_catalog_url": "http://upitsis1.uscupstate.edu/biology/",
  "description": "",
  "descriptionForSpecialists": "",
  "cataloguedSpecimens": null,
  "knownToContainTypes": null,
  "taxonCoverage": "",
  "geographic_range": "",
  "collectionExtent": "",
  "contact": "Benjamin Montgomery",
  "contact_role": "Director",
  "contact_email": "BMONTGOMERY@uscupstate.edu",
  "mailing_address": "Horace C. Smith Building, Room 316",
  "mailing_city": "Spartanburg",
  "mailing_state": "South Carolina",
  "mailing_zip": "29303",
  "physical_address": "Horace C. Smith Building, Room 316",
  "physical_city": "Spartanburg",
  "physical_state": "South Carolina",
  "physical_zip": "29303",
  "UniqueNameUUID": "urn:uuid:ae480445-b995-4d80-82b5-092f51c4a62e",
  "attributionLogoURL": "",
  "providerManagedID": "",
  "derivedFrom": "",
  "sameAs": "http://sweetgum.nybg.org/science/ih/herbarium_details.php?irn=126818",
  "flags": "",
  "portalDisplay": "",
  "lat": 35.0015,
  "lon": -81.9742
}"
```

The fields not in collections already is
```
lat, 
long, 
UniqueNameUUID, 
attributionLogoURL, 
institution name, 
institution code
```

The question is then if they use the collection data elsewhere in other projects/repos. For the portal, this seem to do the trick. And with a little effort. Of course we should have a developer at iDigBio to verify this.

**Comment by marcos-lg** [comment]
This format is available at http://api.gbif.org/v1/external/idigbio/collections
