### ISSUE TITLE
Delete SQL downloads

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#231]
GBIF nearly had a SQL download format. Downloads were made in production for testing but it never went fully _live_.
We've since removed the download format of SQL and it is breaking an endpoint (see below).

I suggest we simply identify and delete the trial SQL downloads.

This was reported by a user as follows:

> We're analysing data use of the botanical dataset of Naturalis with more than 209000 downloads. I use rgbif for this purpose. I run the analysis in a loop where numberStart is string form 0 - 209k with an interval of 1000 because that's the limit of  occ_download_dataset_activity. y is an empty tibble to collect the results
> 
> pb <- txtProgressBar(min = 0, max = max(numberStart), style = 3)
> 
> for(j in numberStart){
>   resBotany <- occ_download_dataset_activity("15f819bd-6612-4447-854b-14d12ee1022d", start=j, limit=1000)
>   x <- tibble::as_tibble(resBotany$results)
>   x <- x[, c("downloadKey", "datasetKey", "datasetTitle", "datasetDOI", "numberRecords",  "download.key", "download.doi", "download.license", "download.created", "download.downloadLink", "download.size")]
>   y <- rbind(y, x)
>   setTxtProgressBar(pb, j)
> }
> 
> close(pb)
> 
> But at j=66000 my loop crashes and I get the following error. I am using the latest version of R and updated all libraries, but that didn't solve the problem. Any suggestions?
> 
> Error: {"timestamp":"2020-10-09T15:11:28.667+0000","status":500,"error":"Internal Server Error","message":"nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'format' from result set.  Cause: java.lang.IllegalArgumentException: No enum constant org.gbif.api.model.occurrence.DownloadFormat.SQL","path":"/occurrence/download/dataset/15f819bd-6612-4447-854b-14d12ee1022d"}

**Comment by MattBlissett** [comment]
These five downloads have been changed to SIMPLE_CSV format, and had the SQL filters converted to predicates.

```
 0012867-181108115102211 │ SELECT DISTINCT COUNTRYCODE                                                                    ↵│
                         │ FROM occurrence_hdfs                                                                           ↵│
                         │ WHERE TAXONKEY = 6                                                                              │
 0012457-181108115102211 │ SELECT gbifid, datasetkey, year                                                                ↵│
                         │ FROM occurrence_hdfs                                                                           ↵│
                         │ WHERE countrycode = 'IN'                                                                        │
 0006372-190813142620410 │ SELECT DECIMALLATITUDE / 10 LAT, DECIMALLONGITUDE / 10 LON, COUNT(OCCURRENCEID) SPECIESRICHNESS↵│
                         │ FROM occurrence_hdfs                                                                           ↵│
                         │ WHERE TAXONKEY = 6                                                                             ↵│
                         │ GROUP BY DECIMALLATITUDE / 10, DECIMALLONGITUDE / 10                                            │
 0006212-190813142620410 │ SELECT FLOOR(DECIMALLATITUDE) LAT, FLOOR(DECIMALLONGITUDE) LON, COUNT(OCCURRENCEID) RECORDCOUNT↵│
                         │ FROM occurrence_hdfs                                                                           ↵│
                         │ WHERE TAXONKEY = 7707728                                                                       ↵│
                         │ GROUP BY FLOOR(DECIMALLATITUDE), FLOOR(DECIMALLONGITUDE)                                        │
 0006363-190813142620410 │ SELECT DECIMALLATITUDE / 10 LAT, DECIMALLONGITUDE / 10 LON, COUNT(SPECIES) SPECIESRICHNESS     ↵│
                         │ FROM occurrence_hdfs                                                                           ↵│
                         │ WHERE TAXONKEY = 6                                                                             ↵│
                         │ GROUP BY DECIMALLATITUDE / 10, DECIMALLONGITUDE / 10                                            │
```
