### ISSUE TITLE
editing iDigBio machine tags

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#232]
iDigBio would like to use the registry as their data source. But they annotate their collections with custom machine tags under the `iDigBio.org` namespace. For example: `recordSet` and `recordSetQuery`.

Only admins have access to edit machineTags in the current access model. Should we add the concept of `namespaces` to users? This could be used to allow editors to edit that namespace (on entities that are in their scope).

**Comment by ManonGros** [comment]
Thanks @MortenHofft. YesI think this issue can be closed as it is a subset of the other issue currently open.
