### ISSUE TITLE
Derived dataset DataCite metadata

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/registry#236]
Check missing metadata fields

**Comment by mike-podolskiy90** [comment]
@dnoesgaard Could you please check DataCite metadata for derived datasets if we miss something there

**Comment by dnoesgaard** [comment]
Yes, we should definitely include `relatedIdentifiers` for each of the relatedDatasets—just like we do for downloads. I'm not exactly sure which `relationType` to use, but since we use `References` for downloads, maybe it makes sense to use that here as well? At least for now...

**Comment by mike-podolskiy90** [comment]
@dnoesgaard should we also include `originalDownloadDOI` somehow?

**Comment by dnoesgaard** [comment]
Hmm, we could do `IsDerivedFrom`?
