### ISSUE TITLE
Non publishing organisation count is wrong

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#237]
The homepage of GBIF shows 1653 publishing organisations, which I believe is defined as an organisation that have a dataset published in GBIF.

The following SQL suggests the number should be 1583
```
SELECT count(distinct o.key) AS orgCount
FROM organization o JOIN dataset d on o.key=d.publishing_organization_key
WHERE o.deleted IS NULL AND d.deleted IS NULL and o.endorsement_approved=true;

 orgcount 
----------
     1583
```

Removing the `AND d.deleted IS NULL and o.endorsement_approved=true` returns 1653.

The homepage count is calculated by taking the [organisation count](http://api.gbif.org/v1/organization?limit=0) and subtracting [non-publishing organisations](http://api.gbif.org/v1/organization/nonPublishing?limit=0).

However I think the nonPublishing is incorrect in it's SQL [here](https://github.com/gbif/registry/blob/master/registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/OrganizationMapper.xml#L511) and [here](https://github.com/gbif/registry/blob/master/registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/OrganizationMapper.xml#L521) for this purpose (it was originally an endpoint used in the registry admin console to list organisations that may require followup). It appears to count only organisations which aren't deleted and do not have a dataset. If we are to keep using this it should be a count that includes all organisations (deleted or not) that do not have a dataset today. There are organisations that once had datasets (they are now all deleted) which are not be accounted for.

I think the best option would be to simply have a new endpoint which provides a count of publishing organisations and uses the SQL at the top of this comment so it is very clearly defined.

**Comment by ahahn-gbif** [comment]
Thanks, that matches my numbers, too, and the logic seems correct to me

**Comment by mike-podolskiy90** [comment]
Don't we already have this?
http://api.gbif.org/v1/organization/count

**Comment by MattBlissett** [comment]
Yes, that number is correct, and the SQL behind it is as Tim wrote.

It's just something for the website to change then.

**Comment by mike-podolskiy90** [comment]
Thomas has committed that https://github.com/gbif/portal16/commit/7c53eea3bb5a23239a8de9fb7cbfeeb1e5641097
