### ISSUE TITLE
Dataset ES index questions/observations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#257]
I've starting looking at the dataset index, and little questions come up

* `maintenanceDescription` is sometimes null other times an empty string. Should we just ignore empty strings instead?
* `maintenanceUpdateFrequency` what is the difference between `UNKNOWN`and `null` - should `UKNOWN` replace `null`?
* `metadata` seem to contain a dump of everything as text. But there is also an `all` field. Should `metdata` perhaps be excluded from source similar to `taxonKey`? Why do we have it at all? Does it contain things not in the other fields?
* There is a `deleted` field that is always empty - we do not index deleted do we? I guess there is no harm in having it.
* Date format is different from the occurrence index. Should they be the same?
* in temporalCoverages date, start and end is indexed as longs. Shouldn't that be dates?

**Comment by fmendezh** [comment]
@mike-podolskiy90 be aware that this issue requires a schema change, the index must be rebuilt following a procedure similar to the one documented in #264
