### ISSUE TITLE
Implement a service to deal with Institutions that should be collections

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#259]
Some institutions on GrSciColl should in fact be collections. This seems to be a relatively widespread issue (although I don't have any specific number) and contributes to the issue with duplicate institutions (https://github.com/gbif/registry/issues/189)

Here are 25 examples that I checked manually: 
[Insitutions_that_should_be_collections_GrSciColl.tsv.zip](https://github.com/gbif/registry/files/5566157/Insitutions_that_should_be_collections_GrSciColl.tsv.zip)
* 20 of these institutions have more than one duplicate institution,
* 14 have no collection associated with them,
* 8 have one collection,
* 3 have two collections,
* Collections associated with these institutions don't always match the content of the institution. For example, the collection associated with the [USDA/ARS, Southeastern Fruit and Tree Nut Research Laboratory](https://registry.gbif.org/institution/75be32b8-eded-4128-b208-9af924f2e9da) is about Nematodes.
* I could only find obvious replacements for 5 of these institutions, the others would require:
    * either duplicate cleaning beforehand, for example we have [many entries for the Cornell University](https://registry.gbif.org/institution/search?q=Cornell%20University) so it would be difficult to pick one for the [Cornell University Insect Collection](https://registry.gbif.org/institution/ae1380be-d358-4a85-a5ff-8a527908a96e),
    * or the creating of a new institution, for example there is no entry for the "Virginia Institute of Marine Science" for the [Virginia Institute of Marine Science, Nunnally Ichthyology Collection](https://registry.gbif.org/institution/03148e66-1120-4078-9b64-e41138286696).

So one idea could be that it is just a special case of resolving duplicates.
It could be an option of the "replace by" mentioned here: https://github.com/gbif/registry/issues/255
What it would do in addition to everything mentioned in the issue is to create a collection and add it to the institution that will be remaining.
Please share your ideas.

**Comment by marcos-lg** [comment]
We'll implement a service in the API to convert an institution into a collection. 

This service will do:
1. Check that the institution doesn't have collections. If it does the service will return an error
2. Create a new collection with the data from the institution
3. Delete the institution and set the `replacedBy` flag with the new collection
4. The service can receive an institution as a parameter that will be the institution of the new collection. If it doesn't receive this parameter it will create a new institution with the same code as the collection. The name of the new institution must also be specified as a parameter

**Comment by marcos-lg** [comment]
The endpoint is available now in UAT at:

http://api.gbif-uat.org/v1/grscicoll/institution/{key}/convertToCollection

In the body it's required to pass either the institution key for the new collection or a name to create a new institution for this new collection. It has to be in JSON format:
```
{
    "institutionForNewCollectionKey": "dd155a13-33da-46be-9f6e-07809d2ab5ab",
    "nameForNewInstitution": "name"
}
```

Authentication is required and the user needs to be a GRSciColl admin or editor.

Curl request example:
```
curl -u username:password -X POST 'api.gbif-uat.org/v1/grscicoll/institution/b779903b-f02b-45f2-91ea-b3b28a0c408e/convertToCollection' \
--header 'Content-Type: application/json' \
--data-raw '{
    "institutionForNewCollectionKey": "dd155a13-33da-46be-9f6e-07809d2ab5ab"
}'
```

**Comment by marcos-lg** [comment]
To be changed:
- Don't move the identifiers, just duplicate them and filter the deleted ones in the lookup and in the identifier resolver

**Comment by marcos-lg** [comment]
I also disallow the merge of 2 iDigBio entities and restricted the endpoint to GRSCICOLL_ADMINS users only.
