### ISSUE TITLE
derivedDataset to include downloads

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry#260]
I would like to suggest that we allow derivedDatasets to include downloads in relatedDatasets as an easy means of combining several download DOIs into a single DOI (as per this old issue https://github.com/gbif/gbif-doi/issues/6)

Thoughts?

**Comment by mike-podolskiy90** [comment]
Maybe as a separate field? it doesn't look good to mix them together from the backend perspective.

**Comment by dnoesgaard** [comment]
If that makes more sense, I'm good with that. My goal is simply to allow users to bring a list of download DOIs and get a single, unifying DOI that they can cite. Actually, in this case, the sourceURL doesn't really make sense either. Ideas?

**Comment by MattBlissett** [comment]
A collection of downloads isn't a derived dataset.  When this is implemented, I think it ought to be a new type of DOI/citation (aggregated… or something).

**Comment by dnoesgaard** [comment]
I agree completely. Was just thinking "two birds, one stone"...

**Comment by mike-podolskiy90** [comment]
let's consider creating another DOI type then
