### ISSUE TITLE
Emails sent for a user with a traditional Chinese locale use the wrong URL

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#261]
Email are sent with /zh_TW, but the portal uses /zh-tw.  I've added a temporary redirect to Varnish to work around this.

Also, the obsolete locale column in the user table should be removed.

**Comment by mike-podolskiy90** [comment]
btw, shouldn't it be 'zh-TW'?

**Comment by MattBlissett** [comment]
https://www.gbif.org/zh-tw/ works, but https://www.gbif.org/zh-TW/ does not.

**Comment by mike-podolskiy90** [comment]
Yes, I know. I mean standard is https://en.wikipedia.org/wiki/Zh-TW

**Comment by mike-podolskiy90** [comment]
registry v3.40, deployed to prod
