### ISSUE TITLE
Posting EML with multiple paragraphs in abstract adds outer <p> tags

### ISSUE THREAD

**Issue by mdoering** [gbif/registry#27]
Posting the [attached EML](https://github.com/gbif/registry/files/1368587/eml.txt)
 to the registry via curl converts the 2 eml paragraphs into a single paragraph with 2 nested <p> tags. Also the ul, li list markup is removed entirely

`curl -H “Content-Type: application/xml” -H “Accept: application/json” -X POST -d @eml.xml https://api.gbif.org/v1/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c/document`

**Comment by mdoering** [comment]
[eml.xml](https://github.com/gbif/registry/files/1368587/eml.txt)

**Comment by cgendreau** [comment]
As far as I remember it was by purpose since there is only a single "description" field.

see https://github.com/gbif/registry/blob/master/registry-metadata/src/main/java/org/gbif/registry/metadata/parse/ParagraphContainer.java

**Comment by cgendreau** [comment]
Allowed HTLM tags are defined here:

**Comment by mdoering** [comment]
Converting the multiple EML <para> tags into <p> to fit into the single registry description makes sense. But should it not be converted back into <para> tags in EML when converting the Dataset?

Having a single <para> tag with multiple <p> underneath is at least not the way EML was designed.
Example for the backbone:

```
<abstract>
<para>
<p>The GBIF Backbone Taxonomy, often called the Nub taxonomy, is a single synthetic management classification with the goal of covering all names GBIF is dealing with. It&#39;s the taxonomic backbone that allows GBIF to integrate name based information from different resources, no matter if these are occurrence datasets, species pages, names from nomenclators or external sources like EOL, Genbank or IUCN. This backbone allows taxonomic search, browse and reporting operations across all those resources in a consistent way and to provide means to crosswalk names from one source to another. It is updated regulary through an automated process in which the Catalogue of Life acts as a starting point also providing the complete higher classification above families.</p>
<p>The following 54 sources from the have been used to assemble the GBIF backbone:</p>
</para>
</abstract>
```

**Comment by cgendreau** [comment]
Not sure it should be "converted" at all.
We should probably store it in an array and handle it correctly.

**Comment by mdoering** [comment]
that would indeed be much better

**Comment by mdoering** [comment]
`<br/>`, `<ul>` and `<li>` tags within the para section are all removed, even if the EML abstract only contains a single `<para>`

**Comment by cgendreau** [comment]
As far as I remember they are not "removed" but filtered (in the sense they are serialized in the db but filtered from the response).
See https://github.com/gbif/registry/issues/27#issuecomment-336658844

**Comment by mdoering** [comment]
allowCommonBlockElements() does inlcude ul, li or br though. So sth seems not right

**Comment by cgendreau** [comment]
ah yes, indeed.
Since the XML is parsed you have to wrap the content of `<para>`with a  `CDATA` block.
