### ISSUE TITLE
add deletedBy

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#276]
We have `modifiedBy` and `createdBy` but no `deletedBy`.
Are there any reason not to have this. It seems informative. Often it can be deduced from modifiedBy of course.

example
https://registry-api.gbif-uat.org/dataset/75f56615-2b79-48d3-a91a-d735191bbdf4

**Comment by marcos-lg** [comment]
We actually update the `modifiedBy` field when we doing the deletion, so when an entity is deleted the `modifiedBy` actually is a 'deletedBy'

**Comment by MortenHofft** [comment]
~~unless someone edits the deleted entry~~

ahh - you cannot edit a deleted entry. I'm closing the issue then
