### ISSUE TITLE
Dataset network membership curation: editor rights and scope

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry#281]
With more dataset networks coming in (and possibly more to be expected in the context of Hosted Portals in future), we would like to move from central, manual curation of network membership to being able to give editor rights to trusted network coordinators.

Network membership is curated in table `dataset_network` and links a network UUID with multiple dataset UUIDs, regardless of dataset publisher affiliation. Typically, a network brackets individual datasets across a range of publishers, and does not include all datasets of the publisher.

The desired functionality would ideally
1) grant a specific network coordinator permission to add more datasets to their own network / remove datasets from their own network
  (NB: it is not necessarily possible to predict which publishers or even nodes these additional datasets may be affiliated with)
2) include a form of safeguard that reminds the editor that adding datasets to their network needs to be in agreement with the dataset owner 
  (networks are products of the self-organization of a community, built on mutual agreement)

As a minimum solution, and given the relatively manageable number of networks, it would help if we could 1) grant the network editor rights on the `dataset_network` content relating to their own network UUID (add/delete), and handle 2) in form of communication. Is 1) possible though? This would concern both the registry UI and API use.

**Comment by ManonGros** [comment]
In summary, we would like to be able to have users as follow:
permission: registry_editor
scope: network UUID

That would allow them to `POST /network/{UUID}/constituents` and `DELETE /network/{UUID}/constituents`

**Comment by mike-podolskiy90** [comment]
Question from @MortenHofft :
Should an editor with network scope only be allowed to edit the constituent datasets. Aren't they allowed to add contacts, change title description etc?

**Comment by ahahn-gbif** [comment]
@MortenHofft Thanks - yes, it would make sense to allow them to also edit the network contacts and description. Less convinced about the title: it should not change often, and for consistency (data filters), I would prefer some communication with helpdesk before any change.

To keep in mind though that none of this is currently visible on the network pages in the GBIF.org context, as this is fed from authored content, not fed from the registry. It may be more relevant for hosted portal environments.

**Comment by mike-podolskiy90** [comment]
registry v3.48, deployed to prod
some more work on UI required, created an issue for that
