### ISSUE TITLE
Add new identifier types: ROR and GRID

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#283]
We will now be adding some ROR (https://ror.org) and GRID (https://www.grid.ac/institutes/) identifiers to organisations: https://github.com/gbif/registry/issues/282

@mike-podolskiy90

**Comment by mike-podolskiy90** [comment]
ROR identifiers start with "https://ror.org"
GRID identifiers start with "grid"
is it correct?

**Comment by ManonGros** [comment]
Yes
ROR identifier: https://ror.org/01tv5y993
GRID identifier: grid.425585.b
