### ISSUE TITLE
Collection codes for non-research institutions in GRSciColl

### ISSUE THREAD

**Issue by rukayaj** [gbif/registry#284]
We occasionally have used dwc:collectionCode for datasets from the private sector and for e.g. observation datasets which are not actually proper scientific collections. An example is https://www.gbif.org/occurrence/1563639254

This seems to be permitted in the dwc term definition, but of course it's not appropriate to add these collection codes and institute codes to GrSciColl. However, it's also not ideal for these records to be flagged in the GBIF portal as having an issue. 

Is there a convention we can follow to exclude those records/datasets from the matching algorithm, or is this perhaps not something to worry about too much?

**Comment by ManonGros** [comment]
Hi @rukayaj, there are two ways to avoid these flags:

- One is to remove the collections and institution codes all together for those records.
- The other is to have corresponding entries in GrSciColl.
We don't have any problem with "Observation" collections (they are still scientific collections) so you are very welcome to create entries for those.

But unless you would like those records to be linked to GrSciColl, you don't have to worry too much about these flags. We are still working on the communication around GrSciColl and the occurrence matching. Suggestions are welcome!

**Comment by katiagbif** [comment]
@ManonGros  Thank you very much for your contribution and suggestion! I am not very familiar with the management of private collections in GrSciColl, so I appreciate the opportunity to ask you about it. When creating a new private collection, is there any recommended practice for setting up the profile of the corresponding institution, or is it better not to assign it to any institution? I have seen various examples and would value any recommendations you can offer to consider for future private collections. Thank you very much!
