### ISSUE TITLE
Support completeListSize in the OAI-PMH resumptionToken

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#286]
A request via email from GBIF France:

"Why don't you provide the "completeListSize" in the <resumptionToken> tag?
Is it something you could implement in the future?

ex: https://api.gbif.org/v1/oai-pmh/registry?verb=ListRecords&metadataPrefix=oai_dc&set=country:FR

`<resumptionToken cursor="1">MToxMDB8Mjpjb3VudHJ5OkZSfDM6fDQ6fDU6b2FpX2Rj</resumptionToken>`

**Comment by mike-podolskiy90** [comment]
https://api.gbif-uat.org/v1/oai-pmh/registry?verb=ListRecords&metadataPrefix=oai_dc&set=country:FR

**Comment by mike-podolskiy90** [comment]
registry v3.49, deployed to prod

**Comment by sylmorin-gbif** [comment]
Wonderful ! Thank you for this very fast implementation and go to production!
I'm notifying the people waiting for this feature.

**Comment by jusana** [comment]
thanks all and thanks @sylmorin-gbif : it works perfectly for my projet needs !!
