### ISSUE TITLE
/network/{UUID}/organization 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#287]
Provide a new endpoint `/network/{UUID}/organization` that lists the distinct publishing organization of the datasets that are associated with a network.

**Comment by mike-podolskiy90** [comment]
Should the method be added to the gbif-api's NetworkService?

**Comment by timrobertson100** [comment]
> Should the method be added to the gbif-api's NetworkService?

Yes, I can't think of a reason to treat it differently from other endpoints in `/network`

**Comment by mike-podolskiy90** [comment]
registry v3.49, deployed to prod
