### ISSUE TITLE
derivedDataset API: datasetDOI vs datasetDoi

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#289]
for downloads we use `datasetDOI`
http://api.gbif.org/v1/occurrence/download/0163791-200613084148143/datasets

for derivedDatasets we use `datasetDoi`
https://api.gbif.org/v1/derivedDataset/10.15468/dd.jskxae/datasets

also citation is included in one, not the other. Should we align this? Or is it too late given that it is in production?

**Comment by MattBlissett** [comment]
No-one has written client to derivedDatasets yet, so there's still time to align it.

**Comment by MortenHofft** [comment]
Related: Should we add `totalRecords` and `numberDatasets` as well. It is in the download API and appears in this mock https://github.com/gbif/portal16/issues/1444 by @dnoesgaard

**Comment by mike-podolskiy90** [comment]
@MortenHofft what are those `totalRecords` and `numberDatasets` please?

**Comment by dnoesgaard** [comment]
`numberDatasets` should be the same as `count` reported on /derivedDataset/10.15468/dd.jskxae/datasets

totalRecords could be calculated at the time of creation as the sum of counts for all `relatedDatasets`

**Comment by mike-podolskiy90** [comment]
I don't think we should add those, but what's your vision about this, duplicate them for every record? Or have only once?
