### ISSUE TITLE
DataCite metadata creator populated wrong when minting Dataset DOIs

### ISSUE THREAD

**Issue by kbraak** [gbif/registry#3]
Currently when GBIF mints DOIs for Datasets, the DataCite metadata creator is populated from the person who created/registered the dataset with GBIF. 

The DataCite metadata creator should be populated from the person who created the dataset. 

In EML / GBIF Metadata Profile, each person who created the dataset is specified using the <creator> element. There must be at least one <creator> for the GBIF Metadata Profile document to be valid. 

Additional associated parties with role originator can also be included in the metadata, however, in my opinion only the creators should be used to populate the DataCite metadata creators. This is what the IPT does. Additional associated parties can be added to the DataCite metadata as Contributors with a type.

The way in which the IPT populates DataCite metadata from EML is described [here](https://github.com/gbif/ipt/wiki/IPT2DataCiteMappings.wiki).

---

Issue relates to https://github.com/gbif/gbif-doi/issues/1

**Comment by MattBlissett** [comment]
I think this was done a long time ago.
