### ISSUE TITLE
network suggest includes deleted entities

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#308]
https://registry-api.gbif-uat.org/network/suggest?q=d

```
[
{
"key": "6c0ee24a-22c5-4492-be6f-5dac58259d50",
"title": "DiSSCo Network"
},
{
"key": "0c8d3457-4995-40c0-9650-aceef8edcb80",
"title": "DiSSCo Network"
},
{
"key": "9400230d-de38-4e0e-b44d-fcdb661f0519",
"title": "DiSSCo Network"
},
{
"key": "2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6",
"title": "Ocean Biodiversity Information System (OBIS)"
}
]
```

This is not how dataset suggest works, but it is how `organization/suggest` works. It makes it tricky to use as a drop down. 
Should we add a parameter to indicate if they should be included? Or at least include the information in the response, so that the user has a chance to select the not deleted one.

**Comment by mike-podolskiy90** [comment]
I think we can add an optional query param, e.g. `includeDeleted` (default - false).

**Comment by fmendezh** [comment]
Deleted networks are not shown in search results anymore
