### ISSUE TITLE
Define plans to improve staff entities in GRSciColl

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#321]
A few of the issues we should address:
- defines who owns the information,
- explore the entries deduplications,
- how to handle the staff in the context of GDPR?
- should we add ORCiDs and similar?

Note that this isn't in our priorities for 2021.

**Comment by kcopas** [comment]
> Note that this isn't in our priorities for 2021.

And yet, it does at least start to cross into if not squarely onto [item 1.a.1](https://docs.gbif.org/2021-work-programme/en/#2021-work-items) in the work programme, for which I'm on the hook. When you're ready, I'd very much like to discuss this and loop @MortenHofft into the discussion, as we should maintain a consistency of approach to our how we manage other groups' personal information.

I can also offer a clear perspective of our current understanding of GDPR as it would apply to the catalogue.

**Comment by dagendresen** [comment]
I think the question "should we add ORCIDs" could rather be "should we require ORCIDs" -- and I think yes, for living people we should (next - do we plan to include dead people? and if so, they might not be able to get an ORCID, adding complexity - yet, ORCIDs for dead people was a hot and popular topic at Pidalooza2021).

I think that the main reason for including staff at all (potential added value by GrSciColl) would be to describe roles in the context of collection curation, collectors, etc. For this, we strictly need only the Agent PID (ORCID) and a controlled vocabulary of roles (and probably the time period the Agent was active in this role).
