### ISSUE TITLE
GRSciColl Search - include additional names

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#333]
In other words, this search: https://www.gbif.org/grscicoll/institution/search?q=Naturwissenschaftliche%20Sammlungen%20der%20Stadt%20Winterthur&offset=0
should return this entry:
https://registry.gbif.org/institution/3ab4b761-c62f-4996-a6d8-ed1283fc161e, that has "Naturwissenschaftliche Sammlungen der Stadt Winterthur" as additional name.

**Comment by marcos-lg** [comment]
Changed the DB trigger and deployed to PROD.
