### ISSUE TITLE
Can the GRSciColl lookup service use IH identifiers for exact matching?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#335]
based on this issue: https://github.com/gbif/portal-feedback/issues/3354
Some publishers have been using the IH identifier for collection match (as it is the only identifier available aside from the collection UUID) but their record was still flagged "Collection match fuzzy".
I think this is because the IH identifiers aren't used for the matching: https://api.gbif.org/v1/grscicoll/lookup?institutionId=http://grscicoll.org/institution/central-siberian-botanical-garden-siberian-branch-russian-academy-sciensis&collectionID=125943

Is this something we could/should change?

**Comment by marcos-lg** [comment]
The IH identifiers are stored with the prefix `gbif:ih:irn:` so if we use it in the lookup it returns an exact match:

https://api.gbif.org/v1/grscicoll/lookup?institutionId=http://grscicoll.org/institution/central-siberian-botanical-garden-siberian-branch-russian-academy-sciensis&collectionID=gbif:ih:irn:125943

What we can do is that when we receive these numeric identifiers, if there is no match I add the `gbif:ih:irn:` prefix as last resort to find a match.

**Comment by ManonGros** [comment]
@marcos-lg Does adding `gbif:ih:irn:` really work? It seems like https://api.gbif.org/v1/grscicoll/lookup?institutionId=http://grscicoll.org/institution/central-siberian-botanical-garden-siberian-branch-russian-academy-sciensis&collectionID=gbif:ih:irn:125943 doesn't return any collection match. Perhaps I am missing something?

**Comment by marcos-lg** [comment]
@ManonGros sorry the collectionId param case was wrong:

https://api.gbif.org/v1/grscicoll/lookup?institutionId=http://grscicoll.org/institution/central-siberian-botanical-garden-siberian-branch-russian-academy-sciensis&collectionId=gbif:ih:irn:125943

**Comment by ManonGros** [comment]
Wonderful! Thanks Marcos!

**Comment by marcos-lg** [comment]
Should we just encourage users that want to use IH irns to use the `gbif:ih:irn:` namespace? Otherwise, just assuming that any number could be a IH irn could lead to some unexpected results.

**Comment by ManonGros** [comment]
I think you are right, we should encourage them to use `gbif:ih:irn:` otherwise it will quickly become messy.
