### ISSUE TITLE
Identity API login returns subset of user

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#34]
Identity API only returns partial user object upon login. You then have to ask for the user again to get the remainder. Are there any reason for that? The website have to do a new get by username after login just to get the full user.

**Comment by cgendreau** [comment]
yes, there is a reason for that. A valid one? Maybe not, I will just try to explain the reason.

The `/login` endpoint is public so it [returns]((https://github.com/gbif/registry/blob/master/registry-ws/src/main/java/org/gbif/registry/ws/resources/UserResource.java#L74) a public version of the user (`LoggedUser`).

The get user is under `/admin` so it returns an administrative version(all fields) of the user. It can only be accessed by an admin or an app.

That been said, if all fields (except @JsonIgnore) in `GbifUser` can be exposed (e.g. systemSettings) to a user that would login via command line or any external code than `LoggedUser` could be removed and `GbifUser` could be returned. Note that there is no point to call `/login` from command line but it's possible :) .

The other solution would be to add `/authenticate` under `/admin` so authenticated app could get the admin version of the user automatically. It means that the portal would not use Basic Auth to check a user but a regular ws call to `/authenticate`.

Not sure if this is comprehensible but I hope it helps.

**Comment by MortenHofft** [comment]
ahh - makes sense. At this point there is nothing in system settings that couldn't be exposed, but makes sense to have that option. Roles however isn't a `systemSettings` and that seems like something that isn't an issue to expose. Anyhow - it isn't important. I'll close the issue. Thanks Gendreau
