### ISSUE TITLE
Consider caching of derived dataset responses

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/registry#340]
Users can now see their derived datasets here https://www.gbif-dev.org/derived-dataset and they can click the edit link to do updates.
They can register new derived datasets when clicking the "register" tab: https://www.gbif-dev.org/derived-dataset/register

Serving cached responses of the following endpoints will lead to unexpected behaviour in the UI:

````
GET /derivedDataset/{doi}
GET /derivedDataset/dataset/{datasetDoi}
GET /derivedDataset/user/{userName}
GET /derivedDataset/{doi}/datasets
````

This is because a user can navigate to a derived dataset directly after a `PUT` and would then expect to see the edits applied. Also users can navigate directly to their list of datasets and would expect to see a newly created dataset immediately.

**Comment by marcos-lg** [comment]
Deployed to PROD.
