### ISSUE TITLE
GRSciColl - use machineTags instead of identifiers for IH synch

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#342]

**Comment by marcos-lg** [comment]
This would also imply to move the IH machine tags when merging entities (now we only move the iDigBio machine tags)

**Comment by ManonGros** [comment]
Yes the machine Tags will have to be carried over during merging.

I guess this is a bit of a broader issue on this whole "Master data management solution": https://github.com/gbif/registry/issues/319
But I don't think we can't keep using identifiers for the synch. This will become difficult to use when we have other sources off synchronisation.
