### ISSUE TITLE
Store GRSciColl change suggestions + audit log

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry#343]
The GRSciColl API should be able to handle change suggestions. 

The suggestions should store the following information at least:
- Person who did the suggestion
- Date of the suggestion
- Proposed changes
- State (applied or not and when)
- Type (merge, deletion, creation, etc.)
- Reason or comment about the suggestion

When a suggestion is created it should be notified (by email?).

The API should enable an endpoint to apply a suggestion.

Additionally, the API should also log any write operation in the DB to keep track of the changes and it should store the pre and post state of the entity. If the write operation comes from a suggestion, they should be linked. To determine if it should log the full entity for secondary entities or just the entity modified (e.g.: identifier or machine tag).

The API should also have endpoints to list all the suggestions and the change log.

The UI changes are in https://github.com/gbif/registry-console/issues/376

**Comment by MortenHofft** [comment]
Should new suggestions be logged in GitHub as well? something along

* Labels per country
* summary of what changed
* link to the registry with the ID of the change request (so that the registry can prefill the form)

The reason should only be to make it easier for node managers to watch suggestions for their country.

**Comment by ManonGros** [comment]
I think the story would be the following:
1. A user makes a suggestion on collection X belonging to institution Z
2. The suggestion gets logged
3. I regularly look at pending suggestions (and perhaps there could always be a notification sent to scientific-collections@gbif.org?) and review them (but really anyone should be able to look at the pending suggestion)
4. In case if doubt, I forward a link to a reviewer: in priority institution editor, then country mediator

So in this scenario, we wouldn't use GitHub issues. I think GitHub is great for one-off cleaning events where there would be a lot to sort through (like for the duplicate). But in this case, I don't know if it would be best. I would want a fast turn over (not more than one or two pending suggestion at the time) and I think the registry UI would be enough for that.

For the suggestion endpoint, it would be good to be able to filter them by:

- pending status
- country of the entry to update
- (ideally to be able to see which ones you can edit before having to click on it. This is a bit of wishful thinking though. It would be fine without it.)

Later on we could consider adding email notifications to all potential editors of the modified entry:
1. the (collection/)institution Z editors
2. the country mediator
3. the administrator

But for now, I think this isn't necessary.
