### ISSUE TITLE
Registry changes that should trigger occurrence and/or dataset indices to be updated

### ISSUE THREAD

**Issue by fmendezh** [gbif/registry#348]
Adding or deleting constituents datasets of a network must trigger an event to refresh datasets-related stores: search indices, occurrence indexing, and databases.

**Comment by MortenHofft** [comment]
These are the cases I can think of:

* [ ] dataset changes publisher (I suspect that triggers an update already?)
* [ ] a dataset publisher changes country. Then occurrence publisherCountry should change
* [ ] a dataset installation changes publisher. Then the hostingOrgKey should be updated in occurrence and dataset index
* [ ] a network adds a dataset. Then the networkKeys should be updated in occurrence and dataset index

**Comment by ManonGros** [comment]
> Any change in GrSciColl institutions and collection (perhaps only identifiers, codes, alternative codes or names) could mean better matching for occurrences.

I guess in that case we would have to re-interpret everything right? Because we can't know which occurrences would be concerned.
Also, since we use a cache for GRSciColl (updated weekly), it would (almost) the same as just doing weekly reinterpretation of all the GBIF occurrences.

**Comment by fmendezh** [comment]
Vocabulary changes and GrSciColl changes will be tackle in a different task, the rest syncronization issues have been fixed.
