### ISSUE TITLE
Expose authors from citation in API

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#351]
The dataset pages currently have a highlighted list of people in the top. This list of people is generated in the portal UI project.

Example https://www.gbif.org/dataset/75956ee6-1a2b-4fa3-b3e8-ccda64ce6c2d
shows `Dutrève Bruno * Robert Solène * Thomas Milon * Anaïs Just`

And then we have the citation string in the bottom which reads

```
citation: {
  text: Bruno D, Solène R (2016). INPN - Données flore des CBN agrégées par la FCBN. Version 1.2. UMS PatriNat (OFB-CNRS-MNHN), Paris. Occurrence dataset https://doi.org/10.15468/omae84 accessed via GBIF.org on 2021-04-27.
}
```
This part comes from the API

**We want them to be the same**
The ones in the top is wrong and the citation string is correct. 
See discussion around this https://github.com/gbif/portal-feedback/issues/3398

Could we expose the list of authors in the order they should appear in the citation object? Something like: 

```
citation: {
  // the text is already there
  text: Bruno D, Solène R (2016). INPN - Données flore des CBN agrégées par la FCBN. Version 1.2. UMS PatriNat (OFB-CNRS-MNHN), Paris. Occurrence dataset https://doi.org/10.15468/omae84 accessed via GBIF.org on 2021-04-27.
  // this next part is the suggestion
  people: [
    "Bruno D", "Solène R" // possible as objects along with the contact Key from the API and their roles?
  ]
}
```

Or even better
```
citation: {
  text: Bruno D, Solène R (2016). INPN - Données flore des CBN agrégées par la FCBN. Version 1.2. UMS PatriNat (OFB-CNRS-MNHN), Paris. Occurrence dataset https://doi.org/10.15468/omae84 accessed via GBIF.org on 2021-04-27.
  people: [
    {
       abbreviatedName: "Bruno D",
       roles: ["ORIGINATOR", "METADATA_AUTHOR"],
       keys: [123], // in case we want to link to the contact
       firstName: "Dutrève", 
       lastName: "Bruno",
       userId: [] // could be  retrieved via keys if needed
    },
    ...
  ]
}
```

**Comment by dschigel** [comment]
Not a matter of preference, and need @ahahn-gbif here. Citation is built from the EML terms I think (same in IPT) and I guess we claim we follow the standard https://www.gbif.org/standards

**Comment by dschigel** [comment]
Looks like links from our [Metadata guide]([url](https://github.com/gbif/ipt/wiki/GMPHowToGuide)) don't link out to EML correctly, but Roles terms should be something to look for.

**Comment by timrobertson100** [comment]
For citations that we generate according to [our algorithm](https://github.com/gbif/registry/blob/master/docs/citations.md) ordering the JSON approach should be doable. We may need to consider the best approach when the citation is provided by the source, such as this [OBIS example](https://www.gbif.org/dataset/89d78af0-ad71-4136-9812-fb1d415ec933) where the people in the citation are not registered contacts, and abbreviations make name matching difficult.

**Comment by mdoering** [comment]
As these people become the authors in the citation I would call them authors. A bibliographic citation has authors, editors and a publisher. Contributors are normally the ones which are NOT cited. 

Splitting out these people is the first step into a parsed citation object. And I would suggest to design this together and base it on the same model at least close to [BibTeX](https://en.wikipedia.org/wiki/BibTeX#Field_types) or [CSL-JSON](https://github.com/citation-style-language/schema#csl-json-schema) as desired output formats: https://github.com/gbif/portal-feedback/issues/2027, https://github.com/gbif/portal-feedback/issues/33

The main weakness of BibTeX is [how authors are treated](https://nwalsh.com/tex/texhelp/bibtx-23.html). They are a single string in a very odd structured syntax to be parsable, e.g. names are concatenated with a literal _and_. There is [BibJSON](http://okfnlabs.org/bibjson/) to overcome this, but in the JSON world CSL-JSON has overtaken.

**Comment by fmendezh** [comment]
Dataset response has been changed to include a flag _citationProvidedBySource_ and _contactsCitation_

```
"citation": {
        "text": "Kim J (2021). 2020_biodiversity_information_specimen. National Science Museum of Korea. Occurrence dataset https://doi.org/10.15468/7gktfs accessed via GBIF.org on 2021-05-12.",
        "citationProvidedBySource": false
      },
      "contactsCitation": [
        {
          "key": 2416932,
          "abbreviatedName": "Kim J",
          "firstName": "JunHee",
          "lastName": "Kim",
          "roles": [
            "ORIGINATOR",
            "METADATA_AUTHOR"
          ],
          "userId": [
            
          ]
        }
```
