### ISSUE TITLE
Allow users to download lists of GRSciColl institution/collections based on search criteria

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#356]
This is something that we were asked at least on two separated occasions.
People who would like to report data or would like to build a network of people don't want to have to click through each entry to get all the information. And they are often not very comfortable with using the API.

For one of them, I have generated a spreadsheet containing the information they wanted for each institution using the API. But I can imagine that it would be helpful to have a service that allow them to download the information themselves.

**Comment by fmendezh** [comment]
@ManonGros any suggestion for the fields that should be in those exports, both collections and institutions have nested element that would make them not very friendly in flat format like TSV or CSV,  for other export services we have selected a subset of fields of API responses, sometimes we use arrays separate by ;.

I can suggest a list of fields and you can review them later on dev...sounds that ok?

**Comment by ManonGros** [comment]
Thanks for following up @fmendezh!
Yes I agree, the flat format isn't ideal for this export. For the people who asked me, I first made a simplified table like this: 

entity_registry_URL | country | name | code | active | synchronised_with_IndexHerbariorum | entity_homepage | description | entity_email | entity_phone |  entity_contacts | mailingAddress | address
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://registry.gbif.org/institution/fce6e835-0a36-4da9-9094-8a35f41ec4f2 | Algeria | Herbarium | GDB | TRUE | TRUE | http://gdebelair.com | gdebelair@yahoo.com | [213] 38445552 | Gérard de Bélair [213] 38445552 gdebelair@yahoo.com | G. de Bélair, B.P. 533 Annaba DZ | 12 rue Hassi Beïda Annaba DZ
https://registry.gbif.org/institution/1c71d18a-13af-4fd8-b8ce-9bc452be092e | Algeria | Ecole Nationale Supérieure Agronomique | ENSA | TRUE | TRUE | &nbsp; | &nbsp; | a.kedad@ensa.dz \| s.benhouhou@ensa.dz | [213] 23 82 85 07/12 | Sabine Abbassi [213] 23 82 85 07/12 abbassi_sabine@yahoo.fr \| Soumaya Baa [213] 23 82 85 07/12 baa.soumia@outlook.fr \| Salima Benhouhou s.benhouhou@ensa.dz \| Abdelaziz Keddad a.kedad@ensa.dz | Avenue Hassen Badi,El Harrach 16200 Algiers DZ | Avenue Hassen Badi,El Harrach 16200 Algiers DZ


But they wanted everything, all the fields available in GRSciColl. So I made 3 sheet instead: one for institution, one for collection and one for contacts. They contained almost all the possible fields from GRSciColl (for example, this is what the institution sheet had: `country`, `Name*`, `Description`, `Code`, `Type`, `Active`, `Homepage`, `Phone`, `Email`, `Institutional governance`, `Disciplines`, `Latitude`, `Longitude`, `Additional names`, `Founding date`, `Geographic description`, `Number specimens`, `Herbariorum record`, `Alternative Codes`, `Mailing address: Address`, `Mailing address: City`, `Physical address: Address`, `Physical address: City`, `entity_contacts`, `Mailing address: Postal code`, `Physical address: Postal code`, `Cites permit number`, `Catalogue URL`, `Taxonomic description`, `API URL`, `Logo URL`).
For the fields that could have multiple values, I separated them with `|` (but `;` would be good too).

I personally, don't think that a separate contact sheet is very practical. It defeats the purpose of downloading the data in the first place.
I think we could have something in between: all the content fields available + contacts with name, phone and email address together, `;` or `|` separated.

I am happy to review any suggested list of fields!

NB: I logged this issue even though it isn't part of our roadmap to keep in in mind. It isn't time sensitive or anything so if this is a lot of work, it can wait.

**Comment by ManonGros** [comment]
@fmendezh @marcos-lg  I have some question about these export functions.

1. In this download: http://api.gbif.org/v1/grscicoll/collection/export?country=US&machineTagNamespace=iDigBio.org the `number_specimens` values don't correspond to anything I can find. For example, this value is 14000000 for the collection c6c95bdc-a4ff-474c-aea2-9e47182806b7:
    * as far as I know, this field doesn't exist for collection
    * it isn't the number of occurrences linked to the collection (which is 11): https://www.gbif.org/grscicoll/collection/c6c95bdc-a4ff-474c-aea2-9e47182806b7
    * it isn't the number of occurrences linked to the institution (which is 838,636): https://www.gbif.org/grscicoll/institution/fdee1b94-e933-4a6e-9a85-05cc39a085a6
    * it isn't the value in the `numberSpecimens` field (which is 0): https://api.gbif.org/v1/grscicoll/institution/fdee1b94-e933-4a6e-9a85-05cc39a085a6

2. I might be misremembering but, last time I used this function I thought the `occurrence_mappings` field was populated with the number of occurrences linked to the collection. However, the field seems now empty (even for GRSciColl entries that are linked to occurrences). Do I misremember? Is this field for something else? In any case, would it be possible to add the number of occurrences linked to the collections and institutions?

3. Are the contacts in the exported file the new contacts or the old ones?
(Right now there are 2 fields in collections and institutions:
contacts -> old model
contactPersons -> new model)

**Comment by marcos-lg** [comment]
@ManonGros 

> 1. In this download: http://api.gbif.org/v1/grscicoll/collection/export?country=US&machineTagNamespace=iDigBio.org the number_specimens values don't correspond to anything I can find. For example, this value is 14000000 for the collection c6c95bdc-a4ff-474c-aea2-9e47182806b7:

The field exists in the DB but it's not in the UI looks like. 

> 2. I might be misremembering but, last time I used this function I thought the occurrence_mappings field was populated with the number of occurrences linked to the collection. However, the field seems now empty (even for GRSciColl entries that are linked to occurrences). Do I misremember? Is this field for something else? In any case, would it be possible to add the number of occurrences linked to the collections and institutions?

The occurrence mappings are to manually map occurrence records to collections/institutions in case we are not happy with the linked done by the lookup service. But so far nobody has used them yet.

To add the number of occurrences linked to a collection or institution it's better to put a link to a page that shows the results of a call to the occurrence API filtering by the desired collectionKey or institutionKey. I think this can be done in the UI directly. It's better not to store this count in the DB because I'd have to be updated every time the occurrences change.


> 3. Are the contacts in the exported file the new contacts or the old ones?
(Right now there are 2 fields in collections and institutions:
contacts -> old model
contactPersons -> new model)

I need to change this to return only the new ones.

**Comment by marcos-lg** [comment]
Just changed the export service to use the new contact model instead of the old one. It's in DEV for now.

**Comment by marcos-lg** [comment]
Fixed in PROD.
