### ISSUE TITLE
Make more GRSciColl fields searchable

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#357]
It would make sense to make more GRSciColl fields searchable, at least all the ones that have enums.

**Comment by marcos-lg** [comment]
Added the following fields for institutions:
- active
- type
- institutionalGovernance
- discipline: it's a list, you can specify it more than once: http://api.gbif-dev.org/v1/grscicoll/institution?active=true&type=OTHER_INSTITUTIONAL_TYPE&discipline=ARCHAEOLOGY_PREHISTORIC&discipline=ARCHAEOLOGY_HISTORIC

And for collections:
- active
- contentType: it's a list
- preservationType: it's a list
- accessionStatus
- personalCollection

It's deployed in DEV.

**Comment by ManonGros** [comment]
This is wonderful! Thanks Marcos!
