### ISSUE TITLE
grscicoll person search fails

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#359]
https://api.gbif.org/v1/grscicoll/person?limit=20&offset=
returns 

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 10 10:00:07 UTC 2021
There was an unexpected error (type=Bad Request, status=400).
```

It looks like the API might have changed to fail when the offset parameter is present, but without a value? I believe this behaviour is new as the website no longer shows any staff https://www.gbif.org/grscicoll/person/search

**Comment by MortenHofft** [comment]
From a website perspective this can be closed as the UI [now sends a value](https://github.com/gbif/portal16/commit/1cc7f477a293b39e88083750ceac3218a56bc8ca#diff-14ee880283ace0424e1a93bf1e4d3eff8d8c92da468530cc522ba62abce3dec7R13). So this can be closed unless we consider it a regression or an API change.

**Comment by marcos-lg** [comment]
Fixed and deployed to PROD.
