### ISSUE TITLE
make machine tags searchable

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#36]
inspired by https://github.com/gbif/portal-feedback/issues/734

It would be useful in some cases to have the option to search for machine tags. Basically adding params like: `dataset/search?tagDomain=GRIIS&tagKey=countryOfCoverage&tagValue=ZA`

**Comment by MattBlissett** [comment]
@fmendezh, how complicated would this be in SOLR?

It would be useful, and avoid kludging structured data into keywords.

`dataset/search?machine_tag_namespace=orphans.gbif.org&machine_tag_key=STATUS&machine_tag_value=RESCUED`

But it needs to be one tag with those values, not some combination of bits of multiple tags.

I think we should support "has a machine tag in this namespace", "has a machine tag in this namespace with this name", and "has a machine tag in this namespace with this name and this value"

**Comment by MattBlissett** [comment]
This was resolved in https://github.com/gbif/registry/commit/2cf50d745c9105bc4707bec7e88154f392bcc061 and is now deployed.

It's using dataset entity search, rather than the SOLR search.

http://api.gbif.org/v1/dataset?machineTagNamespace=orphans.gbif.org&machineTagName=status&machineTagValue=RESCUED

**Comment by MortenHofft** [comment]
Can this be used by publishers to tag their datasets? Or is it for internal use only?

**Comment by MattBlissett** [comment]
Users can use it.  They need their namespace (preferably a domain or host name) to be added to the `namespace_rights` table alongside the username they will use to make changes.
