### ISSUE TITLE
GRSciColl / specimen matching - why this record is a fuzzy match?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#360]
https://www.gbif.org/occurrence/3068371348
I thought the institution would be an exact match. Am I missing something?

**Comment by MortenHofft** [comment]
I assume it is because the institution codes do not match? `Utah State University` vs `USU`

Would you prefer that a known identifier would make for an exact match no matter if the code is wrong? I guess arguments could be made both ways.

**Comment by debpaul** [comment]
@MortenHofft 
> I assume it is because the institution codes do not match? `Utah State University` vs `USU`
The data say 

&nbsp; | Utah State University                                                                                                                                                                                                     Utah State University | Utah State University
-- | -- | --


So, they do "match" but for some reason, the string appears twice in the provider's data?

**Comment by ManonGros** [comment]
I thought that since I added `Utah State University` as an alternative code for USU, the flag wouldn't occur. Maybe I am misunderstanding how it is supposed to work.

**Comment by MortenHofft** [comment]
@debpaul
That is just the interface that is apparently confusing :) Blame me.
The title appears multiple times because it shows 
* the original as provided by the publisher
* The version available in the API, in this case interpreted for this field is just the same.
* And the matched GrSciColl institution (same name again)

<img width="904" alt="Screenshot 2021-06-16 at 11 13 26" src="https://user-images.githubusercontent.com/6759267/122192829-4a2ee100-ce94-11eb-88a3-c571d68c69b7.png">

**Comment by MortenHofft** [comment]
> I thought that since I added `Utah State University` as an alternative code for USU, the flag wouldn't occur. Maybe I am misunderstanding how it is supposed to work.

I thought it would work as well yes, but we better ask @marcos-lg. But either way it requires the data to be interpreted again. When did you add the tag (I see you edited the entry June 14th). And it looks like the dataset was last interpreted June 11th.

The API respond with an exact match
https://api.gbif.org/v1/grscicoll/lookup?institutionId=http://grbio.org/institution/utah-state-university

**Comment by marcos-lg** [comment]
The institution code is also used since it's present in the occurrence, hence the call would be:
