### ISSUE TITLE
installation search: cannot combine q and type params

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#365]
https://api.gbif.org/v1/installation?q=nonsense&type=HTTP_INSTALLATION results 69
https://api.gbif.org/v1/installation?q=nonsense results 0

**Comment by marcos-lg** [comment]
This has been fixed already with a previous refactoring I did some time ago.

Now https://api.gbif.org/v1/installation?q=nonsense&type=HTTP_INSTALLATION returns 0 results.
