### ISSUE TITLE
IH Synch -  Should we pull all the contacts?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#369]
Right now on GRSciColl, all the contacts are the same and during IH synch, we get and displayed all the contacts from IH.
However, it might not be the best idea. As @mnhn-paul mentioned:
 
> IH makes a distinction between "Correspondents/Staff" (in our case two contacts of people that actually work at the museum) and "Staff and Research Associates" which includes additional contacts of people outside of the museum (at least for us this is the case) (http://sweetgum.nybg.org/science/ih/person-list/?NamOrganisationAcronym=LUX).

They would like to avoid having people outside of the institution showing as collection contact on GRSciColl collections.

I see two possible solutions:
* We display all the contacts but make certain the distinction between the two types of contact is clear on GRSciColl
* We only pull the "Correspondents/Staff" contacts

What do you think?

**Comment by mickley** [comment]
@ManonGros: I am working on integrating some of this into Symbiota, so that we can pull institutional information from GRSciColl. 

For this sort of use, it would be very helpful to be able to get the correspondents or staff, this lets us know who to address packages to or contact, for example. In our case (OSC Herbarium), our full contacts section has a diverse group, including recently deceased people, emeritus faculty, formerly involved faculty, and various people who are tied to, but unaffiliated with our herbarium. With the exception of the deceased, they have specialized knowledge that is useful to have in our contacts, even though they do not handle any of the day-to-day work. 

So I would favor a way, as with IH, of keeping all contacts, but allowing some to be designated as correspondents.

**Comment by ManonGros** [comment]
Hi @mickley I understand the use case but we are not ready to have an elaborate model to distinguish those types of contacts.
So far we have received several emails from people confused around the contacts. I think the best is to only keep only the Correspondents/Staff in GRSciColl as it serves a practical purpose. We can roll back on the change if we find a way to better integrate those. We will be reworking our model when we will integrate the TDWG CDs, this will be a good opportunity to revisit this issue.

@marcos-lg could you make the change to pull only the Correspondents/Staff for contacts?

**Comment by ManonGros** [comment]
I tried to analyse a bit what we lose when we only take Correspondents/Staff for contacts:

- About 9,109 staff members are lost of which:
    - 6,564 have unknown `position` information
    - 392 are directors
    - 285 are curators
    - 128 are managers
    - 87 are research associate
    - many have free values like "editor, systematics and biodiversity" so it is difficult to count them.
- Given that the `current status` field isn't available via the IH API yet, I don't know how many of those contacts are retired or deceased.
- 2,741 herbaria are concerned by the change of which:
    - 1,040 don't lose any contact
    - 498 lose 1 contact
    - 294 lose 2 contacts

I think we should go ahead any make the change for the following reasons:
- Our current model doesn't accommodate for the distinction between corespondents and staff. It might change with the integration of the TDWG CDs but this is something that we will work on at the time.
- The staff information is still available on IH and via [the IH API](https://github.com/nybgvh/IH-API/wiki). Anyone is welcome to query IH directly if needed.
- People can always contact the correspondents and get redirected to the relevant people in the herbaria.
- We can roll back on the change when needed.

**Comment by mickley** [comment]
@ManonGros: I think that's fine. To integrate GRSciColl into Symbiota we really only need the corresponding contacts.

**Comment by mnhn-paul** [comment]
@ManonGros to see that a solution for this situation has been found an implemented, thanks

**Comment by marcos-lg** [comment]
Changed and deployed to PROD.
