### ISSUE TITLE
Unable to start crawl

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#37]
trying to start crawling of this dataset nothing happens
https://registry.gbif.org/web/#/dataset/3cabcf37-db13-4dc1-9bf3-e6f3fbfbbe23

I have tried from the console as well as by portal. Nothing happens. But it returns 204 as if started.

**Comment by MattBlissett** [comment]
Underlying cause makes this a duplicate of https://github.com/gbif/crawler/issues/3
