### ISSUE TITLE
UK NBN report they cannot create endorsed organisations

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#370]
The UK NBN report that they are no longer able to create organisations from their ALA installation with `endorsed=true` which is something they have done for years.

An example of a recently created entry is here:
  http://api.gbif.org/v1/organization/20a60772-3924-4d47-8db8-e310e851407a

Has something changed in GBIF webservices (perhaps Spring related) that has stopped this from working?

**Comment by timrobertson100** [comment]
The ALA [side of the code](https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/master/grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy#L124) for this hasn't changed as far as I can see, and for sure the [create SQL](https://github.com/gbif/registry/blob/master/registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/OrganizationMapper.xml#L77) in GBIF will not create an endorsed organization.

**Comment by marcos-lg** [comment]
It seems that it's no longer possible to endorse an organization at creation time. The change was probably related to the issue https://github.com/gbif/registry/issues/209 and https://github.com/gbif/registry/issues/60.

It seems that it broke the code of some existing clients, @ahahn-gbif should we restore this functionality again? we could just check that if a user sends the `endorsementApproved` flag to `true` we set in the database as `true` and we set the `endorsementStatus` to `ENDORSED` and also set the `endorsement` date.

**Comment by ahahn-gbif** [comment]
@marcos-lg: yes, please, restore the functionality. This has been in operation for years, and there is no reason why we would want to change the approach at this point. Thanks!

**Comment by JustinNBN** [comment]
That will work for us, thank you.

**Comment by marcos-lg** [comment]
Deployed to PROD
