### ISSUE TITLE
HTTP 422 on organisation create

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#372]
UKNBN report that two organizations fail to register, with ALA logs showing `422` errors, indicating that the entities fail validation. The JSON posted is based on the following content which is in the ALA Collectory schema:

  https://registry.nbnatlas.org/ws/dataProvider/dp250.json
  https://registry.nbnatlas.org/ws/dataProvider/dp255.json

We should review why this content fails as a start. Once diagnosed, we may consider relaxing validation rules, tightening the constraints in the ALA collectory, or handling this through documentation (perhaps also giving a reason as to why validation failed in the response)

**Comment by marcos-lg** [comment]
@JustinNBN would it be possible to have the requests you send to our API to create those organizations?

**Comment by JustinNBN** [comment]
> @JustinNBN would it be possible to have the requests you send to our API to create those organizations?

Hi Marcos, I'll see about getting that to you ASAP

**Comment by JustinNBN** [comment]
Hi @marcos-lg, see below for dumps of the HTTP requests we send

(for dp250 linked above)
```
--> POST /v1/organization HTTP/1.1
--> Accept: application/json, application/javascript, text/javascript
--> Authorization: Basic <redacted>
--> Content-Length: 884
--> Content-Type: application/json
--> Host: localhost:3000
--> Connection: Keep-Alive
--> Accept-Encoding: gzip,deflate
-->
--> {"endorsingNodeKey":"<redacted>","endorsementApproved":true,"language":"eng","title":"Siphonaptera and Phthiraptera Recording Scheme","description":"The Siphonaptera and Phthiraptera Recording Scheme collates records of the fleas and lice of Great Britain and Northern Ireland in order to add to knowledge of this group of insects, including distribution, population trends, autecology and phenology. In addition, the scheme works with all contributing recorders to raise the profile of the species group and its conservation.","email":["simon.horsnall@googlemail.com"],"phone":[null],"homepage":["https://www.brc.ac.uk/scheme/siphonaptera-and-phthiraptera-recording-scheme"],"latitude":null,"longitude":null,"logoUrl":"","country":"GB","province":"Oxfordshire","address":["c/o Biological Records Centre, UKCEH"],"city":"Wallingford","postalCode":"OX10 8BB"}
```
for dp255:
```
--> POST /v1/organization HTTP/1.1
--> Accept: application/json, application/javascript, text/javascript
--> Authorization: Basic <redacted>
--> Content-Length: 888
--> Content-Type: application/json
--> Host: localhost:3000
--> Connection: Keep-Alive
--> Accept-Encoding: gzip,deflate
-->
--> {"endorsingNodeKey":"<redacted>","endorsementApproved":true,"language":"eng","title":"Oil Beetle Recording Scheme","description":"The National Oil Beetle Recording Scheme aims to generate records of all UK species in the beetle family Meloidae (oil beetles and allies). Records are collated by the scheme in order to add to our current knowledge of this charismatic group of beetles, including distribution, population trends, autecology and phenology. By linking with all contributing recorders, the scheme also aims to raise the profile of this beetle family and its conservation.","email":[null],"phone":[null],"homepage":["https://www.coleoptera.org.uk/meloidae/home"],"latitude":51.5688600000,"longitude":-3.4200010000,"logoUrl":"","country":"GB","province":"Rhondda Cynon Taf","address":["4 Nant Melyn Terrace"],"city":"Tonyrefail","postalCode":"CF39 8BA"}
```

I hope that helps. I've redacted our node key here but it is the same key we use for sucessful queries elsewhere.

**Comment by marcos-lg** [comment]
Hi @JustinNBN, I was checking your requests and the problem is that the `logoUrl` validation fails. The API returns this message:

```
<ul><li>Validation of [logoUrl] failed: Invalid URI</li></ul>
```

It fails because the `logoUrl` is an empty string and we don't accept that. The solution would be that you don't send this field in these cases.

**Comment by JustinNBN** [comment]
Brilliant, cheers Marcos. I'll discuss with our data manager.

**Comment by JustinNBN** [comment]
Hi Marcos, we have resolved this on our end by excluding this field from the request where it is empty.
