### ISSUE TITLE
422  - when attempting to register datasets from ALA's collectory

### ISSUE THREAD

**Issue by djtfmartin** [gbif/registry#385]
We are getting 422 responses from registry.gbif.org when trying to register several datasets.
e.g.
https://collections.ala.org.au/dataResource/show/dr14082

Any tips on why we are getting 422s would be great.

**Comment by ManonGros** [comment]
I don't know if this is the reason why you get this response but often the registry won't accept the registration of datasets with invalid metadata. Email addresses are often the culprit.
Here I can see that the main contact's address ends with `@at3.am`. Could it be incorrect? (and Armenian domain for an Australian dataset?)

**Comment by djtfmartin** [comment]
The email address is correct - Ive had email exchange with Aaron Clausen from that address (although not for 6 years). Perhaps the filter on the registry needs to be relaxed some how.

**Comment by MattBlissett** [comment]
We have a few `org.gbif.registry.security.EditorAuthorizationFilter: User dmartin is not allowed to create network` logged, but not corresponding to the times of the 422 responses.

Do you have the JSON you are posting?

(I can't see the collectory page.)

**Comment by MattBlissett** [comment]
The email address would be accepted, but the other common place where validation fails is URLs, e.g. a homepage without `http://` at the start.

**Comment by ManonGros** [comment]
The URLs seem fine in the DwCA: https://biocache.ala.org.au/archives/gbif/dr14082/dr14082.zip
Could the license be the issue?
```
<intellectualRights>
      <para>Noosa Shire Nature Map <ulink url="https://creativecommons.org/licenses/by/3.0/au/">
          <citetitle>Creative Commons Attribution (Australia) (CC-BY 3.0 (Au) 3.0)</citetitle>
        </ulink>
      </para>
    </intellectualRights>
```

**Comment by djtfmartin** [comment]
The problem seems to be a 422 is returned if an empty `logoUrl` value is supplied for the related organisation.
I was able sync the resource above by adding a logo.

**Comment by djtfmartin** [comment]
Additional finding - we are getting a 422 when trying to sync this resource:

https://www.gbif.org/dataset/f906d1c4-6e1a-46dd-8805-ec98b5091908

2 things to note here about this resource:
* we have previously registered and updated this resource via the API - so I think so something has change on GBIF side or ALA side
* this dataset is attributed to ALA as there wasn't an obvious institution owner for it - so it was attributed to ALA to get past the registry requirement for a linked organisation.

Adding a logo to this resource didn't help in this case.

We'll work on getting the submitted JSON  - not currently easy to do with production installation.

**Comment by MattBlissett** [comment]
@mike-podolskiy90 / @fmendezh, I think we need some extra logging here.  I can see some 422 requests in the Varnish logs, but nothing looks to be logged by the registry-ws showing the error.

I can't see any 422 requests for f906d1c4-6e1a-46dd-8805-ec98b5091908, the most recent non-GET request is `[01/Oct/2021:20:36:08 +0000] "PUT http://api.gbif.org/v1/dataset/f906d1c4-6e1a-46dd-8805-ec98b5091908 HTTP/1.1" 204`.

**Comment by djtfmartin** [comment]
I've confirmed this with a few tests - a `422` is returned when `logoUrl` for an organisation is an empty string. I think is something that was introduced by changes to the  GBIF API as this was previously accepted.

This is stopping ALA sync-ing fully at the moment.  We are looking to push out an update in the next few weeks for the Collectory so we can make changes then  so a `null` value is passed instead which I presume would pass validation.

**Comment by mike-podolskiy90** [comment]
We have slightly loosened the validation in the gbif-api, so the service now accepts empty URLs and interprets them as nulls. Deployed to UAT https://api.gbif-uat.org/v1/dataset 
Fix will be included in the next release.

**Comment by mike-podolskiy90** [comment]
Closing this

**Comment by djtfmartin** [comment]
This isnt fixed unfortunately. The ALA sync is passing empty strings for the `logoUrl` and this breaks the sync.

Currently the sync works up to this organisation

**Comment by mike-podolskiy90** [comment]
@djtfmartin I've just tested a request to [UAT](https://api.gbif-uat.org/v1/dataset) with the current release, and it accepts empty `logoUrl` just fine. 
Would it be possible to have a full request body to see what's going on there please?

**Comment by timrobertson100** [comment]
The private [logs](https://private-logs.gbif.org/goto/a46fca47a6b99828b10842d0fbb8907d) (not visible outside the secretariat) show we returned `422` when doing a `PUT` on http://api.gbif.org/v1/organization/939a71e3-31e8-4917-94a6-f4dad7d059bb to sync for [this Data Provider](https://collections.ala.org.au/public/show/dp2053) from ALA.

The [commit](https://github.com/gbif/gbif-api/commit/3bcd260b289f56d82f6e66df675e31e725d37e10) I think originally intended to fix this looks to be applied on `Dataset` only.  Could it be that we miss an `OrganizationMixin` and equivalent functionality perhaps @mike-podolskiy90?

**Comment by mike-podolskiy90** [comment]
Indeed, that fix was for datasets only. Now I added that to organizations, nodes and network as well.
Deployed to prod (registry v3.70)
@djtfmartin Could you check that works now

**Comment by djtfmartin** [comment]
thanks @mike-podolskiy90  - looks good to me !
