### ISSUE TITLE
Images not loading for crawled datasets

### ISSUE THREAD

**Issue by djtfmartin** [gbif/registry#386]
e.g.
https://www.gbif.org/occurrence/1917072578#occurrencePage_media

our archives have recently changed so I suspect the issue lies there.

Example archive: https://biocache.ala.org.au/archives/gbif/dr8129/dr8129.zip

**Comment by MattBlissett** [comment]
I have cleared the cache for that dataset.  Are there others?

On 24 September the image cache retrieved the placeholder/not found images and cached them.  I don't think this relates to your archives, but maybe image links being published before images are in place.

**Comment by djtfmartin** [comment]
The image for this record is loading now. This can be closed.
