### ISSUE TITLE
GRSciColl - IH synch - include division and department for mailing address in collections

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#394]
Some IH entry include information about institutional departments holding collections. For example: http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125620
It seems that we don't keep that information: https://registry.gbif.org/collection/77a9b1ba-a136-4246-ba7c-0a5cf3e49266

Would it be possible to store it for collections?
It was pointed out that these are useful to address packages, perhaps having them in the mailing address would be a good start?

**Comment by mickley** [comment]
@ManonGros, thank you. To clarify, there are two fields on IH, division, and department that are not in GRSciColl. Some collections have one, some have the other, and some have both. 

For example, DAO is:
Agriculture and Agri-Food Canada
Science and Technology Branch
Biological Collections Division

They include all three on their mailing address. But GBIF is only going to have the first one, at least at this point. 
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=123914

**Comment by mickley** [comment]
@ManonGros:
Is there any progress on including the division and department fields from Index Herbariorum in GrSciColl? I would like to integrate GrSciColl into Symbiota for pulling in institutional information in to send out loans, exchanges, and gifts, and have some time this summer to do this. 

The other issue #369 has now been fixed, but having these fields are important for making sure that Symbiota gets the full institutional address for a collection for mailing packages.

**Comment by ManonGros** [comment]
@mickley, keep an eye on this issue, we are working on adding the division and departments as new fields in the API. I don't know when it will be made available in the UI but at least the information will be accessible via the API.

**Comment by MortenHofft** [comment]
Address is currently a text string in GrSciColl. 

Instead of adding explicit fields we could also just repeat the approach we have on datasets - namely making address a list.
http://api.gbif.org/v1/dataset/fa7e6ad8-0a2e-49f2-b95d-e9f1e380fadf
Not that I mind strongly modelled fields at all, but might be one of those things that are so flexible and different between countries that it makes sense just letting it be unstructured.

**Comment by ManonGros** [comment]
Thanks Morten, I hadn't thought of that. @marcos-lg what do you think of the solution suggested by Morten?

**Comment by marcos-lg** [comment]
We need it to be structured for the sync with IH in order to see if the field has changed and needs updating. Anyway, in IH it's already structured even though they display it in the UI in an unstructured way.

**Comment by marcos-lg** [comment]
Deployed to PROD. In the next IH sync (which will be tomorrow) the division and the department will be populated in the collections.

**Comment by mickley** [comment]
@marcos-lg, @ManonGros Thank you very much!
