### ISSUE TITLE
GRSciColl - entries synched with IH aren't linked to IH in the UI

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#396]
It seems that the latest IH synch didn't create identifiers for IH-synchronized entries.
The problem is that the UI uses the IH identifiers to redirect the users to IH. So users don't know that their entries are synchronised with IH and that they have to edit the data in IH.

In future, it would be better if the UI used the machineTags instead of the identifiers for the linking (https://github.com/gbif/registry-console/issues/379).

But I think we should still keep the IH identifiers as some people might find them helpful regardless of the synchronisation system. What do you think?

**Comment by marcos-lg** [comment]
Fixed in the IH sync and deployed
