### ISSUE TITLE
resetting passwords sends welcome email

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#40]
If you forget your password and reset it, then you will get two email. one for resetting and another welcoming new users.

Is that on purpose?

**Comment by timrobertson100** [comment]
Email notification of password edits seems sensible to me and fairly common practice.

**Comment by mike-podolskiy90** [comment]
Message:

Dear <accountname>,

The password for your GBIF account <accountname> was changed. If you didn't change it, please immediately contact helpdesk@gbif.org.

The GBIF Secretariat

**Comment by MattBlissett** [comment]
Until we record the user's language in the Registry, should we send that email in several languages?

> Dear accountname,
>
> The password for your GBIF account accountname was changed. If you didn't change it, please contact helpdesk@gbif.org immediately.
>
> Пароль для вашей учетной записи GBIF был изменен. Если вы не меняли его, немедленно свяжитесь с helpdesk@gbif.org.
>
> The GBIF Secretariat

etc.

**Comment by mike-podolskiy90** [comment]
I suggest enabling users to choose preferable language in the profile and to store user's language in the registry DB
