### ISSUE TITLE
GRSciColl - add CITES number to identifiers during IH synchronisation

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#406]
Following the implementation of: https://github.com/gbif/registry/issues/405

It looks like some IH entries have a CITES number: http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125812. These institution registration numbers in CITES could be added as CITES identifiers during synchronisation if they aren't already associated with the GRSciColl entry.

Reference to issue describing the IH synchronisation: https://github.com/gbif/registry/issues/167

**Comment by marcos-lg** [comment]
Released. It will be used in the next sync.
