### ISSUE TITLE
cannot delete users from the registry interface

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#41]
Nothing seemingly happens when clicking the delete button on a user.

**Comment by MattBlissett** [comment]
The API call gives 404.

I edited the registry database yesterday, I think you've done the same.

**Comment by MortenHofft** [comment]
but shouldn't the users appear as deleted then?

**Comment by MattBlissett** [comment]
Yes, but this is the first time we've actually deleted a user!

**Comment by MortenHofft** [comment]
ahh. ok :) But the users you have deleted the other days didn't show up in the registry as far as i could see
