### ISSUE TITLE
GRSciColl - cannot create institution from organization Corporación San Jorge

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#412]
This comes from our Colombian Node, they tried creating an institution from this GBIF organization (https://www.gbif.org/publisher/1904954c-81e7-4254-9778-ae3deed93de6) but it give a non-specific error message.
I also get the same issue with my admin account. It seems like an API issue.
Would it be possible to investigate @marcos-lg ?

**Comment by marcos-lg** [comment]
The problem was that the email addresses of one of the contacts of the organization was wrong. If it's fixed the creation of the institution works correctly.

I improved the error message to have a better understanding of the problem. It's in DEV for now.

**Comment by marcos-lg** [comment]
Deployed the more-detailed messages to PROD.
