### ISSUE TITLE
GRSciColl - cannot update collection name for IH synchronised collection

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#414]
The UI seems to let users modify the collection names but when clicking save, nothing happens.
I have the same problem when applying suggestions: https://registry.gbif.org/collection/957d6efc-672e-4a49-a8a2-a4cd0cb28cee?suggestionId=224
I tried doing the same with the API, I don't get any error message but the name remains the same.
@marcos-lg could you take a look? Thanks!

**Comment by marcos-lg** [comment]
It's a bug. It's locking the name because of the master source but for IH the name is overridable.

**Comment by ManonGros** [comment]
Thanks @marcos-lg ! Let me know when it is in production so I can updates some entries

**Comment by ManonGros** [comment]
@marcos-lg would it be possible to fix it in production? I have had more update suggestions for changing herbarium names.

**Comment by marcos-lg** [comment]
yeah, sorry, I'll deploy it next week.

**Comment by marcos-lg** [comment]
Deployed to PROD.
