### ISSUE TITLE
GRSciColl - occurrence mapping doesn't allow me to link occurrence to institution

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#419]
I am trying to map the occurrences of this dataset: https://www.gbif.org/dataset/bbd4effa-9796-4e0c-8c1a-0b92f6a95907 to this GRSciColl institution: https://www.gbif.org/grscicoll/institution/54915ead-6124-4878-ad04-d14b9876832a

I have added some occurrence mapping: https://api.gbif.org/v1/grscicoll/institution/54915ead-6124-4878-ad04-d14b9876832a/occurrenceMapping
Then I waited until the GRSciColl cache is refreshed and reinterpreted the data. But the occurrences are still not linked to the institution: https://www.gbif.org/occurrence/3024215899
According to the lookup service it should work: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=NHMTU&datasetKey=bbd4effa-9796-4e0c-8c1a-0b92f6a95907

In addition to that, I also tried linking the occurrence a default institutionID to the dataset: https://registry.gbif.org/dataset/bbd4effa-9796-4e0c-8c1a-0b92f6a95907/defaultValue but it doesn't show during the dataset reinterpretation.
I don't know if the issue has to do with the dataset reinterpretation or something else, this issue might even be in the wrong repo, could you help me @marcos-lg ?

related issue: https://github.com/gbif/collection-mobilization/issues/1272

**Comment by ManonGros** [comment]
https://github.com/gbif/pipelines/issues/695

**Comment by marcos-lg** [comment]
@ManonGros it was a cache issue that we haven't deployed to prod yet. But we just cleared it. Can you reinterpret the dataset and check again?

**Comment by ManonGros** [comment]
Thanks @marcos-lg ! I just reinterpreted the dataset but the occurrences don't seem to be linked: https://www.gbif.org/occurrence/3024216345

**Comment by marcos-lg** [comment]
The dataset hadn't been crawled since it wasn't modified. I forced the crawl and it worked now.

Reopen if affects to more datasets.
