### ISSUE TITLE
doi-synchronizer should choose extant rather than deleted datasets

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#42]
...if two or more datasets share a DOI.

e.g. 10.15468/btkum2.

**Comment by MattBlissett** [comment]
https://github.com/gbif/portal-feedback/issues/2112
https://github.com/gbif/portal-feedback/issues/3194

Two more cases for this.

**Comment by MattBlissett** [comment]
./doi-synchronizer --doi 10.15468/ts7wsb

This gives an error, since the dataset key is invalid: `Dataset key: 4c103172-ce29-4673-b9a4-bca75419df9d,bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598`.

**Comment by mike-podolskiy90** [comment]
doi-synchronizer seems fine now. All of those DOIs are fixed. Will be deployed to prod on Monday
@MattBlissett can you also check please

**Comment by mike-podolskiy90** [comment]
registry v3.49
