### ISSUE TITLE
Deleted publishers in GBIF can be selected in the Publisher filter

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/registry#421]
When you use the Publisher filter, it shows you the names of organizations that has been deleted from GBIF and don't have data available. As an example, we deleted this organization a long time ago [Museo de Historia Natural Marina de Colombia – INVEMAR](https://www.gbif.org/es/publisher/1d512cd8-810c-4afc-b1ef-bd1a25bfd3fa) but it appears and can be selected. It can confuse users to see this publisher, with no data and already deleted.
![image](https://user-images.githubusercontent.com/63795703/164759997-f0488a73-c576-4571-9106-5bc217bb8d63.png)

This happens in the GBIF data portal too, but it would be nice if deleted organizations with no data are not indexed for search in the data portal, to avoid misunderstandings.

**Comment by marcos-lg** [comment]
Fixed in PROD.
