### ISSUE TITLE
Email format error when submitting a suggestion

### ISSUE THREAD

**Issue by ckotwn** [gbif/registry#422]
The submission to https://registry.gbif.org/institution/b0fb6fa3-633b-4486-9018-8f746603946e failed with a warning of email format, please see the image.

<img width="1616" alt="Screenshot 2022-04-29 at 20 23 57" src="https://user-images.githubusercontent.com/637631/165945131-f5186cc4-7c12-4ea6-bf42-0459bc3cb751.png">

**Comment by marcos-lg** [comment]
The error is actually in the email of a contact. In UAT it's the `bazilah_mohd_ibrahim@nparks.gov.sg.` that ends with a `.`. @ckotwn can you try to change it in production?

I'll have to improve the error message.

**Comment by ManonGros** [comment]
@marcos-lg the data come from IH so he can't change it in the registry unless he disconnect the entry form IH.

Could the IH synch generate an error when contacts have issues? I could then notify IH.

**Comment by marcos-lg** [comment]
I changed it in the database. This happened because the validation was added after the IH sync so before it was valid but now in the sync this contact will fail and won't be updated.

In the IH sync I can also create issues if there are invalid emails.

**Comment by ManonGros** [comment]
Thanks Marcos! I also wrote to IH so hopefully the dot will be removed at the source.

If it isn't too much work for you, it would be good if the IH synch could create issues for invalid emails. (I hope I won't regret this request)

**Comment by marcos-lg** [comment]
Just changed the IH sync to create issues when the institution and/or contacts have invalid emails
