### ISSUE TITLE
endorsements via the registry UI for Nodes?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#423]
I thought I remembered that nodes could endorse organizations in their scope via the registry UI. But today someone who has a node-level permission told me that they couldn’t do it. And indeed, the interface doesn’t show the endorsement status.

Is it intentional? Do I remember correctly that Nodes used to be able to endorse organizations directly in the Registry?

**Comment by MortenHofft** [comment]
@ManonGros would you like it to be possible? It sounds to me like it makes sense, but it isn't something I have dealt with before.

**Comment by ManonGros** [comment]
Thanks @MortenHofft! I checked with @ahahn-gbif and endorsement via the registry UI is actually not something we would like to offer to the registry users because not everyone with node-level permissions are node managers. Thanks for looking into this, I will close the issue.

**Comment by MortenHofft** [comment]
kk - in theory I guess the backend could check the user against the directory if using the same email or such, but that sounds like a larger task
