### ISSUE TITLE
project_identifier column in CSV export is empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/registry#424]
**project_identifier column innCSV export is empty**

I think this is an API issue but the export function doesn't allow us to get the project identifiers associated with datasets.
This field is really useful for people trying to showcase the work in the context of the BID program. Could someone take a look?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/7ce29e434373145ae953a3f403d989ab:ff6987b8e04778ff38b5b7871602dcfefeb8052e4a84f182fe6c6183089a58cd3b8cbe0a5fa6829d94a28174b332a6838603ffda0cc3c8edbe6fe81bfdfb059f0208f45b5a557dce4181949d32378a589596933dc47319b9dc91a4900b67d64ebb356ca711cb049ee3bcf72b60581d22603bb6398b6fd9833000ac4d91434c80cd414e1a9fccfc24f8625b992a701b40) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7ce29e434373145ae953a3f403d989ab:ff6987b8e04778ff38b5b7871602dcfefeb8052e4a84f182fe6c6183089a58cd3b8cbe0a5fa6829d94a28174b332a6838603ffda0cc3c8edbe6fe81bfdfb059f0208f45b5a557dce4181949d32378a589596933dc47319b9dc91a4900b67d64ebb356ca711cb049ee3bcf72b60581d22603bb6398b6fd9833000ac4d91434c80cd414e1a9fccfc24f8625b992a701b40)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/search?q=
Window size: width 1295 - height 807
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-23T14:04:20.727Z',to:'2022-05-23T14:10:20.727Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-23T14:04:20.727Z',to:'2022-05-23T14:10:20.727Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by marcos-lg** [comment]
Fixed in PROD.
