### ISSUE TITLE
OBIS citation requirements

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry#43]
(via email from OBIS, 25.9.2017)

Regarding the citations: We think that citations of the same dataset should be as similar as possible regardless of which system (OBIS, EMODnet or GBIF) they are downloaded from. The dataset citations we provide were actually agreed upon with the data originators and - to avoid issues with our providers (if they notice the differences, this will raise questions) - we would therefore prefer that they are kept as such in GBIF, which would also allow greater transparency and traceability. 
If it would not be possible to keep the citation we provided, we would like to be able to recreate them in the GBIF portal as closely as possible. From what I can tell, the current implementation for generating dataset citations in the GBIF portal would prevent this due to the following issues.
 
**Issues which may or may not relate specifically to VLIZ**:
-  **Publication year**: We regenerate all our IPT resources every time the EurOBIS database is updated. For most datasets the data will not have been changed. GBIF uses as publication year the date that data resource was last modified. For our datasets _the year that the IPT resource was regenerated does not reflect the publication year of our datasets_, which will therefore result in the GBIF portal having incorrect publication years in the citations.
- **Version and download date**: As our resources will be regenerated each time, the version number will each time be 1.1, regardless of the actual dataset version. The EurOBIS DOI approach is to assign a new DOI for each new published version (= significant modification/correction of the data or the addition/deletion of records) of the dataset, therefore the _download date and version number are actually irrelevant_.
- We tend **not to list publishers** in our default citation format.
 
**General issue**
 
- In our default citation format, we allow **institutes to be listed as data creator**. We also allow for _multiple institutes_ to be listed in the citation, as well as only persons or both persons and institutes. The current implementation of the GBIF portal does not allow listing institutes other than the publisher in the citation. 
This seems to differ from the implementation in the citation generator tool (at least at the VLIZ IPT Version 2.3.4-r68469e8), as well as the GBIF implementation to generate DOIs, as both do use institutes listed as Resource Creators as Data Creators in the citation. Did I understand correctly from earlier communication that this difference in approach between the 3 systems is deliberate? 
 
A good example for the latter would be the following DOI: https://search.datacite.org/works/10.15468/7wd1vk. Which list as citation: 
 
_MNHN. (2017). The cnidarians collection (IK) of the Muséum national d’Histoire naturelle (MNHN - Paris) [Data set]. MNHN - Museum national d’Histoire naturelle. https://doi.org/10.15468/7wd1vk_
 
Where MNHN is listed as a Resource Creator in the IPT resource. I think that this citation is the very similar to the one that would have been generated by the IPT. While https://www.gbif.org/dataset/b5cdf587-3342-48ec-9130-ba1281d7166f#citation lists as citation: 
 
_MNHN - Museum national d'Histoire naturelle (2017). The cnidarians collection (IK) of the Muséum national d'Histoire naturelle (MNHN - Paris). Version 37.26. Occurrence Dataset https://doi.org/10.15468/7wd1vk accessed via GBIF.org on 2017-09-21._

**Comment by MattBlissett** [comment]
Could you give an example, using an OBIS dataset, of what OBIS would like the citation to be?

Maybe https://www.gbif.org/dataset/83a517aa-f762-11e1-a439-00145eb45e9a is suitable, but I'm not sure.

**Comment by ahahn-gbif** [comment]
The original at http://ipt.iobis.org/obiscanada/resource?r=arc reads:

"Van Guelpen, L., 2016. Atlantic Reference Centre Museum of Canadian Atlantic Organisms - Invertebrates and Fishes Data. Version 4 In OBIS Canada Digital Collections. Bedford Institute of Oceanography, Dartmouth, NS, Canada. Published by OBIS, Digital http://www.iobis.org/. Accessed on –INSERT DATE"
As I understand, the citation strings crafted in the IPT are the ones that they would prefer to be used, but I'll try to confirm.

While at https://www.gbif.org/dataset/83a517aa-f762-11e1-a439-00145eb45e9a, we give

"Van Guelpen L (2016). Atlantic Reference Centre Museum of Canadian Atlantic Organisms - Invertebrates and Fishes Data. Canadian node of the Ocean Biogeographic Information System (OBIS Canada). Occurrence Dataset https://doi.org/10.15468/wsxvo6 accessed via GBIF.org on 2018-03-21."

**Comment by MattBlissett** [comment]
"Version 4..." only appears in the citation of their IPT (and hence in the [exported EML](http://ipt.iobis.org/obiscanada/eml.do?r=arc&v=5.3)), so the way to achieve this would be to use the IPT-provided citation.

A change in https://github.com/gbif/registry/blob/master/registry-ws/src/main/java/org/gbif/registry/ws/resources/DatasetResource.java#L380 should achieve this.

How should it be applied? By filtering for members of the [OBIS network](https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6)?

**Comment by ahahn-gbif** [comment]
Again, need to confirm with OBIS, but assume that yes. NB the network membership presently requires manual maintenance in the registry to keep updated, but is the right starting point.

**Comment by ahahn-gbif** [comment]
From email exchange with EurOBIS: 
"(...) All this said, we really started this exercise to deal with the problem of messy citations. OBIS, on the other hand, has a very well managed system of consistently providing citations in an appropriately standardized format. So in your case, we probably overshot our target a bit by pushing GBIF-generated replacements on top and overruling your version. We had so far been discussing a slightly different solution for fixing this: for datasets provided by OBIS [a filter we will still have to define, based on most likely network membership of datasets], use the custom generated citation string directly as provided from source rather than the auto-generated version from IPT metadata. If the DOI is already part of that citation, use as-is; if a DOI is missing, add the DOI generated during registration with GBIF. Would that work equally well for you? And for other OBIS nodes?" (ah)
->"As I can only speak for EurOBIS I forwarded the issue to Anton who is the designated OBIS-GBIF liaison. For me the solution you propose would work perfectly. "

**Comment by ahahn-gbif** [comment]
"I would like to confirm that GBIF can show OBIS provided citations where they are present" (via email to helpdesk, Pieter, 9.3.20)
Scope: any citations for datasets from the OBIS network, unless the citation string is empty (in this case, still auto-generate the GBIF version). Citation quality: OBIS to reach out to the Nodes

**Comment by MattBlissett** [comment]
Here are publisher citations that are broken in some technical way.

(It's partly based on data on the dev system, so might be a few months out of date.)

### Rescued orphans

I can fix these by looking at old downloads to see what it's supposed to be.

- [ ] 83a65020-f762-11e1-a439-00145eb45e9a
- [ ] 83a7950c-f762-11e1-a439-00145eb45e9a
- [ ] 83ad4862-f762-11e1-a439-00145eb45e9a
- [ ] 83afb58e-f762-11e1-a439-00145eb45e9a
- [ ] 83b45ca6-f762-11e1-a439-00145eb45e9a
- [ ] 83c964d4-f762-11e1-a439-00145eb45e9a

→ Matt.

### No metadata document in the registry, EML probably invalid

These will take a GBIF format citation until fixed.

- [ ] 00eb5629-35bc-439c-afe4-3c8d5ac51360
- [ ] 915f1c6d-5c17-4365-893a-a284afd8b5b9
- [ ] 248832e4-ddab-4b2f-8e46-87212dc508a6
- [ ] 6be24d2a-bbda-4cea-b2bf-8f7043126639
- [ ] edc29fd6-ff2e-48cb-a6d4-0de00c33b6b4
- [ ] f0a30229-2026-41ad-93e8-9415ed8efdbf
- [ ] e62d2839-507f-4582-bf65-db8f5a814620

→ DP in the first instance? The data validator should help.

### No metadata document in the registry, DIGIR dataset

These will take a GBIF format citation until they're fixed

- [ ] 96309e26-f762-11e1-a439-00145eb45e9a
- [ ] 96180cd0-f762-11e1-a439-00145eb45e9a

→ Matt

### No citation provided by OBIS (otherwise OK)

- [ ] 544aabb8-bd2a-44ef-8917-a3b9c70bb837
- [ ] 3a288cf3-4038-4759-a2d9-4541b10e41e3
- [ ] 4a2b819f-c539-4362-badc-8a9c85246c26
- [ ] da209453-8d41-4a29-b759-1f5e1a2b6980
- [ ] 7ffd804c-d389-41ad-84ba-4ad5d51d8f04
- [ ] 0e0b04c4-df34-4205-a039-748c9e70cc9c
- [ ] 4a53a180-f0c8-4dd8-a1fb-18768668edc9
- [ ] b52cb0c3-c024-46c4-b7b2-d635400ff6d1
- [ ] 6d28a527-bf84-4e58-b133-0e60987b5e7c
- [ ] 60c45f15-135d-42fb-8b8e-dd11c6375ad8
- [ ] ea8469bb-918a-4a15-9448-5509e36d229a
- [ ] 0628cc70-37e0-4353-949d-e3990bc2a341
- [ ] b1c6b7a6-4c57-4814-93bc-d5c0c5743203
- [ ] 6686c610-9d99-459e-b229-fdf3ac35a197
- [ ] 683957d7-7bb8-44da-bdc1-8d61a41d2b7b
- [ ] 3c381293-9b33-477d-84ed-c7da7302f384
- [ ] 83ea4307-fd04-467c-af87-271a963841fc
- [ ] 7b940ada-f762-11e1-a439-00145eb45e9a
- [ ] 7b61ebd6-f762-11e1-a439-00145eb45e9a
- [ ] 7b5d6a48-f762-11e1-a439-00145eb45e9a
- [ ] 197908d0-5565-11d8-b290-b8a03c50a862
- [ ] 8922dd20-f762-11e1-a439-00145eb45e9a
- [ ] 890e8604-f762-11e1-a439-00145eb45e9a
- [ ] 890d62e2-f762-11e1-a439-00145eb45e9a

→ No action.

### Others

These have a publisher-provided citation, but it's not up-to-date in the database. It might be a sign of an old bug in the registry (fixed, but I don't know if affected datasets were fixed), or a prod/dev difference. Investigate.

- [ ] adb92d68-aaff-47ba-b197-d3d26f72f728
- [ ] ec245bc1-4812-438d-8d07-5d74ad0bd496
- [ ] 3e652fbf-04f3-4b32-8cc0-a90c54ebf743
- [ ] 7b517a6c-f762-11e1-a439-00145eb45e9a
- [ ] 7b42aea6-f762-11e1-a439-00145eb45e9a

→ Matt?

**Comment by MattBlissett** [comment]
@ahahn-gbif, I've fixed what's mine to fix, by either editing the eml.xml in the orphan DWCAs to the last citation we have in the database before the orphan export, or (for "Others") re-interpreting the metadata, which for some reason wasn't in sync.

The rest are for OBIS to fix, though they may need guidance for the "No metadata" 7, as those probably have EML validation errors as in https://www.gbif.org/tools/data-validator/1580460392938

**Comment by pieterprovoost** [comment]
@MattBlissett I still need to look into your results, but I did a quick analysis of OBIS datasets in GBIF: https://iobis.github.io/obis-gbif-notebook/ There seem to be around 400 datasets which should be added to the OBIS network.

**Comment by MattBlissett** [comment]
I will come back to this tomorrow.

On our test system, gbif-uat.org, I've added the 400-ish datasets to the OBIS network. (A few aren't present in gbif-uat.org, as they've been added fairly recently to gbif.org and we only copy over the database occasionally.)

[Andrea, I see we don't have a way to let external people add datasets to networks, but I don't know your process -- I can repeat this in production easily. The third column from https://github.com/iobis/obis-gbif-notebook/blob/master/obis_not_in_network.csv is the GBIF dataset key, so `for i in $(cut -d, -f 3 obis_not_in_network.csv | tr -d '"'); do echo $i; curl -i -X POST --user user:password 'https://api.gbif-uat.org/v1/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/constituents/'$i; done`]

https://www.gbif-uat.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/dataset

UAT is showing the citations with the changes discussed above, e.g. https://www.gbif-uat.org/dataset/ee51f04c-addc-4d04-99a7-61e53fd641ad has

> **Hebda, A.(2014). Nova Scotia Museum of Natural History - Freshwater mussels. Version 1 In OBIS Canada Digital Collections. Bedford Institute of Oceanography, Dartmouth, NS, Canada. Published by OBIS, Digital http://www.iobis.org/. Accessed on –INSERT DATE** https://doi.org/10.15468/al0unx accessed via GBIF.org on 2020-03-11.

with the bold bit being the citation provided by OBIS, and the same is present in a [download](https://www.gbif-uat.org/occurrence/download/0000048-200221155752679).

**Comment by ahahn-gbif** [comment]
Thanks, @MattBlissett! This is a slightly different discussion - adding datasets to networks has a registry permissions aspect to it that is not quite as simple as it looks; we are discussing a proposal for a moderated process, enabling networks to manage the information and only requiring a registry admin to trigger the update registry-side (similar to proposing easier edit workflows on the GrBio/GrSciColl side). So far, adding datasets to networks is a central procedure, though we only require the dataset UUIDs. @ManonGros, could I ask you to look at the update that Matt suggests? Thanks!

**Comment by ahahn-gbif** [comment]
@pieterprovoost, there are two aspects to this: datasets that are registered to GBIF, but not yet added to the OBIS network entry, and datasets that we would like to register to GBIF (again). Adding registered datasets to the network entry, as sketched in my email, unfortunately needs to happen at our side for the time being, but if you could let us know which ones those are, it should be quick, and we are more than happy to support you on this. (Re)registering datasets would need to happen before that, though. We noticed a lot of activity on that a couple of days ago; is there more we should wait for?

**Comment by ManonGros** [comment]
@ahahn-gbif I added the datasets in prod (they are already visible in the registry console although not yet on GBIF.org)

**Comment by MattBlissett** [comment]
These two datasets have a GBIF-style citation within their IPT metadata:
* https://www.gbif.org/dataset/8a756d0f-ed04-4855-bb67-e421e06ef2e9
* https://www.gbif.org/dataset/44839329-fa4d-468d-9da0-39739a2d0b63
This will need to be corrected by NZ OBIS, as we currently have (on UAT) "Sampling_event Dataset https://doi.org/10.15468/s7ctpf accessed via GBIF.org on 2018-01-15. accessed via GBIF.org on 2020-03-12."

The technical work is complete, as well as checks/synchronizing (on our side) for any out-of-sync datasets.

Let me know when it should be deployed to gbif.org.

**Comment by MattBlissett** [comment]
This is now deployed.
