### ISSUE TITLE
dataset search license facet wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/registry#430]
**dataset search license facet wrong**

When doing a checklist dataset search there are no unspecified licenses in the facets. The registry does give some though, so these go missing in the portal: https://api.gbif.org/v1/dataset/search?type=CHECKLIST&limit=0&facet=license

Also the counts dont add up in the portal because of that

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/70184c6cbe7ca2cd37a9918c87a562cb:3e09a16257abe2ea58b278fab677b2cd6a38270bd82b3602bfeb0f2742b01481faafc3a0f206cfd6a4510db7a38816f6ebead2d32ab30064de013c6d2076ac53709b1c985118ec05a89a53fc4ac758c2168351415165c1f83d829d63959eb11aac23b0dbd803cee656babaea9794f148a8f7c7321dc3066aac1acacd03c08968) - [Send email](https://www.gbif.org/api/feedback/user/mailto/70184c6cbe7ca2cd37a9918c87a562cb:3e09a16257abe2ea58b278fab677b2cd6a38270bd82b3602bfeb0f2742b01481faafc3a0f206cfd6a4510db7a38816f6ebead2d32ab30064de013c6d2076ac53709b1c985118ec05a89a53fc4ac758c2168351415165c1f83d829d63959eb11aac23b0dbd803cee656babaea9794f148a8f7c7321dc3066aac1acacd03c08968)
System: Safari 15.4.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/search?type=CHECKLIST
Window size: width 1194 - height 811
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-19T12:35:25.396Z',to:'2022-08-19T12:41:25.396Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-19T12:35:25.396Z',to:'2022-08-19T12:41:25.396Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by marcos-lg** [comment]
fixed
