### ISSUE TITLE
GRSciColl - applying contact update suggestion overwrites previous suggestion

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#433]
When a user tries to update several contacts for a collection or an institution via the suggestion system, the last suggestion overwrites everything else.
The problem is that the change stored will only remember the current state.

So for example, if a user wants to delete two contacts, they will make two suggestion update, but applying the last one will restore the first contact they had deleted.

Right now when I need to apply this type of suggestion, I will discard the suggestion and make the changes manually myself.
Since we are getting more mediators that are reviewing the suggestion changes, it would be better if this was a little more user-friendly.

**Comment by marcos-lg** [comment]
Deployed to PROD.
