### ISSUE TITLE
GrScicoll: numberOfSpecimens added to search API

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#434]
@ManonGros and @marcos-lg
For GrSciColl should we get numberOfSpecimens added to the search API (institutions and collections)? That seems like it would be useful for data mobilization. Especially if we also had "number of shared specimens"

**Comment by ManonGros** [comment]
Yes that's a good idea Morten! I think it would be really useful for data mobilisation.

**Comment by MortenHofft** [comment]
Just to clarify the issue. The suggestion is to expose `numberSpecimens` from the API. e.g. https://registry-api.gbif.org/grscicoll/collection/0f563d5f-6ff0-4e7b-8bd8-dfac30efd9f1

So that users can search for institutions or collections that have e.g. above 2000 specimens.

I'm not sure what to do with all those that have no counts stated. It would be useful to search for them, but it isn't clear how it would work. I guess zero could be used, but it is a bit like misuse

**Comment by MortenHofft** [comment]
It would be so much easier just to have this in ES, then we could just use the predicate API

**Comment by ManonGros** [comment]
I agree Morten, that's what I thought too.

Actually I could also imagine the case where people would like to identify small collections (more likely to hold local specimens). But in this case since the number of specimen is zero when not provided, I am not sure how this could realistically be achieved.

**Comment by marcos-lg** [comment]
I had changed the field some time ago to be able to have that field as null by default and not zero. Although I didn't clean the values in the database. But we could replace the zeroes with nulls
