### ISSUE TITLE
grscicoll collection suggest

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#437]
https://api.gbif.org/v1/grscicoll/collection/suggest?limit=8&q=k

I believe it would be useful to include the institution name in both search matches and response. Institution name should probably have a lower boost than collection name and codes though.

**Comment by marcos-lg** [comment]
Agreed with @MortenHofft to use the search endpoint: https://api.gbif.org/v1/grscicoll/search?q=SMI&hl=true&entityType=INSTITUTION&displayOnNHCPortal=true

Reopen if necessary.
