### ISSUE TITLE
cannot search for pending collections : error 500

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#438]
https://registry-api.gbif.org/grscicoll/collection/changeSuggestion?q=&limit=25&offset=0&status=PENDING
fails with status 500 - whitelabel

https://registry-api.gbif.org/grscicoll/collection/changeSuggestion?q=&limit=25&offset=0&status=APPLIED
works fine

I'm guessing it is related to the new displayOnNhcPortal flag. But have no idea

**Comment by MortenHofft** [comment]
possible related to https://github.com/gbif/registry/issues/439

**Comment by marcos-lg** [comment]
Fixed
