### ISSUE TITLE
grscicoll suggest api error

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#439]
https://api.gbif.org/v1/grscicoll/institution/0237598a-853a-492c-af74-a723fe251799
works fine
but https://registry.gbif.org/institution/0237598a-853a-492c-af74-a723fe251799
fails due to API errors
https://registry-api.gbif.org/grscicoll/institution/changeSuggestion?entityKey=0237598a-853a-492c-af74-a723fe251799&status=PENDING

**Comment by marcos-lg** [comment]
Fixed
