### ISSUE TITLE
Is being matched to a collection from another institution

### ISSUE THREAD

**Issue by gbif-portal** [gbif/registry#441]
**Is being matched to a collection from another institution**

This record is being matched to both institution and collection, but the collection doesn't belong to the institution. That seems like something that should at least get a flag, if not match at all

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/1c3b5e1b2a53e8822a315b1d2534042f:19e531706a0b36adc632e05b7b1aabf83094e3933d94eca659154e5bb8180841d8c36ae7b9cb4dc513356d21b99e17c9d239bee2acebf37509e45d7a7de4d6e13310b267ec00f0068b98b4c52aaea49695b6f83a2a37401c533d13a7f380351ba97b57d35dd5701bab09a267281cedb28102044ccb8ca0c447ebee3bda7400ca) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1c3b5e1b2a53e8822a315b1d2534042f:19e531706a0b36adc632e05b7b1aabf83094e3933d94eca659154e5bb8180841d8c36ae7b9cb4dc513356d21b99e17c9d239bee2acebf37509e45d7a7de4d6e13310b267ec00f0068b98b4c52aaea49695b6f83a2a37401c533d13a7f380351ba97b57d35dd5701bab09a267281cedb28102044ccb8ca0c447ebee3bda7400ca)
System: Chrome 105.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3750817437
Window size: width 1728 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-23T19:46:49.171Z',to:'2022-09-23T19:52:49.171Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-23T19:46:49.171Z',to:'2022-09-23T19:52:49.171Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7d3fbc21-38f9-43b5-98d4-1ed7c65f7103
publishingOrgKey: 689b40c4-ff31-4cd0-83a5-a7a828f1cd92

**Comment by ManonGros** [comment]
Thanks @marcos-lg yes please go ahead

**Comment by marcos-lg** [comment]
Fixed in the lookup service. It won't be effective in the occurrences untill the cache is cleaned(it happens weekly) and the dataset reinterpreted.
