### ISSUE TITLE
founding date = -1

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#444]
After todays update of `foundingDate` to a string, then -1 appears. I assume it is in cases where no date was provided?

Example https://registry-api.gbif.org/grscicoll/institution/e0cd510a-a05e-4a39-b00b-6ebb4cb04aeb

**Comment by marcos-lg** [comment]
Changed to `null` in the DB. The institution had a wrong founding date because IH is returning 0 as `dateFounded`
