### ISSUE TITLE
GrSciColl performance on search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#446]
I find that the institution search is quite slow for 8K items

https://api.gbif.org/v1/grscicoll/institution?q=e
for example took 1.85 seconds to start sending data.

https://api.gbif.org/v1/grscicoll/institution?q=bmnh
took over 3 seconds

**Comment by marcos-lg** [comment]
The grscicoll persons were removed so the searches should a bit faster now.

**Comment by MortenHofft** [comment]
"query": {
    "q": "kew",
    "limit": 20,
    "offset": 0
  }

took  more than 12 seconds in uat. there were 2 results

**Comment by MattBlissett** [comment]
This is still very slow.

I think the contact person query still needs to be removed from the countCollections query, specifically in COLLECTIONS_FULLTEXT_SEARCH.

**Comment by marcos-lg** [comment]
Added a couple of indexes to make it faster. If this is not enough I'll have to remove the contacts from the full text search.
