### ISSUE TITLE
cannot search dataset by project id

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#45]
reported by @ahahn-gbif 

these 2 dataset both have a project identifier
http://api.gbif.org/v1/dataset/f46b1577-3ccc-494c-b8c8-89ad26457394 project_id:BID-AF2015-0004-NAC
http://api.gbif.org/v1/dataset/7fa4ed8c-e879-465f-acd2-2e65f398cc96 project_id: BID-AF2015-0069-SMA

But only one of them can be found by search
http://api.gbif.org/v1/dataset/search?project_id=BID-AF2015-0004-NAC
http://api.gbif.org/v1/dataset/search?project_id=BID-AF2015-0069-SMA

**Comment by MattBlissett** [comment]
The Varnish logs show that after the dataset was updated, it was no longer in the results (just going by the size, 8048B to 77B).

```
130.225.43.8 - - [10/Apr/2018:09:48:21 +0200] "GET http://api.gbif.org/v1/dataset/search/?limit=500&projectId=BID-AF2015-0069-SMA&hl=true HTTP/1.1" 200 8048 "-" "GBIF-portal"
130.225.43.8 - - [10/Apr/2018:11:07:50 +0200] "GET http://api.gbif.org/v1/dataset/search/?limit=500&projectId=BID-AF2015-0069-SMA&hl=true HTTP/1.1" 200 77 "-" "GBIF-portal"
```

**Comment by ManonGros** [comment]
I found a somewhat related issue, a dataset with the correct project identifier BID-CA2016-0006-REG that does not link to the project page

the following dataset https://www.gbif.org/dataset/c6449c7b-775c-41b1-93cd-9fde78f0af10 
can be accessed from the project page https://www.gbif.org/project/83239/improving-biodiversity-data-accessibility-in-trinidad-and-tobago-barbados-and-suriname#datasets

but the project page cannot be accessed from the dataset

**Comment by MortenHofft** [comment]
@ManonGros 
Thanks - This is unrelated, but I can see that it appears related. This has to do with the project description being so brief. It doesn't show the project tab if there isn't really any data provided from the publisher. It assumes that at least a study area description, a design description or funding is filled. I have extended that to accept as little as an abstract now: https://github.com/gbif/portal16/commit/791875c1e76af10c5337d6b427bfa2c51e6ba1fe

**Comment by fmendezh** [comment]
Closing this issue, it seems to be related to deleted datasets and project descriptions
