### ISSUE TITLE
Add country filter to search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#451]
Prompted by https://github.com/gbif/hp-uk-collections/issues/3

@marcos-lg adding a country filter to suggests sounds like something that would make a lot of sense to have.

Something like `https://api.gbif.org/v1/grscicoll/search?entityType=INSTITUTION&displayOnNHCPortal=true&limit=8&q=danish&country=DK`

similar to how we can filter search results in `https://registry-api.gbif.org/grscicoll/collection?q=&limit=25&offset=0&country=DZ`

**Comment by marcos-lg** [comment]
Deployed to PROD
