### ISSUE TITLE
GDPR Notifications

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#46]
GBIF will be making changes to support the [GDPR legislation](https://www.eugdpr.org/) coming into effect on 25th May 2018.

In summary GBIF will be:

1. Providing an information page about how user information is treated and how a request for removal can be made
2. Sending a notification to all email addresses associated with registry entities that their information is being used.  This email will contain a link to the information page and should include some sample URLs (not all URLs) where the user can see examples

The registry needs to be modified as follows:

1. Add a table containing the `email_address` (primary key), `version` (primary key) *, `timestamp_sent`, `context` (e.g. `{"datasets":[uuid1,uuid2]}, "organizations": [uuid3]})`
2. A web service that allows get and update on the (compound) primary key (`admin authorization`) 
3. A hook on each entity update (see the `BaseNetworkEntity.create()` and `BaseNetworkEntity.update()`) that checks if any contact has not notified.  If not, a message is sent to Rabbit
4. A registry CLI will subscribe to the changes and send an email (suggest this be templated and include some sample URLs the recipient can visit - e.g. a dataset detail page. Once sent it updates the DB table through the API. Given this has race conditions and is asynchronous, it should perhaps do another check before sending by reading the table to see if another thread has updated the table.
5. A bash script or similar needs to be able to do a one time mail shot by reading a CSV/TSV file containing email + context, and then sending requests to Rabbit.  This is to ensure we can easily extract all existing contacts and then mail them once. This probably needs to be rate limited to avoid GBIF getting marked as a SPAM deliverer.

(Note: I propose including a version in case we need to send more than 1 message to each email address should future requirements come in)

**Comment by timrobertson100** [comment]
Relates to https://github.com/gbif/portal16/issues/759

**Comment by MattBlissett** [comment]
Marcos implemented this (or most of it?) in the branch [gdpr-notifications](https://github.com/gbif/registry/tree/gdpr-notifications). It is ready if/when needed.
