### ISSUE TITLE
GRSciColl - IH synchronitzation - change default name of collections

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#460]
So far when a new collection is created by default during synchronisation with IH, the default name is "Herbarium".
We got some feedback that naming everything "herbarium" makes it difficult to curate the information.

I propose that by default, the collection name should be "Herbarium - INSTITUTION_TITLE". For example, "Herbarium - Tarleton State University".

Ideally, we should also rename all the collection entries with the title "Herbarium" to "Herbarium - INSTITUTION_TITLE". It will be important not to change any other collection title.

@marcos-lg Would that be feasible?

**Comment by marcos-lg** [comment]
Deployed to PROD
