### ISSUE TITLE
Cannot access https://registry.gbif.org/institution/35a10a88-03b2-48db-8284-6566a132de33

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#470]
Not sure why, I was about to report and error about applying a suggestion for this institution (see screenshot below). But now I cannot even access the institution page: https://registry.gbif.org/institution/35a10a88-03b2-48db-8284-6566a132de33

<img width="428" alt="Screenshot 2023-02-01 at 09 13 27" src="https://user-images.githubusercontent.com/7677271/216630729-30c54fec-3df9-49e3-9734-5687ebf876d0.png">

**Comment by ManonGros** [comment]
Same problem here: https://registry.gbif.org/collection/bf6ef975-8cde-47ea-9037-9ca01d8d61ea

**Comment by marcos-lg** [comment]
Fixed
