### ISSUE TITLE
Add identifier type to GRSciColl - WIKIDATA

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#471]
For example, it would be nice to have this entry https://registry.gbif.org/institution/9250e18c-ccb3-4e06-8bcc-2298250cefe7/identifier linked to its Wikidata entry https://www.wikidata.org/wiki/Q1528756 with only the wikidata identifier

**Comment by dshorthouse** [comment]
Suggestion: Make use of the wikidata entity URI for this purpose in the form http://www.wikidata.org/entity/Q1528756.

**Comment by marcos-lg** [comment]
Deployed to prod.

**Comment by ManonGros** [comment]
Thanks Marcos! That allowed me to import Wikidata identifier for about 1700 institution entries!
