### ISSUE TITLE
GRSciColl - error when trying to access suggestion list for institution

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#472]
This URL: https://registry.gbif.org/suggestions/institutions?status=PENDING
gives me the following message:
<img width="1459" alt="Screenshot 2023-02-07 at 10 26 10" src="https://user-images.githubusercontent.com/7677271/217205146-f169f7d9-5528-47d5-95df-0074b4f11b3c.png">

**Comment by marcos-lg** [comment]
Fixed
