### ISSUE TITLE
GRSciColl - dataset metadata synchronisation - exclude contacts with type "programmer" and "metadata author"

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#473]
I have been linking a lot more datasets to GRSciColl entries (as master source) lately. And it is a bit odd to have "programmers" (see examples here: https://registry.gbif.org/dataset/d39570b9-2972-4dbb-b41f-6826823176ae/contact) become collection contacts. The programmers definitely contributed to making the data available on GBIF but I don't think it makes sense to show them as collection contacts. The same goes for metadata authors.
If this is at all possible, would it be possible to exclude those contacts from making it to GRSciColl?

**Comment by marcos-lg** [comment]
Deployed to PROD. The entities with contacts of those types have also been updated.
