### ISSUE TITLE
DWCA_TO_VERBATIM No count provided

### ISSUE THREAD

**Issue by dshorthouse** [gbif/registry#474]
This dataset https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5/ingestion-history has had a significant drop in the number of records indexed because of hiccup in `basisOfRecord`, which apparently has since been fixed. However, ingestion appears to have stalled. This is a bottleneck for a data refresh in Bionomia. @TheMereKat

**Comment by themerekat** [comment]
The Darwin Core Archive looks fine from our end (is greater than 400 records), so I'm not sure what the problem is. Thanks for persisting, @dshorthouse !

**Comment by ManonGros** [comment]
Thanks for the notification @dshorthouse, I restarted the ingestion and it worked this time.

**Comment by themerekat** [comment]
Yay, thank you @ManonGros !
