### ISSUE TITLE
Handling batches of collections

### ISSUE THREAD

**Issue by fmendezh** [gbif/registry#475]
Some data publishers maintain their collections in specialised systems, that information is periodically updated and maintain by their staff. It should be desirable to extend the Grscicoll API to support the creation and/or update of collections data. 
Additionally, a tool that allows to compare a list of collections against the currently registered ones.

Some examples of this are:

- Living Atlases maintain some information about collections that worth considering sincronise against GRSciColl data,  Living Atlases expose that information through API services: [https://docs.ala.org.au/openapi/index.html?urls.primaryName=metadata](https://docs.ala.org.au/openapi/index.html?urls.primaryName=metadata)  and [https://collections.ala.org.au/ws/](https://collections.ala.org.au/ws/) (old documentation)
- Collections management systems could easily integrate through API services (similarly how Index Herbarorium is handled) to keep in synchronisation collections data (the GBIF-Chile platform and Specify are examples of this escenario).

**Comment by ManonGros** [comment]
Side note, this is something I have been writing scripts for like this one for the Swiss Node: 
[import_swiss_collections_grscicoll.py.zip](https://github.com/gbif/registry/files/10791243/import_swiss_collections_grscicoll.py.zip)

It would be great if this could be something more flexible and available to more people!

**Comment by marcos-lg** [comment]
Deployed to UAT so it can be tested if someone wants to.

There is a small documentation here https://github.com/gbif/registry/blob/dev/docs/grscicoll_batches.md

**Comment by marcos-lg** [comment]
Deployed to PROD.
