### ISSUE TITLE
GRSciColl - Can't apply suggestion change for a contact with research_ID

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#476]
This is the suggestion I can't apply: https://registry.gbif.org/collection/bf6ef975-8cde-47ea-9037-9ca01d8d61ea?suggestionId=796
And this isn't the first time I am not able to apply this type of suggestion. This is the error message I get:
<img width="415" alt="Screenshot 2023-02-23 at 11 26 28" src="https://user-images.githubusercontent.com/7677271/220881363-f9f74b7d-80b7-440a-8968-5254c12bf2b9.png">

What are the rules for this type of ID? Could they be loosened a bit?

@marcos-lg

**Comment by marcos-lg** [comment]
The rules are here, it has to follow one of those 2 patterns https://github.com/gbif/gbif-api/blob/c1395b375bfd421bb5120b1312a16ea2d1bbc041/src/main/java/org/gbif/api/util/validators/identifierschemes/ResearcherIdValidator.java#L21

But I see now that there are other patterns: https://www.webofscience.com/wos/author/record/AAK-3007-2021

I couldn't find a place where they describe the format of these identifiers, do you know any?

**Comment by ManonGros** [comment]
According to wikidata, the pattern is `[A-Z]{1,3}-\d{4}-(19|20)\d\d` (https://www.wikidata.org/wiki/Property:P1053)
Would that be implementable?

**Comment by marcos-lg** [comment]
Deployed to production
