### ISSUE TITLE
Authors missing in citation

### ISSUE THREAD

**Issue by peterdesmet** [gbif/registry#480]
A number of our datasets don’t include the people that are originators as authors in the citation, e.g. https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a7b3c7a3c7b4#citation:

> Research Institute for Nature and Forest (INBO): HG_OOSTENDE - Herring gulls (Larus argentatus, Laridae) breeding at the southern North Sea coast (Belgium) [subsampled representation] https://doi.org/10.5281/zenodo.6594838 accessed via GBIF.org on 2023-04-25.

This in contrast with most of our other datasets, e.g. https://www.gbif.org/dataset/b7ee2a4d-8e10-410f-a951-a7f032678ffe#citation:

> Cartuyvels E, Brosens D, Adriaens T, Baert K, Desmet P, Devisscher S, Neukermans A, Stuyck J, Huysentruyt F (2021). Muskrat captures in Flanders, Belgium. Version 1.9. Research Institute for Nature and Forest (INBO). Occurrence dataset https://doi.org/10.15468/pequ4z accessed via GBIF.org on 2023-04-25.

What could be causing this? Is because we reuse the Zenodo DOI (intentional)?

**Comment by MattBlissett** [comment]
Hi Peter,

By agreement with OBIS, datasets in the [OBIS network]() use the citation provided by the publisher in the metadata (i.e. EML).  See https://github.com/gbif/registry/issues/43 for the background on this.

https://ipt.inbo.be/eml.do?r=hg_oostende doesn't include a citation, but I think if you create one it will start showing on GBIF.org.
