### ISSUE TITLE
Notification for GRSciColl update suggestion

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#484]
When a user makes a suggestion update on GRSciColl, could we send an email directly to the person with the permission to apply those suggestion (institution editor if there is one, country mediator if there is one and scientific-collections@gbif.org for everything else and in CC)?
We now have a lot more mediators than we used to and it would make my life easier if I didn’t have to look them up and forward emails every time I get a suggestion.

We could have a hierarchy, for example, if someone has specific permissions to the institution, then they could have priority over the mediator for the whole country. If there are more than 1 persons with permissions to the institution then we would send the notification to all of them.

We might want to adjust the text in the email to remind people of how it works.
I suggest adding at the end of the email something like:
> You can review and apply or discard the suggestion by clicking on the link above and logging in with your GBIF credentials. Please contact scientific-collections@gbif.org if you encounter any issue or have any question. Thanks!

**Comment by marcos-lg** [comment]
deployed to prod

**Comment by marcos-lg** [comment]
Reopening: I forgot to add the text specified in the issue at the end of the email.
