### ISSUE TITLE
GRSciColl - IH contacts can be retired and still be displayed as contact

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#485]
Some collection entrie(s) is/are linked to IH and contain(s) contacts who no longer work at the institution.
See for example this update suggestion: https://registry.gbif.org/collection/d22c2d2c-43d9-4a66-8b7a-01fc7d4bc889?suggestionId=915
The problem is that the contact still exist on the IH entry https://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124988 but there is a status that says "Retired and no longer associated".

Could we only keep the contacts that are "Active" like this one https://sweetgum.nybg.org/science/ih/person-details/?irn=248436?
Otherwise, would it make sense to have the status somewhere in the contacts?
What do you think @marcos-lg

**Comment by marcos-lg** [comment]
I just released a new version with a change to only sync the `Active` contacts. In the next sync we should see the changes in GRSciColl.
