### ISSUE TITLE
More information on download pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#486]
See https://github.com/gbif/portal16/issues/1860

**More metrics**
More metrics on https://api.gbif.org/v1/occurrence/download/0011797-180412121330197
just like that says `"numberDatasets": 3666`, it could say `numberOrganizations` and `numberCountries`

AND if we think it makes sense we could also add `numberInstitutions` and `numberCollections`, but those are more dynamic over time as our matching is improved with GrSciColl. 

**Add countryCode to dataset list**
Extend `https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/datasets` with countryCode for the entries. E.g.
```json
{
  "downloadKey": "0011797-180412121330197",
  "datasetKey": "fea77396-7b26-44cb-8580-aefadc8db276",
  "datasetTitle": "The cryptogamy collection (PC) at the Herbarium of the Muséum national d'Histoire Naturelle (MNHN - Paris)",
  "datasetDOI": "10.15468/mywiem",
  "datasetCitation": "MNHN - Museum national d'Histoire naturelle (2018). The cryptogamy collection (PC) at the Herbarium of the Muséum national d'Histoire Naturelle (MNHN - Paris). Version 70.61. Occurrence Dataset https://doi.org/10.15468/mywiem accessed via GBIF.org on 2018-05-07.",
  "numberRecords": 271292,
  "countryCode": "DE" <======
},
```

**Add list of publisher**
A new endpoint like `https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/datasets` but for publishers. e.g.
`https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/organizations`

The only information i can come up with for the publisher entries is
```json
{
  "downloadKey": "0011797-180412121330197",
  "organizationKey": "fea77396-7b26-44cb-8580-aefadc8db276",
  "organizationTitle": "Some publisher",
  "countryCode": "DE",
  "numberRecords": 8271292
},
```

**Add list of countries**
A new endpoint like `https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/datasets` but for countries. e.g.
`https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/countries`

The only information I can come up with
```json
{
  "downloadKey": "0011797-180412121330197",
  "countryCode": "DE",
  "numberRecords": 18271292
},
```

**Add ways to sort and filter above**
For dataset and publisher lists, add sort and search filters:
`sortBy=datasetTitle|publisherTitle|countryCode|recordCount`
`sortOrder=ASC`
`datasetTitle=abcd` (only applied to dataset list of course)
`organizationTitle=efgh`

**Comment by kcopas** [comment]
Just to flag this: if it sits in the queue, a current discussion with NSF about the possibility of adding standardized funding references to the citation graph could warrant inclusion of an additional feature request here—something along the lines of a list of funders and a `numberFunder` element.

**Comment by marcos-lg** [comment]
Deployed to PROD.

This endpoint now includes the number of organizations and countries: https://api.gbif.org/v1/occurrence/download/0011797-180412121330197

The `datasets` endpoint now includes the `publishingCountryCode`:
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/datasets

Added 2 new endpoints:
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/organizations
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/countries

Added the filter params too, e.g.:
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/datasets?datasetTitle=CPAP%20-%20Herb%C3%A1rio%20CPAP
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/organizations?sortBy=ORGANIZATION_TITLE&sortOrder=DESC
https://api.gbif.org/v1/occurrence/download/0011797-180412121330197/countries?sortBy=RECORD_COUNT&sortOrder=DESC

The values for the `sortBy` param can be found here:
https://api.gbif.org/v1/enumeration/basic/DatasetUsageSortField
https://api.gbif.org/v1/enumeration/basic/OrganizationUsageSortField
https://api.gbif.org/v1/enumeration/basic/CountryUsageSortField

@kcopas if you want to add more info in the future feel free to reopen this issue or create a new one.
