### ISSUE TITLE
Expose changed datasets since a given time

### ISSUE THREAD

**Issue by mdoering** [gbif/registry#489]
Expose only the changed datasets in the API since a given point in time to allow efficient syncing with the registry.
The modified date is already a search parameter and in the search index, but you cannot do a larger/smaller than query, only equals.

Checklistbank currently syncs with the registry rather inefficiently, crawling through all checklist datasets incl. their host & publisher several times a day even though most are unchanged.

**Comment by marcos-lg** [comment]
@mdoering how do you get the datasets in checklistbank? do you use the DatasetClient? just to know what methods I should change since we have several methods to list datasets

**Comment by mdoering** [comment]
no, I have my own simple client that pages through the API with `v1/dataset?type=checklist` and looks up publishers and hosts as needed by their key. I can adjust to any method really, its very isolated.

**Comment by mdoering** [comment]
Nice, many thanks!
It even works with just a year: https://api.gbif.org/v1/dataset?modified=2021
