### ISSUE TITLE
What happens when records is deleted in IH

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#492]
This entry is no longer in Index Herbariorum. It looks like it was added twice on mistake and one of them subsequently deleted.
https://registry.gbif.org/institution/e32edff9-164d-4fb7-babe-d3df12da6a47

But it still appears in our system. Do we have a way to detect such cases? It might be wrong to just delete it in our end as well, but it also seems silly not to review the change

**Comment by marcos-lg** [comment]
The IH sync app doesn't check for these cases but it could. So if there is an entity in GrSciColl whose master source is IH and IH doesn't return it in the API call it could delete the master source in GrSciColl.

**Comment by ManonGros** [comment]
I think it would be helpful if there was a way to remove institutions that disappeared from IH.
I have approved your merging suggestion Morten (I suspect Cat didn't really know what to do with that suggestion). I am unassigning myself now.

**Comment by MortenHofft** [comment]
So what is the procedure that you would like to see @ManonGros ?

Automatically generate a suggestion to delete it? Create a Github issue? Just delete it?

**Comment by ManonGros** [comment]
Good question. Since the example above was an accidental duplicate, the ideal response was to merge the duplicates together. In that case, a deletion wouldn't be ideal. Perhaps an issue in this repo would be best? https://github.com/gbif/collections-sync/issues

**Comment by marcos-lg** [comment]
@ManonGros you mean the IH sync app to detect it automatically in every sync and create an issue in that repo, right? (it's doable)

**Comment by ManonGros** [comment]
Yes that's what I mean, that would be the best I think.

**Comment by marcos-lg** [comment]
Done and deployed.
