### ISSUE TITLE
Institutions API support for multiple countries

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#493]
For the Tettris project, they wish to show institutions in Europe.
That isn't possible with the current API as we cannot filter on multiple countries 
e.g. `https://api.gbif.org/v1/grscicoll/institution?country=SE&country=DK` will only show institutions in `SE`

Same issue for collections

**Comment by marcos-lg** [comment]
Deployed to PROD.

Added multiple countries and `gbifRegion` param:

https://api.gbif.org/v1/grscicoll/institution?country=DK&country=ES&gbifRegion=AFRICA

**Comment by MortenHofft** [comment]
The behaviour of that combination is odd I find
https://api.gbif.org/v1/grscicoll/institution?country=DK&country=ES&gbifRegion=AFRICA
There should be no results that match that I would think. Both Africa and denmark should be zero. normally when we add params of different type it is an `AND` and multiple of the same type is `OR`. So that would read as `(country=DK OR country=ES) AND region=AFRICA` but the results shows that it is all `OR`

**Comment by marcos-lg** [comment]
I did it as a an `OR` because `gbifRegion` is a list of countries under the hood and it's a convenience not to list all the countries one by one. This means that both parameters(`gbifRegion` and `country`) actually query the same field. Also, I think it's more useful this way to be able to query more combinations of countries in an easier way.

**Comment by mike-podolskiy90** [comment]
I think what Morten suggests is more intuitive behaviour.

**Comment by MattBlissett** [comment]
I can see the convenience, but I'm also worried about the inconsistency it introduces.

We've discussed extending the V1 APIs to support negation, and that would be made more complicated by this.
