### ISSUE TITLE
Institutions API with maps

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#494]
I've recently been trying to add maps to institution search, but the performance isn't great. I have to cache data in a proxy service, that then does some of the filtering for the largest queries. Else it can take 20 seconds to see a map as I have to page through all institutions.
Continuing to do so isn't impossible, but it is extra work and as new search filters are added, it has to be reflected in that proxy service. We could also consider using e.g. elastic search and generate map tiles via ES.

**Comment by marcos-lg** [comment]
what data from the institutions do you need for the maps? I could create an endpoint that returns that data only and it should be faster.

**Comment by MortenHofft** [comment]
We could add a `hasCoordinate` filter. And then return lat, lon, key, name?

**Comment by marcos-lg** [comment]
I agreed with @MortenHofft to return the institutions in geojson format.

**Comment by MortenHofft** [comment]
The endpoint will accept the same filters as search. And will for now only return the properties key + name

**Comment by marcos-lg** [comment]
Deployed to PROD. 

E.g: 
https://api.gbif.org/v1/grscicoll/institution/geojson
https://api.gbif.org/v1/grscicoll/institution/geojson?country=DK
