### ISSUE TITLE
Suggest shows changes that didn't take place

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#495]
E.g. https://registry.gbif.org/institution/2550d5ba-c363-4439-8517-267946728919?suggestionId=1043

Shows that the address has changed. It hasn't in the user input or the posted data. 
But somewhere the address is trimmed of trailing spaces, and so the suggestion is marked as being about the address.
It is confusing for both suggester and reviewer.

Could we fix that? I suppose the simplest way is to remove spaces in the database and not wait until someone modifies an entry

**Comment by MortenHofft** [comment]
Another example is
https://registry-api.gbif.org/grscicoll/institution/changeSuggestion/1045
but this time latitude, longitude is listed as having changed. There is no difference to be seen.
It makes reviewing confusing

```json
changes": [
{
"field": "latitude",
"suggested": 35.1801,
"previous": 35.1801,
"created": "2023-06-14T04:49:59.306+00:00",
"overwritten": false,
"outdated": false
},
{
"field": "homepage",
"previous": "http://www.mpcer.nau.edu/cpbc",
"created": "2023-06-14T04:49:59.306+00:00",
"overwritten": false,
"outdated": false
},
{
"field": "longitude",
"suggested": -111.655,
"previous": -111.655,
"created": "2023-06-14T04:49:59.306+00:00",
"overwritten": false,
"outdated": false
}
]
```

**Comment by marcos-lg** [comment]
Fixed and deployed to prod.
