### ISSUE TITLE
GRSciColl lookup - map occurrence to institutionCode regardless of the ownerInstitutionCode

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#496]
This was brought up during our Technical Support Hour for Nodes.
The occurrences should be linked to the institution based on the institutionCode even when it differs from the ownerInstitutionCode.

I think it makes sense to keep the flag (as a warning) but link the occurrences.

**Comment by marcos-lg** [comment]
Deployed to production.

Datasets have to be reinterpreted to get this change.

**Comment by marcos-lg** [comment]
All datasets have been reinterpreted.
