### ISSUE TITLE
Add city and state to export to /institution/export 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#501]
Requested by Kirk, Smithsonian who - with some assistance - is using the spreadsheet export function from the API

**Comment by marcos-lg** [comment]
They are already included but they are concatenated with the other fields of the address. Do they need them in a separate field?

**Comment by timrobertson100** [comment]
Yeah. I was answering a helpdesk request. [This is the procedure](https://gist.github.com/timrobertson100/52b2086609ec89737a1bcbb37bd304a7) I ended up with.

I think the motivation was to be able to get a _simple_ overview of what was available, so it could be scanned for obvious missing things.

**Comment by ManonGros** [comment]
maybe we could have the city both in the address and in a separate field (for filtering)?

**Comment by marcos-lg** [comment]
Deployed to PROD.

Added the `city` and `province` columns.
