### ISSUE TITLE
Add occurrence counts to institutions and collections

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#502]
Could/should we add occurrence counts to institutions and collections?

It would enable searching collections that have e.g. >100K specimens, but none in GBIF.
Or dashboards on state of digitized and shared specimens. etc.

It is expensive to do so live, but even a weekly batch job would probably be fine I imagine. And we could show the counts as approximate in the UI search table

**Comment by MortenHofft** [comment]
Additional idea - having a type specimen count as well. A bit more unclear what the criteria would be and what to use it for, but might be intersting

**Comment by ManonGros** [comment]
Related to this one: https://github.com/gbif/registry/issues/497

**Comment by marcos-lg** [comment]
A type specimen would require a bit more work but we can still do it if you guys think it's useful. 

The filter would be that the basisOfRecord is `PRESERVED_SPECIMEN`,`FOSSIL_SPECIMEN` or `LIVING_SPECIMEN`?

**Comment by MattBlissett** [comment]
Type specimens are those where typeStatus is set, but not NOTATYPE ("Not a type"): 

https://www.gbif.org/occurrence/search?type_status=TYPE&type_status=TYPE_SPECIES&type_status=TYPE_GENUS&type_status=ALLOLECTOTYPE&type_status=ALLONEOTYPE&type_status=ALLOTYPE&type_status=COTYPE&type_status=EPITYPE&type_status=EXEPITYPE&type_status=EXHOLOTYPE&type_status=EXISOTYPE&type_status=EXLECTOTYPE&type_status=EXNEOTYPE&type_status=EXPARATYPE&type_status=EXSYNTYPE&type_status=EXTYPE&type_status=HAPANTOTYPE&type_status=HOLOTYPE&type_status=ICONOTYPE&type_status=ISOLECTOTYPE&type_status=ISOPARATYPE&type_status=ISONEOTYPE&type_status=ISOSYNTYPE&type_status=ISOTYPE&type_status=LECTOTYPE&type_status=NEOTYPE&type_status=PARALECTOTYPE&type_status=PARANEOTYPE&type_status=PARATYPE&type_status=PLASTOHOLOTYPE&type_status=PLASTOISOTYPE&type_status=PLASTOLECTOTYPE&type_status=PLASTONEOTYPE&type_status=PLASTOPARATYPE&type_status=PLASTOSYNTYPE&type_status=PLASTOTYPE&type_status=SECONDARYTYPE&type_status=SUPPLEMENTARYTYPE&type_status=SYNTYPE&type_status=TOPOTYPE&type_status=ORIGINALMATERIAL

**Comment by marcos-lg** [comment]
Deployed to PROD.

The search by the counts works as a range param, e.g.:
https://api.gbif.org/v1/grscicoll/institution?occurrenceCount=100,*
https://api.gbif.org/v1/grscicoll/institution?occurrenceCount=1,100
https://api.gbif.org/v1/grscicoll/institution?occurrenceCount=66

The same is for collections and for the `typeSpecimenCount`param.

The counts are updated [every day from Monday to Friday](https://github.com/gbif/registry/blob/eaaede07e88a1b99dd75bd33aacbd44db4fb4d63/registry-ws/src/main/java/org/gbif/registry/ws/resources/scheduled/GRSciCollCountsUpdaterService.java#L62)
