### ISSUE TITLE
GRSciColl - add identifier type NCBI_BIOCOLLECTION

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#512]
I would like to have an identifier type for NCBI_BIOCOLLECTION identifiers, the ones that are here: https://ftp.ncbi.nih.gov/pub/taxonomy/biocollections/Institution_codes.txt. Since they are only integer it would make sense to have a type to put it back in the context.

**Comment by marcos-lg** [comment]
Deployed to prod.
