### ISSUE TITLE
Should we clean up EML more?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#515]
From https://api.gbif-uat.org/v1/dataset/03376f38-8456-42c2-91c3-cd77299b3cae
```json
{
  "samplingDescription": {
    "methodSteps": [
      null
    ]
  }
}
```

Entries like these are a pain to work with because you have to do a lot of tests to figure out if it is relevant to show a given section.
It also isn't clear to me when we wrap(wrap(wrap(nulls))).

We do [not for example](https://api.gbif-uat.org/v1/dataset/34a96ebe-e51c-4222-9d08-5c2043c39dec) do

```json
"geographicCoverages": [
  {
     "boundingBox": {
      "minLatitude": null
    }
  }
]
```

Should we consider cleaning this in the API layer?

**Comment by ahakanzn** [comment]
closed in favor of #416
