### ISSUE TITLE
UI related metadata in the registry

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#516]
Should we consider more UI related metadata in the registry?

Specifically adding an image field (and image license) to collections to allow more splashy collection pages.
<img width="1656" alt="Screenshot 2022-10-03 at 15 37 19" src="https://github.com/gbif/registry/assets/6759267/ec8e3ad6-8945-4151-a3f5-27fa9b884ccb">

ping @ManonGros

**Comment by ManonGros** [comment]
Yes, I would love that!
Something like "featured image" or along those lines. Thanks for opening the issue! we might have to leave it open until we review all the GRSciColl fields though.

**Comment by marcos-lg** [comment]
I'm closing this issue since this is covered here: https://github.com/gbif/registry/issues/552
