### ISSUE TITLE
GRSciColl default sorting for collections and institution based on number of specimens

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#517]
Right now, the latest GRSciColl entries are displayed first on our website/API.

ideally, we would like to show collections (and institutions) on the new GRSciColl website that have interesting content. The number of specimens is an arbitrary field to use but it allows to show by default entries that "usually" have more content. https://grscicoll.hp.gbif-staging.org/collection/search?numberSpecimens=1%2C1000000

@marcos-lg would it be possible to use the number of specimens to sort entries by default?

**Comment by MortenHofft** [comment]
So this would be the sort order as lo g as there is no `q` param Marcos

**Comment by marcos-lg** [comment]
Wouldn't it be better to add a `sortBy` parameter and keep the default as it is?

**Comment by MortenHofft** [comment]
sounds fine

**Comment by marcos-lg** [comment]
Deployed to production.

E.g.: https://api.gbif.org/v1/grscicoll/institution?sortBy=NUMBER_SPECIMENS&sortOrder=DESC

The values for the enums are here:
- https://api.gbif.org/v1/enumeration/basic/SortOrder
- https://api.gbif.org/v1/enumeration/basic/CollectionsSortField
