### ISSUE TITLE
Add option to omit "NOT MODIFIED" in dataset ingestion

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#518]
to support https://github.com/gbif/registry-console/issues/545

https://registry-api.gbif.org/ingestion/history/c1e31227-6595-4797-b75a-d9d9f75e4cca?limit=10
Add an option to omit NOT_MODIFIED.
One implementation of that could be to support filtering by finishReason? `finishReason=NORMAL&finishReason=NOT_MODIFIED`

**Comment by marcos-lg** [comment]
Deployed to production.

E.g.: https://api.gbif.org/v1/ingestion/history/c1e31227-6595-4797-b75a-d9d9f75e4cca?finishReason=NORMAL&finishReason=NOT_MODIFIED
