### ISSUE TITLE
discipline AND/OR

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#523]
https://api.gbif.org/v1/grscicoll/institution?limit=100&discipline=ARCHAEOLOGY&discipline=SPACE 3 results
https://api.gbif.org/v1/grscicoll/institution?limit=100&discipline=SPACE 5 results
https://api.gbif.org/v1/grscicoll/institution?limit=100&discipline=ARCHAEOLOGY 34 results

Looks like discipline is and AND unlike our normal API

**Comment by MortenHofft** [comment]
I'm not sure what is most useful, but it is different from the other APIs

**Comment by MortenHofft** [comment]
Same goes for contenttype on collections

**Comment by marcos-lg** [comment]
I'll change them to be an OR.

**Comment by MortenHofft** [comment]
Same goes for preservationType on collections

**Comment by MortenHofft** [comment]
I would argue that everything within the same field should be OR. just like the other APIs

**Comment by ManonGros** [comment]
I agree, let's be consistent and use OR like all the other APIs

**Comment by marcos-lg** [comment]
Deployed to production.
