### ISSUE TITLE
GRSciColl lookup - URLs as institution and collection IDs - make sure it works with new website

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#527]
The new GRSciColl website will be made public in two weeks or so. From then on, people might use the URL for the new website as institution and collection ID.
@marcos-lg could you check that the lookup service will work with that?

Related issues:
https://github.com/gbif/registry/issues/410 and https://github.com/gbif/hp-grscicoll/issues/29

**Comment by marcos-lg** [comment]
Do we know how the urls of the new website will look like?

**Comment by ManonGros** [comment]
If we can use the base URL I am suggesting here: https://github.com/gbif/hp-grscicoll/issues/29
I assume a typical entry would look like https://scientific-collections.gbif.org/institution/1d808a7c-1f9e-4379-9616-edb749ecf10e

**Comment by marcos-lg** [comment]
I just checked and it already works with the URLs of the new website:

https://api.gbif.org/v1/grscicoll/lookup?institutionId=https://scientific-collections.gbif.org/institution/6ac3cc61-39d7-4e8e-bd51-f56ff91412ee
