### ISSUE TITLE
downloads: don't show nr of datasets until it is known

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#53]
the API expose a number that varies as the upload is being prepared. Is that intentional? It leads to this view, where 3 concurrent downloads of everything involve a different amount of datasets.

![screen shot 2018-06-23 at 10 11 14](https://user-images.githubusercontent.com/6759267/41807339-f7172afc-76cd-11e8-8334-257cdae2452b.png)

if the nr of datasets isn't known, perhaps it shouldn't be populated? or the tmp counter field called something else?

**Comment by fmendezh** [comment]
@aalbatross this should be fixed once we deploy https://github.com/gbif/registry/pull/58
