### ISSUE TITLE
Downloads Monitoring UI

### ISSUE THREAD

**Issue by fmendezh** [gbif/registry#532]
The occurrence download API exposes services that would allow to build a basic monitoring interface to perform basic operations and queries on dowloads:

1.  A paginated list of downloads filter by download status and source, being source a free text field provided by the user: `occurrence/download?status=&source=`
2.  See the detailed information of a download: `occurrence/download/{key}` and `occurrence/download/{prefix}/{suffix}` (doi).
3.  Cancel a running download: DELETE `occurrence/download/request/{key}`

**Comment by MortenHofft** [comment]
https://api.gbif-dev.org/v1/occurrence/download?_=1698063981994&status=RUNNING&limit=10&offset=10
returns

```json
{
    "offset": 10,
    "limit": 10,
    "endOfRecords": true,
    "count": 2,
    "results": []
}
```

that response doesn't make sense. it can't have 2 results a limit=10 and no results

**Comment by MortenHofft** [comment]
Will behave odd until https://github.com/gbif/occurrence/issues/322 is fixed

**Comment by MortenHofft** [comment]
I've added a basic version. It shows the list of downloads, allow pagination. You can view details, links to API and gbif.org. And delete running downloads.

It is only visible if logged in as registry admin

The url doesn't update, so you cannot send page 2 to anyone or store filters.

I'm happy to add more details and features, but then let me know what you need
