### ISSUE TITLE
Does search by identifier work? 

### ISSUE THREAD

**Issue by jhnwllr** [gbif/registry#537]
The tech-docs claim you can search for identifier 

identifier: An identifier such as a DOI or UUID.

But it seems like it doesn't work: 
https://api.gbif.org/v1/dataset/search?identifier=4fa7b334-ce0d-4e88-aaae-2e0c138d049e
https://api.gbif.org/v1/dataset/search?identifier=10.15468%2Figasai

This endpoint works 
https://api.gbif.org/v1/dataset/doi/10.15468/igasai

**Comment by MattBlissett** [comment]
Identifier search is like this: http://api.gbif.org/v1/dataset?identifier=168

There could be incorrect documentation for other bits of /dataset/search.

**Comment by marcos-lg** [comment]
Docs fixed.
