### ISSUE TITLE
Should dataset/search?country=US return nothing? 

### ISSUE THREAD

**Issue by jhnwllr** [gbif/registry#538]
From tech docs: 

country : The 2-letter country code (as per ISO-3166-1) of the country publishing the dataset.

https://api.gbif.org/v1/dataset/search?country=SE

```json 
{
  "offset": 0,
  "limit": 20,
  "endOfRecords": true,
  "count": 0,
  "results": [
    
  ],
  "facets": [
    
  ]
}

```

**Comment by MortenHofft** [comment]
publishingCountry
https://api.gbif.org/v1/dataset/search?publishingCountry=SE

**Comment by marcos-lg** [comment]
The `country` parameter has been replaced with `hostingCountry`(country of the installation) and `publishingCountry`(country of the organization). Therefore, `country` will be removed from the docs(only needs deployment, the change is done in the code already).

**Comment by MortenHofft** [comment]
is the `country` parameter new? removing a parameter in a versioned api isn't something we normally do. What did it do previously and are there any reason to remove it?

**Comment by marcos-lg** [comment]
I haven't changed anything in the API, just fixing the docs. Taking a look at the commit history the `country` parameter hasn't worked for the last 3 years at least. I don't know if it has ever worked or if it did why it was changed but at this point the most reasonable solution to me is to update the docs.

**Comment by MortenHofft** [comment]
Thanks - if it has been like this for 3 years I guess that is the most stable version we should stick with. 

If I remember correctly we used to have a country array that was provided by the publisher and referred to data coverage. But I might well remember wrong.

**Comment by marcos-lg** [comment]
> If I remember correctly we used to have a country array that was provided by the publisher and referred to data coverage. But I might well remember wrong. Similar to the decade field

I saw that in the code but it's been commented out and I don't know why. I think @fmendezh might know.

**Comment by marcos-lg** [comment]
docs fixed.
