### ISSUE TITLE
GRSciColl fields to discard - GRSciColl data schema review

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#545]
After processing the input we got during the review, here are the fields that we will discard and where to move the content.

| Entity type | field to discard | where to migrate the data |
| --- | --- | --- |
| collection | importantCollectors | will be replaced by a table when we implement roadmap item 2 (it will become a table of collection descriptors) |
| institution and collection | indexHerbariorumRecord (deployed to PROD) | no replacement |
| institution | geographicDescription (deployed to PROD) | could we add the content at the end of the existing description values? |
| institution | taxonomicDescription (deployed to PROD) | could we add the content at the end of the existing description values? |
| institution | citesPermitNumber (deployed to PROD) | make them into identifiers, see also https://github.com/gbif/registry/issues/407 |

**Comment by marcos-lg** [comment]
All the fields but the `importantCollectors` have been discarded and deployed to production.

I'll keep the issue open until we replace the `importantCollectors` with the collection descriptors and hence we can remove it from the api.

I also kept the DB columns of the discarded fields just in case. I will remove them at the end of the 2024.

**Comment by marcos-lg** [comment]
The `importantCollectors` field has also been removed and migrated to collection descriptors.
