### ISSUE TITLE
GRSciColl change how addresses are filled in and displayed - GRSciColl data schema review

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#546]
Right now we have four kinds of addresses:

- institution physical address
- institution mailing address
- collection physical address
- collection mailing address

Editors find it cumbersome to edit (especially when it repeats several times). Could we have a way for users to copy the addresses from the exiting ones in the institution or collection?

For example, if I am filling the mailing address for the collection, I would like to just have the same address as the physical one (either from the collection or from the institution). The information should be copied to facilitate filling the information.

**Comment by marcos-lg** [comment]
@ManonGros is this something we'd like to have in the API or just when using the UI?

**Comment by ManonGros** [comment]
@marcos-lg I don't have a preference, could you check with @MortenHofft what makes the most sense?

**Comment by ManonGros** [comment]
Thanks for the input Morten. The problem is that everyone agrees that four addresses are too many but no one agrees on which they think are the most important. The result being that different people care the most about different addresses but there is no consensus.
This is why I don't think we should remove the addresses, just improve the way we display them.

**Comment by ManonGros** [comment]
After discussion today, we will just have a UI update where people can choose to **copy** another address: either address from the institution or another address from the collection.

**Comment by MortenHofft** [comment]
We already state that the physical address doesn't need to be filled, as it is assumed it is the same if only mailing address is filled. Should that perhaps be more prominent?

**Comment by MortenHofft** [comment]
I just looked. Looks good. A few comments:
* It looks odd that the option is there even when there is no data. It just shows an empty popup. E.g. https://registry.gbif.org/collection/create
* It also fills addresses when the field is locked like in the case of IH. See for example https://registry.gbif.org/collection/231b166d-3a1b-4442-91c1-bb0e842c87ad
