### ISSUE TITLE
GRSciColl fields which should have multiple values - GRSciColl data schema review

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#550]
These fields should have multiple values.

| entityType | field |
| -- | -- |
| institution | type |
| institution | institutionalGovernance |
| institution | catalogURL |
| institution | apiURL |
| collection | catalogURL |
| collection | apiURL |

**Comment by marcos-lg** [comment]
The change in the collection's catalogURL implies a change in the iDigBio endpoint too, so the `collectionCatalogUrl` field becomes a list too. We need to let them know when we're planning to deploy these changes so they can adapt their site.

**Comment by ManonGros** [comment]
Yes good point, I have warned @CatChapman that this type of changes were coming. I am happy to send them an official email with the list of changes.

**Comment by marcos-lg** [comment]
I've been thinking that to make the transition smoother I'm gonna keep 2 fields at the beginning so the changes don't break their site, so we'll have:
````
"collection_catalog_url": "http://www.plantpath.cornell.edu/CUPpages/CUPsearch.aspx",
"collection_catalog_urls": [
"http://www.plantpath.cornell.edu/CUPpages/CUPsearch.aspx"
]
````

Once they they adapt their site I'll remove the `collection_catalog_url` field.

**Comment by MortenHofft** [comment]
The field name isn't `catalogURL` as stated in the issue but `catalogUrls`

**Comment by MortenHofft** [comment]
again. it isn't `apiURL` as stated above but `apiUrls`

**Comment by marcos-lg** [comment]
Deployed to production.
