### ISSUE TITLE
GRSciColl fields to add - GRSciColl data schema review

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#552]
These fields should be added to GRSciColl:

| entity | field | type | definition | notes |
| --- | --- | --- | -- | -- |
| collection | featuredImageURL | URL | URL to the image to be featured on the collection page, this image should be associated with a license. | see https://github.com/gbif/registry/issues/516 |
| collection | featuredImageLicense | License | the license associated with the image to be featured on the collection page. | see https://github.com/gbif/registry/issues/516 |
| institution | featuredImageURL | URL | URL to the image to be featured on the institution page, this image should be associated with a license. | see https://github.com/gbif/registry/issues/516 |
| institution | featuredImageLicense | License | the license associated with the image to be featured on the institution page. | see https://github.com/gbif/registry/issues/516 |
| collection | temporalCoverage | Free text field | Temporal scope or focus of the collection. This free text field can be used to describe both the collection date ranges as well as the geological time group(s) of the collection objects in the context of paleontological collections | Some additional data can be provided in collection descriptors, this is meant to capture high level information  |

**Comment by MortenHofft** [comment]
Seems wrong that one can enter unsopprted as a license

**Comment by MortenHofft** [comment]
updating featuredImageURL doesn't work. the data is not updated with any value

**Comment by marcos-lg** [comment]
Deployed to production.
