### ISSUE TITLE
Map GRSciColl schema to Latimer Core - GRSciColl data schema review

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#554]
Based on the mapping documented here: https://docs.google.com/spreadsheets/d/1DrBD8lCPhJQwXJs7R73sq9wvr6_2v2ee641RnbBjn3s/edit?usp=sharing

See the `Latimer Core mapping` tab.

Let me know if you have any question.

**Comment by ManonGros** [comment]
This "mapping" to Latimer Core should enable two things:

- access the GRSciColl data formatted as Latimer Core (as JSON)
- upload data to GRSciColl when formatted as Latimer Core (we would only take the data for which we have an equivalent field in GRSciColl)

**Comment by marcos-lg** [comment]
In order to make the updates of existing entities easier I added the UUIDs of the entities as identifiers and they are required to do an update of an existing entity, e.g.:

```
{
"identifierValue": "6b408a24-dc0e-451a-bba9-44ffd23a920a",
"identifierType": "Collection GRSciColl key"
}
```

The same for the collection contacts:

```
{
"identifierValue": "32406",
"identifierType": "Contact GRSciColl key"
}
```

**Comment by marcos-lg** [comment]
Deployed to production.
