### ISSUE TITLE
uuid used as creator name

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry#556]
I noticed that when you import GBIF datasets into the Zotero reference manager, some look a bit strange with uuids as the author names. This appears to be because of how we translate `originator` into `creators` - but shouldn’t the publisher name ("National Museum of Natural History, Luxembourg") be used as the `name` in this example (see below)…?

https://api.datacite.org/dois/10.15468/449gg9

```
            "creators": [
                {
                    "name": "75642970-F855-11dd-8235-B8a03c50a862",
                    "affiliation": [],
                    "nameIdentifiers": [
                        {
                            "schemeUri": "gbif.org",
                            "nameIdentifier": "75642970-f855-11dd-8235-b8a03c50a862",
                            "nameIdentifierScheme": "GBIF"
                        }
                    ]
                }
            ],
```

**Comment by CecSve** [comment]
I have come across examples where some dataset citations also throw in 'unknow' for authorship. Not sure why the UUID is not used in those cases. I will try to find an example.

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie, I'll have a look

**Comment by CecSve** [comment]
Also, this dataset has `Jeroen` as author although I do not see the name in the contacts for the dataset. I did not check the meta.xml file though: https://www.gbif.org/dataset/8a863029-f435-446a-821e-275f4f641165

**Comment by MattBlissett** [comment]
It is presumably using the creator of the dataset entity in the registry, which is either a username (uknbn, jeroen) or the UUID of an IPT installation registry entity.

**Comment by mike-podolskiy90** [comment]
Yes, I'm fixing it. I'll also find all datasets like that and update their DataCite metadata

**Comment by CecSve** [comment]
Thanks Matt. Yes, it looks like it is the `created by` in the registry metadata of the dataset. In both cases, it should be the publishing organization instead. Here it would work if the originator role was supplied as author (the last dataset citation works):
https://registry.gbif.org/dataset/a86201a4-fa20-44e5-ade2-68ea3563cfa8/contact
https://registry.gbif.org/dataset/8a863029-f435-446a-821e-275f4f641165/contact
https://registry.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f/contact

It would not work with Daniel's original example:
https://registry.gbif.org/dataset/9ed0adc4-0a7a-49df-9054-e26e9a7dbc8d/contact - here it is metadata author that would fit the citation.

**Comment by mike-podolskiy90** [comment]
I've deployed the fix so it won't be an issue for new datasets. Now need to update the existing ones

**Comment by mike-podolskiy90** [comment]
All affected datasets were updated
