### ISSUE TITLE
I cannot apply this GRSciColl suggestion: https://registry.gbif.org/collection/create?suggestionId=1672

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#567]
I am not sure if this is a registry or a UI issue.
When I click on the suggestion link. I am adding the institution to the suggested collection, then click on the apply button. The UI says that the suggestion was successfully applied but then when I look for the collection, I cannot find it.
In addition to that:
* I don't receive the email notification that the suggestion was applied
* The suggestion doesn't show that it was applied: https://registry.gbif.org/collection/create?suggestionId=1672
* My comment (the "Thanks!") seems to be added to the comment originally provided by the person made the suggestion

I am not sure what is happening.

**Comment by marcos-lg** [comment]
what is the institution that you want to add to the collection? so I can try and reproduce it.

**Comment by ManonGros** [comment]
Thanks @marcos-lg this should be the institution: https://registry.gbif.org/institution/765b040f-1c0d-4403-94c2-1585b47ab4b0

**Comment by marcos-lg** [comment]
It turns out that the suggestion contains an empty address and that fails when persisting it to the DB. I'm not sure how that happened but I added a check in the API to prevent it from happening again. The change is not deployed yet but I fixed this suggestion manually in the DB and applied it.

**Comment by marcos-lg** [comment]
The check is deployed to production.
