### ISSUE TITLE
GRSciColl add fields for featured image attributions

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#573]
We have already institution and collection fields for featured images (URL and licenses) https://github.com/gbif/registry/issues/552 but we need a free text field for attribution as well: `featuredImageAttribution` both for institution and collection.

**Comment by ManonGros** [comment]
Description of the field: Information about ownership, attribution, etc. of the featured image (free text). This value with be used to generate a suggested citation of the image.

**Comment by ahakanzn** [comment]
deployed to prod
