### ISSUE TITLE
Vocabulary editing interface - can't access vocabulary once I log in

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#578]
I would like to be able to edit some of the GRSciColl vocabulary. But once I log in the interface, I get an error 500. I am using Safari Version 17.5 (19618.2.12.11.6), see this video: 

https://github.com/gbif/registry-console/assets/7677271/5d94dbcd-68b6-416e-9bf0-e311f6460ba4

**Comment by MattBlissett** [comment]
As you are a REGISTRY_ADMIN you don't need the INVITED_TESTER role.

@marcos-lg, is the vocabulary service using the latest gbif-api and registry versions?

**Comment by marcos-lg** [comment]
>  is the vocabulary service using the latest gbif-api and registry versions?

Nope, it needs the gbif-api version to be updated

**Comment by marcos-lg** [comment]
just deployed to production the vocabulary-ws with the updated gbif-api version.
