### ISSUE TITLE
Allow non admin users to see list of downloads

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#588]
Prompted by https://github.com/gbif/portal16/issues/1936

https://api.gbif.org/v1/occurrence/download?status=PREPARING&status=RUNNING 
This endpoint currently require admin permissions. Probably because it contains user names and email.

Perhaps we could simply remove sensitive information like that? Similar to what we do for [individual downloads](https://api.gbif.org/v1/occurrence/download/0070950-240506114902167) where the public API do not expose usernames. But if you are an admin (or owner) you can see it.

To proceed with above issue we need to access the number of running downloads one way or another

**Comment by ahakanzn** [comment]
deployed to prod
https://api.gbif.org/v1/occurrence/download/count?status=PREPARING&status=RUNNING
