### ISSUE TITLE
arrays of nulls

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#590]
Nested empty objects and arrays of nulls is a real nuissance when using the APIs
Example from the dataset API
https://api.gbif.org/v1/dataset/768b23fb-7d73-41a1-b3e4-364fefd3c91b

```json
"samplingDescription": {
  "methodSteps": [
    null
  ]
},
```
Would it make sense to clean such entries in the API response?

**Comment by marcos-lg** [comment]
Duplicate of https://github.com/gbif/registry/issues/416

**Comment by MortenHofft** [comment]
close in favour of https://github.com/gbif/registry/issues/515
