### ISSUE TITLE
publisher geojson response

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#597]
We recently added this for institutions: the option to filter for records with latitude/longitude and to get the result as geojson. 
e.g. https://api.gbif.org/v1/grscicoll/institution/geojson?country=DE - it support all the same filters as plain search.

It could be nice to have the same option for publishers. It would enable us to do a publisher map and show it on publisher search. But also on a new variation of our network page that shows the size of the GBIF network
https://www.gbif.org/the-gbif-network

**Comment by marcos-lg** [comment]
It is deployed to prod.
