### ISSUE TITLE
Logo URL for an Institution is stuck in previous version

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/registry#601]
When we update a logo for an institution, we keep the same [URL](https://raw.githubusercontent.com/SIB-Colombia/logos/main/socio-SiB-cenicafe.png). But when we try to update it in the registry, it does not read the new version https://registry.gbif.org/organization/da583013-8a1b-4570-b0e4-c7cb25b2e7bf.

The same happens in the GBIF portal, it show just the old logo https://www.gbif.org/dataset/5fb6974e-55f0-43ce-b5e9-26e6cd1f4b12 even when the [IPT](https://doi.org/10.15472/017mzy) shows the new version.

We want to know if there is a recomendation for updating URLs

**Comment by marcos-lg** [comment]
I ping @MortenHofft

**Comment by MattBlissett** [comment]
We have a long cache on these images, as they frequently disappear.

I've cleared the cache for this one, so it is now showing the new image. Are there any others that have been updated?

**Comment by MortenHofft** [comment]
if you want to force update you could add a cache bust param in the registry? like `https://raw.githubusercontent.com/SIB-Colombia/logos/main/socio-SiB-cenicafe.png?version=2` 
It is either that, change the url completely or wait for the cache to be cleared. Or apparently there is also the option to tell Matt :)

**Comment by EstebanMH-SiB** [comment]
Thank you very much for your help! With all your options I think we can evaluate case by case when we can just wait to the cache to change or if we need a faster approach
