### ISSUE TITLE
MachineTag search for collection doesn't seem to work

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#615]
According to the documentation, this should work but it doesn't: https://api.gbif.org/v1/grscicoll/collection/search?machineTagNamespace=usda.gov (it gives me all the collections in GRSciColl).
However, this works: https://api.gbif.org/v1/grscicoll/collection?machineTagNamespace=usda.gov
as well as this https://api.gbif.org/v1/grscicoll/collection/export?machineTagNamespace=usda.gov

Would it be possible to make sure that collections and institutions can be searched by machineTags?

**Comment by marcos-lg** [comment]
Fixed in prod.
