### ISSUE TITLE
UI: paging for filtered results (e.g. organization, dataset) loses the filter

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry#616]
A filtered result (e.g. for "pending" organizations, or for "deleted" datasets) is only available on the first page of the result set. After moving to the next page, the filter is lost, meaning that a maximum of 100 entries is available. This makes it difficult to identify deleted datasets for "resurrection", since additional text filters cannot be combined with the "deleted" filter. For pending endorsements, the current list length is 90, also because "rejected" endorsements are included in the filter result. 

In the latter case, a more strict filter should help, as we would not expect more than 100 pending endorsements. In the case of datasets, it would help to have an option to explicitly include deleted dataset entries in the result of searches for a dataset name - not as the default, but as an option. Would that be possible?

![image](https://github.com/user-attachments/assets/9a36cc84-3e52-4971-871e-ea403f143b56)

**Comment by MortenHofft** [comment]
oops - i was a bit fast at closing this. It now keeps "deleted" state when paging. And free text search of deleted dataset worked already. Combining deleted and pending would require api changes

**Comment by ahahn-gbif** [comment]
Just to avoid a misunderstanding: pending and deleted would not need to be combined, as they concern different data areas / workflows. The combination of text filter and status filter works as desired now, I think this can be closed, indeed - thanks!
