### ISSUE TITLE
GRSciColl - add identifier type ISIL

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#617]
I was made aware of the existence of the International Standard Identifier for Libraries and Related  (ISIL) https://slks.dk/english/work-areas/libraries-and-literature/library-standards/isil which is used to catalogue a number of museums across the world.
I would like to be able to import data from ISIL as well as link museums to ISIL when the identifiers are available.

Here are examples of ISIL identifiers: https://slks.dk/english/work-areas/libraries-and-literature/library-standards/examples

I think we should also enforce the format they suggest. It is described here: https://slks.dk/english/work-areas/libraries-and-literature/library-standards/structure. Also pasting below the first part of the description (please check the link for more details):

> The ISIL is a variable length identifier. The ISIL consists of a maximum of 16 characters, using digits (Arabic numerals 0 to 9), unmodified letters from the basic Latin alphabet and the special marks solidus (/), hyphen-minus (-) and colon (:). Latin letters modified with one or more diacritics and letters from alphabets other than Latin cannot be used in the ISIL.
> 
> Each ISIL identifier shall be unique when normalized to the repertoire of characters specified in ISO/IEC-10646-1. 
> 
> ISIL country code and non-country code prefixes are case insensitive. The case sensitivity of the library code shall be decided at the national level. For instance, in Finland FI-Ht and FI-HT are two different ISILs. In the UK, GB-UkLoRHS and GB-uklorhs are two variants of the same ISIL and identify the same organization.
> 
> An ISIL is made up by two components: a prefix and a unit identifier, in that order, separated by a hyphen-minus. The hyphen-minus is a mandatory character in the ISIL string.

**Comment by ahakanzn** [comment]
deployed to prod
