### ISSUE TITLE
Something is off with the time when contacts etc are created

### ISSUE THREAD

**Issue by CecSve** [gbif/registry#619]
In this [example](https://registry.gbif.org/organization/ee9a9cbf-d62d-4d6d-a46a-769e0b1714d1/contact), one of the contacts was created 55 years ago, and I have noticed similar odd timelines with data from `registry-migration.gbif.org`. Can/should something be changed here?

**Comment by ahakanzn** [comment]
It seems the creation date defaulted to 1970-01-01 during migration from the old registry. This doesn’t affect functionality, so no changes are needed.
