### ISSUE TITLE
typeSpecimenCount and occurrenceCount in the GRSciColl collection API call

### ISSUE THREAD

**Issue by ckotwn** [gbif/registry#622]
Hello -

Reading the JSON response from a call to
```
https://api.gbif.org/v1/grscicoll/collection/d05697da-a398-4897-9bbb-a95b539a7547
```
There are `typeSpecimenCount` and `occurrenceCount` among the properties. However, neither is available in the UI form for filling in. Are these to be available in the form?

Thanks!

**Comment by ManonGros** [comment]
@ckotwn they are based on the occurrences linked to the GRSciColl entries. They are generated automatically.
