### ISSUE TITLE
GRSciColl identifier - have a preferred/primary identifier

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#625]
This is based on feedback we got from confused users who didn't which identifier to use to cite their collections and institutions.
I would like a "primary" field (checkbox) like we have for contacts.
The idea is for the primary identifier to be displayed (and cited) as preferred identifier. I assume that if no primary identifier is selected, then we would show the GRSciColl URL as preferred identifier.

I will log a separate issue for the UI.

**Comment by ahakanzn** [comment]
backend implementation of this is done
