### ISSUE TITLE
Endorsement request email to the PNMC should not contain an endorsement-link

### ISSUE THREAD

**Issue by jlegind** [gbif/registry#63]
Endorsement form email requests where the submission has the Participant Node Managers Committee as the endorsing node should have the 'endorsement link' stripped from the email text.
Usually the endorsement link will be manually removed before the email goes out to the PNMC contacts, but not always. 
Removing the link in the PNMC cases should fix the issue permanently.

**Comment by MattBlissett** [comment]
Looks like I haven't fixed this correctly.
