### ISSUE TITLE
align grscicoll api with others

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#631]
If it isn't a lot of work I think it would be nice to align the APIs a bit more.

**Multiselect on all fields**
On collections for example you can only specify one code currently. That is probably also most useful, but i do not see why it should be different from other fields. Even for binary fields we support multiple params for e.g. `occurrences/search?repatriated=true&repatriated=false`

That goes for both institutions and collection APIs

**Facets**
For both institutions and collections we could have facets where meaningful.
e.g. country, city, institution, code, gbifRegion, discipline

**Comment by marcos-lg** [comment]
Deployed a first version to UAT. 

Facets should work as in occurrence search, e.g.: https://api.gbif-uat.org/v1/grscicoll/collection/search?facet=COUNTRY&limit=1&country=DK&facetMultiselect=true&facetMinCount=150&facetLimit=2&facetOffset=1

you can see the fields you can facet by here:

https://api.gbif-uat.org/v1/enumeration/basic/CollectionFacetParameter
https://api.gbif-uat.org/v1/enumeration/basic/InstitutionFacetParameter


Also, all the searches should allow multivalue params (except ranges):

https://api.gbif-uat.org/v1/grscicoll/collection/search?code=SMI&code=WPR
https://api.gbif-uat.org/v1/grscicoll/collection?code=SMI&code=WPR
https://api.gbif-uat.org/v1/grscicoll/institution/search?code=SMI&code=WPR
https://api.gbif-uat.org/v1/grscicoll/search?country=DK&country=ES

**Comment by marcos-lg** [comment]
The first version is already deployed to PROD.

I'll keep the issue open to add some improvements such as allowing multiple ranges.

**Comment by MortenHofft** [comment]
https://api.gbif.org/v1/dataset/search?facet=type is allowed
but https://api.gbif.org/v1/grscicoll/collection/search?limit=0&facet=country fails
only upper constant case is allowed for facet names.

**Comment by marcos-lg** [comment]
I see, I can make it case insensitive.

**Comment by MortenHofft** [comment]
just to be precise: it isn't just upper lower. INSTITUTION_KEY is also institutionKey

**Comment by marcos-lg** [comment]
Fixes are deployed to prod.
