### ISSUE TITLE
bug: collection facets typestatus

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#634]
https://api.gbif-uat.org/v1/enumeration/basic/CollectionFacetParameter lists TYPE_STATUS as an option
but it returns an errur when trying
https://api.gbif.org/v1/grscicoll/collection/search?limit=0&facet=TYPE_STATUS

**Comment by MortenHofft** [comment]
Should it just be removed perhaps? I'm not sure what it is intended to actually facet on. isn't type an institution thing?

**Comment by marcos-lg** [comment]
TypeStatus is a descriptors field. I'll fix it.

**Comment by marcos-lg** [comment]
Fixed in prod.
