### ISSUE TITLE
LegacyDatasetResource removes Dataset description formating

### ISSUE THREAD

**Issue by cgendreau** [gbif/registry#7]
In the `updateDataset` method from `LegacyDatasetResource`, the dataset description is updated by the one submitted via the form as `LegacyDataset` object. This description is a single String and doesn't contain the notion of paragraph.

In order to preserve the description paragraph(s) the IPT should use the `ParagraphContainer` from the `registry-metadata` module to format the description in the same format.

**Comment by kbraak** [comment]
@cgendreau How about we also add instructions to the [Registry API documentation](http://www.gbif.org/developer/registry) with clear guidance how to format paragraphs properly and which fields this formatting can be applied to?
