### ISSUE TITLE
Dataset license URL http/https compatibility

### ISSUE THREAD

**Issue by reupost** [gbif/registry#73]
When updating a dataset with license = https://creativecommons.org/licenses/by/4.0/legalcode
it is showing up as 'Unsupported license' on the dataset page.

Updating a dataset with license = 'http://creativecommons.org/licenses/by/4.0/legalcode'
is correctly interpreted.

Given that creativecommons redirects you to the https pages now, would it be possible to accept both http:// and https:// when interpreting the licence?

**Comment by MattBlissett** [comment]
Thanks — the change is committed, but we don't deploy on Fridays. It will become active some time next week.

**Comment by reupost** [comment]
Thanks @MattBlissett , much appreciated :)
