### ISSUE TITLE
collection api performance

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#79]
A call to 
http://api.gbif-dev.org/v1/grbio/collection?limit=20&offset=&q=tardigrada takes 12.7 sec in dev and 8.5 sec in prod. That is surprisingly slow for a table with less than a 1000 rows.

**Comment by MortenHofft** [comment]
Also it seems there is no varnish? calling a slow endpoint 10 seconds later will still take 8 seconds.

**Comment by asturcon** [comment]
Deployed in DEV and DEMO

**Comment by asturcon** [comment]
Deployed in UAT and PROD
