### ISSUE TITLE
Use Java 8 Date to represent datasets temporalCoverages

### ISSUE THREAD

**Issue by cgendreau** [gbif/registry#8]
Currently `temporalCoverages` uses `java.util.Date` which leads to incorrect API response:
```
"temporalCoverages": [
{
"@type": "range",
"start": "1913-12-31T23:00:00.000+0000",
"end": "2015-12-31T23:00:00.000+0000"
}
],
```

reported through: https://github.com/gbif/portal-feedback/issues/165

**Comment by marcos-lg** [comment]
This seems to be already fixed.
