### ISSUE TITLE
institutions api sends array with nulls

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#83]
e.g. http://api.gbif.org/v1/grbio/institution/b534ffbc-5ec9-4ff8-9670-3c15343b9f47

```
"additionalNames": [
null
],
```

**Comment by asturcon** [comment]
This happens with more methods http://api.gbif-dev.org/v1/organization/57254bd0-8256-11d8-b7ed-b8a03c50a862

So we need to fix it for all the registry entities either by fixing the data in the DB or changing the StringArrayTypeHandler

**Comment by MortenHofft** [comment]
This is something new - it haven't been like this in the past. The occurrence API response has also changed. I think @MattBlissett might know more about the cause.

**Comment by asturcon** [comment]
Could be related to this issue in occurrence https://github.com/gbif/occurrence/issues/85

**Comment by MattBlissett** [comment]
No, that is a data content problem.

However, it might be related to https://github.com/gbif/occurrence/issues/82.

See https://github.com/gbif/gbif-common-ws/tree/master/src/main/java/org/gbif/ws/mixin and https://github.com/gbif/gbif-api/tree/master/src/main/java/org/gbif/api/jackson .

**Comment by asturcon** [comment]
Fixed in DEV and DEMO

**Comment by asturcon** [comment]
Deployed in UAT and PROD
