### ISSUE TITLE
synchronization endpoint do not accept jwt

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#85]
... as far as i can see.

A post to for example 
https://registry-demo.gbif-dev.org/installation/7857582d-033e-4c54-92e1-330638596cef/synchronize

works in https://registry-demo.gbif-dev.org/web/#/home but not when using the jwt in the new registry console.

**Comment by asturcon** [comment]
I just tried and worked for me. @MortenHofft Can you please try again? maybe the token was expired or was generated for a user with insufficient privileges

**Comment by MortenHofft** [comment]
I can confirm that it works (shrug) - sorry.
