### ISSUE TITLE
grbio renamed to grscicoll

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#93]
It has been decided that grbio should be renamed (everywhere?). That includes the API
so `/grscicoll/collection...` instead of `/grbio/collection...` etc.

GRBIO also appears in enums. For that i cannot say, but i guess it would be most consistent.

**Comment by MortenHofft** [comment]
I suspect enums stay as they are? at least the URIs since they point to things like http://grbio.org/cool/71qz-j715

**Comment by asturcon** [comment]
path of urls changed. Deployed in DEV and DEMO
