### ISSUE TITLE
CORS and preflight redirect

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#94]
It might be for good reasons, but as a consumer it would be nice if redirects also worked with CORS headers

```
Access to XMLHttpRequest at 'http://registry-api.gbif-dev.org/dataset/6663666e-475d-4df2-ad99-823995ad14f0' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

**Comment by MattBlissett** [comment]
This is a new API endpoint, so I'd prefer to say it's HTTPS only.  That is more secure than tolerating an HTTP→HTTPS redirect, and removes the pointless round-trip for every request that would otherwise not be noticed.

**Comment by MortenHofft** [comment]
👍 but currently it does redirect
