### ISSUE TITLE
Search for country in Organizations

### ISSUE THREAD

**Issue by jlegind** [gbif/registry#95]
Searching for 'turkey' under organization yields only one publisher: GEBZE TECHNICAL UNIVERSITY
https://registry.gbif.org/organization/d9d8121f-37ee-41d0-bcd4-e3a73d802cd9
However there are two Turkish publishers; the other is Duzce University
https://registry.gbif.org/organization/af5132dd-d748-44c4-8fed-42bdce8be726

It would be useful if searching a country name would return all publishers in that country.

**Comment by asturcon** [comment]
Currently, we index the countries using the 2-letter code, so searching by "TR" returns both organizations. In the first case it appears because "Turkey" is present in the address field.

**Comment by MortenHofft** [comment]
And when the site is translated it becomes unclear if a search for "tyskland" should return DE/Germany. We have the same challenge in the portal. Ideally it would, but that would require the APIs to index the translated values for enums.

**Comment by MortenHofft** [comment]
If this is desired, then it is probably more feasible to have a country filter countryCode=DE instead of the free text search.

**Comment by fmendezh** [comment]
Closing this issue, the country filter seems to be in place now
see [http://api.gbif.org/v1/organization?country=CR](http://api.gbif.org/v1/organization?country=CR)
