### ISSUE TITLE
User scopes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#99]
Users can have scopes. But it isn't documented how those scopes can be assigned. This might already be implemented as an API? 
What we want is a way to edit these scopes on users if logged in as ADMIN in the registry

**Comment by asturcon** [comment]
Just to clarify it, this is a new endpoint with CRUD operations for the editor_rights table

**Comment by asturcon** [comment]
@MortenHofft I just noticed that this is already implemented:
- GET admin/user/{username}/editorRight
- POST admin/user/{username}/editorRight 
- DELETE admin/user/{username}/editorRight/{key}

For the GET you need either ADMIN or USER role. For the other only ADMIN role.

**Comment by luckyluck** [comment]
@asturcon, would you mind to clarify what the data should be sent in the POST request to add a new item as a role scope and what should be the Content-type? Thank you in advance.

**Comment by asturcon** [comment]
@luckyluck I just checked the code and it expects a UUID (the key of the entity to add)  in the body and the content type is JSON. I remember we had a similar issue in collections trying to send a UUID as JSON and I changed the content type to plain text. So I think I should change it here too, right?

**Comment by luckyluck** [comment]
@asturcon looks like you are right. Thank you in advance for changes.

**Comment by asturcon** [comment]
@luckyluck this should be in DEMO now
